KOGITO-7211: KN CLI workflow plugin
apache/incubator-kie-tools pull request #1051
Opened 2022-06-28 15:51 UTC by ljmotta

## JIRA
https://issues.redhat.com/browse/KOGITO-7211

##  On this PR
Adds the new `kn-plugin-workflow` package.

### About
This package is a plugin for the Knative CLI. It adds the `workflow` subcommand, resposible to `create`, `build` and `deploy` workflow projects built in Quarkus.

Read more about Knative plugins [here](https://knative.dev/docs/install/client/kn-plugins/).

#### Commands
All commands have the `--help` and `--verbose` option.
- **create**
 `kn workflow create`
  
  Create a Quarkus workflow project with the following extensions:
   - kogito-quarkus-serverless-workflow
   - kogito-addons-quarkus-knative-eventing
   - resteasy-reactive-jackson
   - quarkus-kubernetes

   Also creates a "hello world" workflow file in the ./<project-name>/src/main/resources folder.

- **build**
 `kn workflow build`
  Builds a Quarkus workflow project and generates a container image

- **deploy**
  `kn workflow deploy`
  Deploys a previous built Quarkus workflow project using the ./<project-name>/target/kubenertes deployment files.

2022-06-28 21:16 UTC, ljmotta commented
Hi @spolti, I've added you as a reviewer. I guess you could give some insightful feedback.

2022-06-29 13:44 UTC, tiagobento approved these changes

2022-06-29 14:21 UTC, spolti requested changes

2022-06-29 14:21 UTC, spolti commented on .github/workflows/staging_build.yml
> +          KN_PLUGIN_WORKFLOW_quarkusVersion: "2.9.2.Final"
AFAIK we are using Quarkus 2.10.0.Final.

2022-06-29 14:21 UTC, spolti commented on .github/workflows/staging_build.yml
> +          KN_PLUGIN_WORKFLOW_quarkusVersion: "2.9.2.Final"
@ricardozanini can you please confirm?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/Makefile
> +	GO111MODULE=on GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/kiegroup/kie-tools/kn-plugin-workflow/pkg/common.QUARKUS_VERSION=$(build-env knPluginWorkflow.quarkusVersion)'" -o dist/kn-
imho it is better provide three binaries, linux, windows and mac, e.g. https://github.com/kiegroup/kogito-operator/blob/c655c31b0c62ca9743daeab91ba7e3e06ec43cb8/hack/go-build-cli.sh#L54

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/README.md
> +`kn-plugin-workflow` is a plugin of the Knative Client, to enable users to quickly set up a local Quarkus workflow project from the command line.
Maybe a Kogito Serverless Workflow?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/README.md
> +Note: In order to use the `workflow` plugin, you must install [Java](https://www.java.com/en/download/help/download_options.html) at least version 11, [Maven](https://maven.apache.org/install.html) a
maybe use bullets for each prerequisite

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/README.md
> +kn workflow create --name myproject
what this create --name project does?
create a namespace on the target k8s cluster or just use Quarkus to scaffold a new project with the required extensions?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/README.md
> +kn workflow create --name myproject
maybe just kn workflow create my-project would be better.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/root/root.go
> +		Long:  "Manage Quarkus workflow projects",
maybe Kogito?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/constants.go
> +const QUARKUS_DEFAULT_EXTENSIONS = "kogito-quarkus-serverless-workflow,kogito-addons-quarkus-knative-eventing,resteasy-reactive-jackson,quarkus-kubernetes"
you can use const(..)

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +	dockerCheck := exec.Command("docker", "stats", "--no-stream")
for docker it is probably better to use the go client
https://pkg.go.dev/github.com/docker/docker/client

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/constants.go
> +var QUARKUS_VERSION = "2.9.2.Final"
we might need to update the Quarkus version

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/verbose.go
> +func VerboseLog(stdout io.Reader, stderr io.Reader) {
for Verbose I would use a logging api like `log "github.com/sirupsen/logrus"` and when verbose is enabled just set it at Viper's init config: 

```go
	if viper.GetBool("verbose") {
		log.SetLevel(log.DebugLevel)
	}
```

then use the log levels as usual.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/helper.go
> +	var (
seems these vars are used more than once, can't it be moved to a func?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/helper.go
> +	stdout, _ := command.StdoutPipe()
these two can probably be removed if you use logging as suggested.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +type DeployConfig struct {
maybe it is better move structs to another file or to the beginning of this one.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +	} else if errors.Is(err, os.ErrNotExist) {
is there a specific reason to return error nil?
maybe just use else return false, err, wdyt?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		SuggestFor: []string{"delpoy", "deplyo"},
```suggestion
		SuggestFor: []string{"delpoy", "deploy"},
```

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		Short: "Deploy a Quarkus workflow project",
Kogito Serverless Workflow?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	err = ioutil.WriteFile(workflowFilePath, data, 0644)
why not use decorators or json parser?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	overriten with the --image and with all --image-* options
```suggestion
	overriten with the --image or with others image options, see help for more information.
```

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	required. To authenticate to your registry, use "docker login" or any other
is there any plans to support podman as well?
at beginning we could probably support both.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# Build using Jib instead of Docker. (Read more: https://quarkus.io/guides/container-image#jib)
you could refer our guide here: https://kiegroup.github.io/kogito-docs/serverlessworkflow/main/cloud/build-workflow-image-with-quarkus-cli.html

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# Docker is still required to save the image
Jib can build images without having docker installed.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	cmd.Flags().Bool("jib", false, "Use Jib extension to generate the image (Docker is still required to save the generated image)")
see my previous comment.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +type BuildConfig struct {
see the other comment abut structs.

once suggestion is maybe create a common file called types.go and house all structs there.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		addExtension = exec.Command("./mvnw", "quarkus:add-extension",
maybe enforce the Quarkus version here.
if the maven wrapper is in use, maybe maven can be optional and we could the wrapper handle the installation if it is not available?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	if len(cfg.ImageName) > 0 {
what is the value expected here?
is the image name only or the full image with registry and context?

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		name = imageArray[1]
same

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +func getImageName(registry string, repository string, name string, tag string) string {
maybe just image to avoid confusion with the image name.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	var registry = "docker.io"
imho we shouldn't hardcode it, we can leave to docker daemon to pull from the configured registries.
or default to quay.io.

2022-06-29 14:21 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		push += "true"
why appending? 
using just return `"-Dquarkus.container-image.push=" + strconv.ParseBool(s)` wouldn't return the same value?

2022-06-29 15:43 UTC, ljmotta commented on packages/kn-plugin-workflow/Makefile
> +	GO111MODULE=on GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/kiegroup/kie-tools/kn-plugin-workflow/pkg/common.QUARKUS_VERSION=$(build-env knPluginWorkflow.quarkusVersion)'" -o dist/kn-
The three binaries are created using the `build` script in the `package.json` file. The Makefile is a helper file to build the windows version.

2022-06-29 15:45 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +`kn-plugin-workflow` is a plugin of the Knative Client, to enable users to quickly set up a local Quarkus workflow project from the command line.
Change the `Quarkus workflow` to `Kogito Serverless Workflow` or `Quarkus Kogito Serverles Workflow`?

2022-06-29 15:45 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +Note: In order to use the `workflow` plugin, you must install [Java](https://www.java.com/en/download/help/download_options.html) at least version 11, [Maven](https://maven.apache.org/install.html) a
Sure!

2022-06-29 15:46 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +kn workflow create --name myproject
The second option. It will scaffold a new Quarkus project with the required extensions. I'll improve the documentation.

2022-06-29 15:47 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/root/root.go
> +		Long:  "Manage Quarkus workflow projects",
Should I remove the Quarkus?

2022-06-29 16:04 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +	dockerCheck := exec.Command("docker", "stats", "--no-stream")
Oh! I didn't know about this client, but for this case I guess it would be better to keep this way. This command is just used to check if the docker daemon is running, and we don't use the docker API for any other propuse. I'm not sure if we need to add a new dependency for that. But I'm not used to develop in go. WDYT?

2022-06-29 16:12 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/common/verbose.go
> +func VerboseLog(stdout io.Reader, stderr io.Reader) {
I wasn't aware of this library. I'm going to take a look it.

2022-06-29 16:14 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		SuggestFor: []string{"delpoy", "deplyo"},
This is a list of strings in case the user make a typo. `delpoy` and `deplyo` (typos) suggests `deploy` (correct).

2022-06-29 16:20 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/common/helper.go
> +	stdout, _ := command.StdoutPipe()
`stdout` and `stderr`. captures the command output to be logged. I guess the `logging` can be used to print the values of this variables.

2022-06-29 16:29 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# Build using Jib instead of Docker. (Read more: https://quarkus.io/guides/container-image#jib)
Sure!

2022-06-29 16:31 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	required. To authenticate to your registry, use "docker login" or any other
I couldn't find a Quarkus extension that uses podman to build the image. So I've tried to keep everything using Docker.

2022-06-29 16:45 UTC, ricardozanini commented on .github/workflows/staging_build.yml
> +          KN_PLUGIN_WORKFLOW_quarkusVersion: "2.9.2.Final"
It is. We need a way to sync with the pipelines to update here, if possible.

2022-06-29 16:48 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# Docker is still required to save the image
Oh, it's true. I read in the [quarkus docs](https://quarkus.io/guides/container-image) that Docker is required if the push option is false. I will update the help text.

2022-06-29 17:01 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	if len(cfg.ImageName) > 0 {
The `ImageName` is the image name only. `ImageName` can be set with the `--image-name` flag. If not, the name is parsed from the `--image` flag. In this case, the value of the `name` will be in one of the following:
 -  `imageArray[0]` if  `--image=[name]:[tag]`
 -  `imageArray[1]` if  `--image=[repository]/[name]:[tag]`
 - `imageArray[2]` if `--image=[registry]/[repository]/[name]:[tag]`

2022-06-29 17:20 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +kn workflow create --name myproject
This is a great suggestion. But for now we thought about keeping the `name` flag, and we're going to revisit this in the near future, as we're going to add subcommands to the CLI.

2022-06-29 17:28 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +type DeployConfig struct {
I'm going to move to the beginning of the file as I think it's better to keep each command separated from each other.

2022-06-29 17:33 UTC, ricardozanini reviewed
Great work! I made a few comments if you don't mind. Many thanks!

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/Makefile
> +	GO111MODULE=on GOOS=windows GOARCH=amd64 go build -ldflags "-X 'github.com/kiegroup/kie-tools/kn-plugin-workflow/pkg/common.QUARKUS_VERSION=$(build-env knPluginWorkflow.quarkusVersion)'" -o dist/kn-
Would be nice to offer them all for other contributors, IMO.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/README.md
> +`kn-plugin-workflow` is a plugin of the Knative Client, to enable users to quickly set up a local Quarkus workflow project from the command line.
Kogito Serverless Workflow

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/README.md
> +### Instalation
Maybe we can add all this information in the guides (https://github.com/kiegroup/kogito-docs) instead and link back here.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/README.md
> +Creates a new Quarkus workflow project named "myproject":
```suggestion
Creates a new Kogito Serverless Workflow project named "myproject":
```

Since this will be migrated to the guides, we can discuss more of this doc there.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	will be a container image.
```suggestion
	This command builds the workflow project in the current directory resulting
	in a container image.
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	Those two files are used by the deploy command.
```suggestion
	During the build, a knative.yml file will be generated on the ./target/kubernetes folder.
	If your workflow uses eventing, an additional kogito.json is also generated.
	The deploy command uses both these files.
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	required. To authenticate to your registry, use "docker login" or any other
```suggestion
	Authentication is required If you want to push the resultant image to a private registry.
	To authenticate to your registry, use "docker login" or any other
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# project directory name
```suggestion
	# project's directory name
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# it to remote registry (authentication can be necessary, use docker login)
```suggestion
	# it to the remote registry (authentication can be necessary, use docker login)
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	# Build from the local directory, passing separadtly image options
```suggestion
	# Build from the local directory, passing separately image options
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	cmd.Flags().StringP("image", "i", "", "Full image name in the form [registry]/[repository]/[name]:[tag]")
```suggestion
	cmd.Flags().StringP("image", "i", "", "Full image name in the form of [registry]/[repository]/[name]:[tag]")
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		addExtension = exec.Command("./mvnw", "quarkus:add-extension",
I think `.mvnw` is already on the path after generating the project. And if the project was generated, then Maven is already present.

I haven't gone through all the code yet, but I imagine we are checking for the prerequisites. At least I know Quarkus CLI should do.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	if len(cfg.ImageName) > 0 {
I think it's only the image name part (not the full part), since this is created based on the CLI options, you can compose it via the args or pass the full name.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	./<project-name>/src/main/resources directory.
```suggestion
	This command creates a Kogito Serverless Workflow project in the current directory.
	It sets up a Quarkus project with minimal extensions to build a workflow
	project.
	The generated project has a "hello world" workflow.sw.json located on the
	./<project-name>/src/main/resources directory.
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +		Long: `Create a Quarkus workflow project
```suggestion
		Short: "Create a Kogito Serverless Workflow project",
		Long: `
```

You're already saying that this command creates a project in the next line.
The `Long` attribute shows the extended description.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	# By default the project will be named "new-project"
```suggestion
	# By default the project is named "new-project"
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	# Multiple can be add by separete then with a comma
```suggestion
	# You can add multiple extensions by separating them with a comma
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	cmd.Flags().StringP("name", "n", "new-project", "Project name that will be created in the current directory.")
```suggestion
	cmd.Flags().StringP("name", "n", "new-project", "Project name created in the current directory.")
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	fmt.Println("Creating a Quarkus workflow project...")
```suggestion
	fmt.Println("Creating a Kogito Serverless Workflow project...")
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	fmt.Printf("🚀 Create took: %s \n", finish)
```suggestion
	fmt.Printf("🚀 Project creation took: %s \n", finish)
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/create.go
> +}
I think we can use a templating engine instead of hardcoding the workflow in the codebase. Eventually, a user could pick their starting example. Also to maintain this code in the future will be way easier.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		Short: "Deploy a Quarkus workflow project",
```suggestion
		Short: "Deploy a Kogito Serverless Workflow project",
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		Long: `Deploy a Quarkus workflow project
```suggestion
		Long: `
```
Not sure if we need to repeat ourselves here. I can't remember what cobra prints, but if this is the pattern feel free to ignore this and the other comment.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +	is required before using the deploy command.
```suggestion
	Deploys the workflow project in the current directory. 
	By default, this command uses the ./target/kubernetes folder to find
	the deployment files generated in the build process. The build step
	is required before using the deploy command.
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +	cmd.Flags().StringP("path", "p", "./target/kubernetes", fmt.Sprintf("%s path to knative deploy files", cmd.Name()))
```suggestion
	cmd.Flags().StringP("path", "p", "./target/kubernetes", fmt.Sprintf("%s path to knative deployment files", cmd.Name()))
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		deploy := exec.Command("kubectl", "apply", "-f", fmt.Sprintf("%s/kogito.yml", cfg.Path))
```suggestion
		deploy := exec.Command("kubectl", "apply", "-f", fmt.Sprintf("%s/kogito.json", cfg.Path))
```

I think it's `kogito.json`. Can you confirm, please?

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		fmt.Println("✅ Knative events binding sucessufully created")
```suggestion
		fmt.Println("✅ Knative Eventing bindings successfully created")
```

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +	if _, err := os.Stat(fmt.Sprintf("%s/kogito.yml", cfg.Path)); err == nil {
```suggestion
	if _, err := os.Stat(fmt.Sprintf("%s/kogito.json", cfg.Path)); err == nil {
```

Same thing here.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +		fmt.Println("At least Java 11 is required to use this command")
```suggestion
		fmt.Printf("At least Java %.2d is required to use this command", JAVA_VERSION)
```

I imagine you have the prereqs in an enum/const value?

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +		fmt.Println("At least Maven 3.8.1 is required to use this command")
```suggestion
		fmt.Println("At least Maven 3.8.1 is required to use this command")
```

Same thing here. So we can change it in one place and propagate it to the rest of the code base.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +	dockerCheck := exec.Command("docker", "stats", "--no-stream")
That's fine sticking with the command. But just FYI, go will import only the dependency required files in the final package. Might be too much, tough. We can consider using the client if we have other use cases or to make this check more robust.

They might do checks there that we do not. Anyhow, I think this is fine for now.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +		fmt.Println("If it's already installed, check if it's running")
```suggestion
		fmt.Println("If it's already installed, check if the docker daemon is running")
```

For instance, the docker lib might be more precise here.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +}
nitpick; I think you can rely on regular expressions here and use the grouping feature to grab the major/minor/patch parts of the semver. Don't need to implement it now, though. Just something to keep in mind.

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/root/root.go
> +		Long:  "Manage Quarkus workflow projects",
Yes

2022-06-29 17:33 UTC, ricardozanini commented on packages/kn-plugin-workflow/pkg/root/root.go
> +		Long:  "Manage Quarkus workflow projects",
```suggestion
		Long:  "Manage Kogito Serverless Workflow projects",
```

2022-06-29 18:20 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		addExtension = exec.Command("./mvnw", "quarkus:add-extension",
`.mvnw` is generated with the project, and Java and Maven versions are checked.

2022-06-29 19:26 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		deploy := exec.Command("kubectl", "apply", "-f", fmt.Sprintf("%s/kogito.yml", cfg.Path))
It's a kogito.yml file.

2022-06-29 19:30 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/checks.go
> +	dockerCheck := exec.Command("docker", "stats", "--no-stream")
that's fine for now.

2022-06-29 19:33 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/deploy.go
> +		SuggestFor: []string{"delpoy", "deplyo"},
oh, ok, didn't notice that :D

2022-06-29 19:33 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	required. To authenticate to your registry, use "docker login" or any other
Jib supports podman builder as well.

2022-06-29 19:56 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/common/verbose.go
> +func VerboseLog(stdout io.Reader, stderr io.Reader) {
I've created a [JIRA](https://issues.redhat.com/browse/KOGITO-7479) to do a future upgrade using a logging library and improve the logs of the plugin. I need to take a better look in the setups and configs.

2022-06-29 20:06 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +### Instalation
I guess we can keep in both places. I've created a [JIRA](https://issues.redhat.com/browse/KOGITO-7480) to write a more complete doc for the kogito-docs.

2022-06-29 20:10 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/create.go
> +	err = ioutil.WriteFile(workflowFilePath, data, 0644)
I've updated to use json parser.

2022-06-29 20:27 UTC, ricardozanini commented on packages/kn-plugin-workflow/README.md
> +### Instalation
Hmm keeping in both places might be hard to maintain.

2022-06-29 21:13 UTC, ljmotta commented
@ricardozanini @spolti  Thanks a lot for your effort in reviewing this PR. I believe I've made all the requested changes and answered your questions. If I missed something, let me know.

Also, I've added Podman support with the following command:
`kn workflow build --jib-podman`

@spolti I've created a JIRA to work as an enhancement in the near future regarding the [logging library](https://issues.redhat.com/browse/KOGITO-7479).

@ricardozanini I believe this README is the first version of the documentation and is something to improve before adding it to the kogito-docs, so I've created a [JIRA](https://issues.redhat.com/browse/KOGITO-7480) for it, but if you prefer I can send a PR with the installation steps the way it is.

2022-06-29 21:15 UTC, ljmotta commented on packages/kn-plugin-workflow/README.md
> +### Instalation
That's true. I can work on a more complete version to add there, WDYT?

2022-06-29 21:17 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	required. To authenticate to your registry, use "docker login" or any other
I've add podman support through jib.

2022-06-30 12:29 UTC, ricardozanini commented
> @ricardozanini I believe this README is the first version of the documentation and is something to improve before adding it to the kogito-docs, so I've created a [JIRA](https://issues.redhat.com/browse/KOGITO-7480) for it, but if you prefer I can send a PR with the installation steps the way it is.

@ljmotta the kn CLI is a hard requirement for DP1. Therefore, it would be nice to have the guide as soon as possible. I think the README info we have here is enough for now. Open the PR, I'll add a few people there that will have the final say.

2022-06-30 13:46 UTC, ederign commented
@ricardozanini Luiz will work on the guides for this on his next task.  So I think on doc side, we will be good to go as well.

2022-06-30 13:48 UTC, ederign approved these changes

2022-06-30 13:51 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +		addExtension = exec.Command("./mvnw", "quarkus:add-extension",
maven and java, yes, but Quarkus, if you do not define the version with the mvn quarkus plugin, it will use the latest if I am not mistaken, or as Zanini suggested, Quarkus CLI would be better to use.

2022-06-30 13:51 UTC, spolti commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	if len(cfg.ImageName) > 0 {
@ljmotta will you update it to use compose?

2022-06-30 13:52 UTC, spolti commented on packages/kn-plugin-workflow/pkg/common/constants.go
> +var QUARKUS_VERSION = "2.10.1.Final"
please align these versions, on the yaml files you have set to 2.10.0

2022-06-30 14:04 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/common/constants.go
> +var QUARKUS_VERSION = "2.10.1.Final"
done

2022-06-30 14:54 UTC, ricardozanini commented
@ljmotta @ederign just to reinforce, my comment is not a blocker. We can open a PR later linking the guide in the README. My only concern is to not keep the same information in two places.

2022-06-30 15:04 UTC, ljmotta commented on packages/kn-plugin-workflow/pkg/command/build.go
> +	if len(cfg.ImageName) > 0 {
I'm not sure if I've followed. It has the option to pass the full name with `--image` or compose it using the flags: `--image-registry`, `--image-repository`, `--image-name`, `--image-tag`.

2022-06-30 15:06 UTC, ricardozanini approved these changes

2022-06-30 15:08 UTC, spolti approved these changes

2022-06-30 15:38 UTC, paulovmr approved these changes

2022-06-30 18:17 UTC, merged

2022-06-30 18:17 UTC, ederign commented
great work @ljmotta !

2022-07-15 12:40 UTC, barboras7 reviewed
Hi @ljmotta,
I know that this PR has already been merged but since the README from the PR will probably be used in the guides for serverless workflow, I consider this a good place to start a discussion about some fixes in the README. If you will agree with my suggestions, I can open a Jira issue. :slightly_smiling_face:

2022-07-15 12:40 UTC, barboras7 commented on packages/kn-plugin-workflow/README.md
> +- [Docker](https://docs.docker.com/engine/install/) (Optional)
I am not sure if marking Docker as "Optional" is correct, since Docker is required for `build` command.

2022-07-15 12:40 UTC, barboras7 commented on packages/kn-plugin-workflow/README.md
> +
I was not able to use this plugin without installation of Maven Wrapper (mvnw). Either that was some kind of issue (and probably needs to be fixed) or it is expected and therefore should be mentioned in this guide.