KOGITO-7501:  [SWF Editor] replicate the JSON functionalities to YAML in serverless-workflow-language-service
apache/incubator-kie-tools pull request #1064
Opened 2022-07-05 10:23 UTC by fantonangeli

Issue: https://issues.redhat.com/browse/KOGITO-7501

PLEASE, DO NOT MERGE BEFORE:
[KOGITO-6903: Integrate stunner-based SWF Diagram Editor with multiplying architecture](https://github.com/kiegroup/kie-tools/pull/1052)

This is the first step for JSON/YAML parity. I replicated the JSON functionality to YAML, maintaining the logic already developed for JSON.
I couldn't find an equivalent `jsonc` package to parse YAML. I used https://www.npmjs.com/package/yaml-language-server-parser and converted the result to the same type of data to reuse the logic.

2022-07-11 14:59 UTC, caponetto commented
@fantonangeli could you please update your branch? https://github.com/kiegroup/kie-tools/pull/1052 is merged.

2022-07-11 16:21 UTC, tiagobento requested changes
Nice work, @fantonangeli! Left some comments inline.

2022-07-11 16:21 UTC, tiagobento commented on packages/serverless-workflow-language-service/src/channel/SwfYamlLanguageService.ts
> +export class SwfYamlLanguageService extends SwfLanguageService {
Can we try and and make this with composition instead of inheritance? I think it works better on the long run.

2022-07-11 16:21 UTC, tiagobento commented on packages/vscode-extension-serverless-workflow-editor/src/extension/languageService/VsCodeSwfLanguageService.ts
> +    }
Creating the LS may become a heavy operation in the future. I would personally prefer avoiding the creation of a new instance every time we query for a different file extension. IMHO, we could have `this.jsonLs` and `this.yamlLs`, and return the right instance on the `ls` getter, instead, which would then accept a parameter with the file extension. WDYT?

2022-07-11 16:30 UTC, tiagobento commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +            newText: JSON.stringify(swfFunctionRefArgs, null, 2),
Will this work with YAML too? I mean, this is a JSON snippet, right?

2022-07-11 16:30 UTC, tiagobento commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +              newText: JSON.stringify(swfFunctionRef, null, 2),
Same here..

2022-07-11 16:30 UTC, tiagobento commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +                newText: JSON.stringify(swfFunction, null, 2) + separator,
Same here..

2022-07-12 10:22 UTC, fantonangeli commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +            newText: JSON.stringify(swfFunctionRefArgs, null, 2),
Yes, it works because the code where it belongs queries over the `rootNode` that is a `SwfLSNode` type for both JSON and YAML
This way, for YAML, I reused the already working code made for JSON.

2022-07-12 10:22 UTC, fantonangeli commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +              newText: JSON.stringify(swfFunctionRef, null, 2),
https://github.com/kiegroup/kie-tools/pull/1064#discussion_r918803391

2022-07-12 10:22 UTC, fantonangeli commented on packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
> +                newText: JSON.stringify(swfFunction, null, 2) + separator,
https://github.com/kiegroup/kie-tools/pull/1064#discussion_r918803391

2022-07-12 12:56 UTC, yesamer commented
jenkins retest this

2022-07-12 13:39 UTC, tiagobento commented
@fantonangeli I'm trying the SWF Editor VS Code Extension from this PR's branch, and I see that for YAML files, the bindings are not yet set up.

To try and test it, I changed the glob pattern from `**/*.json` to `**/*.{json,yaml,yml}`, and it kind of worked.. the code lenses are displayed [1] (although they should've been 1 line above), but I couldn't get the completion items to work.. am I missing something?

[1] 
![image](https://user-images.githubusercontent.com/1584568/178503418-ebdfcb0b-fd59-4588-9f07-6cbe0232f14d.png)

2022-07-12 13:51 UTC, fantonangeli commented
@tiagobento In this issue I preferred to work mainly on `serverless-workflow-language-service` for the YAML support, testing it with Jest and making sure the logic in this PR is on the right way.
After this, I will work on `vscode-extension-serverless-workflow-editor` and `serverless-workflow-text-editor`

> @fantonangeli I'm trying the SWF Editor VS Code Extension from this PR's branch, and I see that for YAML files, the bindings are not yet set up.
> 
> To try and test it, I changed the glob pattern from `**/*.json` to `**/*.{json,yaml,yml}`, and it kind of worked.. the code lenses are displayed [1] (although they should've been 1 line above), but I couldn't get the completion items to work.. am I missing something?
> 
> [1] ![image](https://user-images.githubusercontent.com/1584568/178503418-ebdfcb0b-fd59-4588-9f07-6cbe0232f14d.png)

2022-07-12 14:03 UTC, tiagobento commented
@fantonangeli Ok, got it! 

You can try and do the changes I did to enable it in the VS Code Extension too, this might give you good ideas for unit tests. One thing that I learned while developing the autocompletion for JSON is that some cases you can only catch when you try and edit the file "live". One thing that I noticed, for example, is that the code lenses disappear if there's a syntax error anywhere in the YAML file. That's something that the JSONC parser is resilient to, which I think is very important.

Anyway, no problem with splitting in two or more PRs! :)

2022-07-12 14:08 UTC, fantonangeli commented
@tiagobento Thank you for your tip, I will keep it in mind for the next step.

2022-07-12 17:03 UTC, fantonangeli commented on packages/serverless-workflow-language-service/src/channel/SwfYamlLanguageService.ts
> +export class SwfYamlLanguageService extends SwfLanguageService {
I changed it in commit:
https://github.com/kiegroup/kie-tools/pull/1064/commits/dffcd322b23fe8293785dc2cab71f9f5b81df62e

But I had to write more code in very important classes (SwfJsonLanguageService, SwfYamlLanguageService). I'm just thinking about possible mistakes in the future.
What do you think about it?

2022-07-12 19:28 UTC, tiagobento commented
@fantonangeli Please consider https://github.com/fantonangeli/kie-tools/pull/3

2022-07-13 14:02 UTC, tiagobento approved these changes

2022-07-14 11:27 UTC, caponetto approved these changes
Great stuff! Thanks, @fantonangeli and @tiagobento!

@fantonangeli please also consider adapting the `serverless-logic-sandbox` package as well when you work on `vscode-extension-serverless-workflow-editor` and `serverless-workflow-text-editor`.

2022-07-14 11:34 UTC, yesamer approved these changes

2022-07-14 12:07 UTC, fantonangeli commented
@caponetto Thank you, noted here
https://issues.redhat.com/browse/KOGITO-7568

2022-07-14 13:12 UTC, merged