KOGITO-7633 - SWF Viewer - Usability improvements for mediators (Preview Window)
apache/incubator-kie-tools pull request #1124
Opened 2022-07-26 12:27 UTC by Josephblt

**JIRA:** [KOGITO-7633 - SWF Viewer - Usability improvements for mediators (Preview Window)](https://issues.redhat.com/browse/KOGITO-7633)

Added preview button beside zoom selector control.
Added preview window.

**VS Code Extension:** [Serveless Workflow Editor]
(https://drive.google.com/file/d/13XJWcepJ-oy-X3HAB-Srt3n6dkUlmT0v/view?usp=sharing)

2022-08-25 07:24 UTC, domhanak requested changes
There is one blocker imho, not sure thought, the JIRA itself has no acceptance criteria so I do not know what is the target of testing.
I check the preview buttong from widget and the problem is that when I click `Preview` the widget disappear, so I am not able to reset the viewer.

2022-08-25 07:24 UTC, domhanak commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/mediators/ZoomLevelSelectorPresenter.java
> +
missing method body?

2022-09-19 14:00 UTC, romartin requested changes
Hey @Josephblt 

Code looks good!

I am also quickly testing the UI and 2 issues, for now. Will continue testing. Can you please take a look at those?

1. Use come icon for the preview button (instead of text)
2. Once I toggle the preview, it appears floating near to the top left corner... but it should be floating on top of the mediators widget (buttons). It should look like a expand/collapse panel. See screenshot:

![Screenshot from 2022-09-19 15-58-07](https://user-images.githubusercontent.com/4602417/191035259-783788c7-1c79-4de8-9436-7869d0d80531.png)

Thanks!

2022-10-10 20:47 UTC, romartin commented
Hey @Josephblt 

Thanks for the fixes and improvements. I still found a **few things to do**, let me know what you think:

1. The preview window is too big IMO, maybe we can do it smaller. There is lot of unused free space there.... see screenshot below
2. Once decided the right preview size (point above), can we then fit the workflow into that size, in the preview? Similar as we do with the main canvas once opening a workflow
3. The preview window overlaps the buttons bar on bottom (zoom, fit, etc), and it should not, just because features from icons should be also available meanwhile preview is opened
4. The preview window gets closed just on mouse exit the area. I think the expected behavior, at least what other tools also do, is to open the preview once clicking on the icon, and it will REMAIN OPEN until the user clicks again on the icon. This way it allows to interact with the workflow meanwhile having the preview opened, so users can quickly navigate using the preview as well
5. Issue -> The preview area (draggable) is not properly located as the main canvas is, see the following screenshot, where the preview is on an "empty" area on east side, but the main canvas show that there exists shapes there

![Screenshot from 2022-10-10 22-39-03](https://user-images.githubusercontent.com/4602417/194949850-1d2761ee-33f3-4fad-8b77-0d3f2d612e94.png)

Thanks!

2022-10-19 21:05 UTC, romartin commented
@Josephblt any updates on this?

2022-10-28 12:01 UTC, Josephblt commented
Hello @romartin, @handreyrc. Here is the PR for the preview.

2022-11-08 21:09 UTC, romartin commented
hey @Josephblt , is the PR ready for review again? Please let us know once ready, so we can start it. Thanks!

2022-11-21 15:09 UTC, romartin commented
@Josephblt @domhanak ready for review again!

2022-11-28 14:41 UTC, romartin approved these changes
Hey @Josephblt 

Thanks for the updates. All issues I reported previously are being fixed, great job, it works nice!

2022-11-28 14:42 UTC, romartin commented
Please @domhanak 

Missing QE reivew here. Thanks!

2022-11-30 08:01 UTC, domhanak commented
@Josephblt @romartin Found an issue.

Steps:
1. Open diagram and zoom in to enable the preview window. Open it.
2. Rename a state so that diagram gets broken.
3. Observe the preview window going grey, while main canvas still is not grey.
4. Repair the damage. Observe that the window is still grey.

Expected behavior: (imho) it should reset the preview when diagram gets fixed.

Workaround: Zoom out and zoom in to reopen the preview window.

Let me know how do you want to handle this problem.

2022-11-30 20:26 UTC, romartin commented
thanks @domhanak . @Josephblt can you please tak ea look?

2022-12-06 12:03 UTC, Josephblt commented
Hello @domhanak, @romartin. I updated the PR and .vsix. Ready for another round of tests. Thanks.

2022-12-06 12:04 UTC, domhanak commented
@Josephblt Thanks! Will take a look asap.

2022-12-08 10:38 UTC, domhanak approved these changes
Thanks! Works well.

2022-12-08 11:32 UTC, romartin approved these changes

2022-12-08 11:32 UTC, merged