Json marshaller
apache/incubator-kie-tools pull request #1207
Opened 2022-08-29 06:54 UTC by treblereel

https://issues.redhat.com/browse/KOGITO-7717

2022-08-29 17:58 UTC, tiagobento commented
@romartin As this only impacts `serverless-workflow-diagram-editor`, I'm deferring my review to @romartin .

2022-08-29 17:58 UTC, tiagobento approved these changes

2022-08-30 15:49 UTC, domhanak requested changes
@treblereel there seems to be an issue with transitions not being drawn:
![Screenshot from 2022-08-30 17-47-00](https://user-images.githubusercontent.com/5937251/187482348-a28e6033-6ab4-4a1f-8dd4-8578b11b50d3.png)

The editor reports that there are invalid targets for transtions:
![Screenshot from 2022-08-30 17-48-37](https://user-images.githubusercontent.com/5937251/187482513-702c19a0-2132-418f-ad4d-b041777f2d0e.png)


Did not review the code, will do once @romartin or @hasys chime on that.

2022-08-31 21:43 UTC, treblereel commented
@domhanak thanks for your report, i expect here ll be more issues, simple because it's a huge update. Right now i am working on tests, so i expect this case (and some other) ll be fixed soon.

2022-09-29 11:52 UTC, mbiarnes commented
Jenkins run kie-tools-stunner-editors tests

2022-10-17 15:18 UTC, romartin reviewed
Hey @treblereel 

Thanks for this stuff, looks great!

I have just added a few minor review comments. Also please review that all domain beans should be JsTypes, as we discussed let's preserve them as exported types for third party usage. So please also do not drop the jstype annotations and consider adding the missing ones.

A part from this, once fixed, I think we should be ready to go!

Thanks!

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionDataFilters.java
> +public class ActionDataFilters {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionEventRef.java
> +//TODO is it the same as EventRef
TODO?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionEventRef.java
> +public class ActionEventRef {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ContinueAs.java
> +public class ContinueAs {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Correlation.java
> +public class Correlation {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Data.java
> +//TODO maybe is should converted to JsType=native with custom ser/deser
TODO?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Data.java
> +public class Data {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Error.java
> +public class Error {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Function.java
> +public class Function {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/FunctionRef.java
> +public class FunctionRef {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/custom/SubflowExecutionTypeJsonbTypeDeserializer.java
> +    private static final StringJsonDeserializer stringJsonDeserializer = new StringJsonDeserializer();
I have seen that mostly every deserializer has its own instance of, for instance, StringJsonDeserializer. Does it makes sense to have a single instead for this ,and other serializers, reused across all custom deserializer classes?
I am just thinking on the memory footprint, and trying to keep it minimal.

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/EventDataFilter.java
> +public class EventDataFilter {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ParallelStateBranch.java
> +public class ParallelStateBranch {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ProducedEvent.java
> +public class ProducedEvent {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Schedule.java
> +public class Schedule {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Retry.java
> +public class Retry {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/Sleep.java
> +public class Sleep {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/StartDefinition.java
> +public class StartDefinition {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/StateDataFilter.java
> +public class StateDataFilter {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/StateEnd.java
> +public class StateEnd {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/StateTransition.java
> +public class StateTransition {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/SubFlowRef.java
> +public class SubFlowRef {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/WorkflowExecTimeout.java
> +public class WorkflowExecTimeout {
can this be a `@JsType`?

2022-10-17 15:18 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/WorkflowTimeouts.java
> +public class WorkflowTimeouts {
can this be a `@JsType`?

2022-10-18 02:24 UTC, treblereel commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionEventRef.java
> +//TODO is it the same as EventRef
@romartin yeah, i am not really sure, maybe this type can be reused as EventRef or vice-versa

2022-10-19 19:30 UTC, romartin commented
Hey @treblereel have you already fixed the issues mentioned by @domhanak above? Please guys let's move this forward

2022-10-19 19:35 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionEventRef.java
> +//TODO is it the same as EventRef
I think both cannot be reused... anyway can you please verify against the `[spec](https://github.com/serverlessworkflow/specification/blob/main/specification.md)` and give your opinion? :)

2022-10-19 19:42 UTC, romartin commented
@treblereel Thanks for this work, again! After another review iteration, the status for this PR is

- waiting for the required changes in code, also would be nice if you can figure out those TODOs about reusing classes, just by comparing existing model classes, and your new (added) ones, against the spec and the fields for each type. 
- please let @domhanak know if the issues he reported are fixed
- would be nice (and hopefully easy) rebasing from main upstream, please
- ensure the generated VSIX are properly generated with latest changes

Once those above are completed, please let us know so we'll proceed with another review iteration!  
Thanks!!! :+1:

2022-10-20 01:11 UTC, treblereel commented
> Hey @treblereel have you already fixed the issues mentioned by @domhanak above? Please guys let's move this forward

yeap, it's fixed long ago

2022-10-20 01:14 UTC, treblereel commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ActionEventRef.java
> +//TODO is it the same as EventRef
> I think both cannot be reused... anyway can you please verify against the [spec](https://github.com/serverlessworkflow/specification/blob/main/specification.md)` and give your opinion? :)

yeap, from my opinion those two definitions aren't interchangeable, i left this comment to think about it again later one day.

2022-10-20 08:14 UTC, domhanak commented
Great, is this considered approved from you @romartin ? I ll retest when I see approval.

2022-10-20 18:03 UTC, treblereel commented
@romartin by the way, do you remember the bug i reported you ? Is it fixed ?

2022-10-20 18:04 UTC, treblereel commented
> Great, is this considered approved from you @romartin ? I ll retest when I see approval.

let me add @JsTypes first :)

2022-10-24 13:47 UTC, romartin commented
Yep  @treblereel , just waiting for your fixes on the jstypes removed, also maybe adding some, see review comments above please.

Also, about the issue you mentioned, it was about exporting the example named "states", I can't find it yet reported. Can you please report it and send me the link? We did some fixes on marshallers a few time ago, so if this is not yet rebased, maybe the issue is gone. Can you please re-try and if still persists, report and send me the link plz?

2022-10-24 23:06 UTC, treblereel commented
@romartin yeap, right after i fix the exception i got after rebase with upstream

2022-10-26 15:14 UTC, treblereel commented
@romartin 'States Example' is broken, please let me know, once it ll be fixed and i ll rebase the branch.
PS: i remember, you created issue, right ?

2022-10-31 05:24 UTC, treblereel commented
the issue: https://issues.redhat.com/browse/KOGITO-8197

2022-11-03 14:29 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/EventDataFilter.java
> +@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
Hey @treblereel 
Quick Q - why are you considering it a native type (`isNative=true`)? Also setting the `name` field as `Object, and the namespace to `GLOBAL`? Is this some good practice?

In general as you can see on other classes we're just not considering (yet) those classes as native types. So we don't use any annotation field, just the `@JsType` with no parameters.

2022-11-03 20:21 UTC, treblereel commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/EventDataFilter.java
> +@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
@romartin there is no need for it right now, but we should remember, in j2cl, because of closure compiler just a @JsType(isNative = true) wouldn't work. There are few options howto fix it, so no worries for now, but we should remember about it. Let me update PR for now, but i think, i have to write some article about this case.

2022-11-07 22:22 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/EventDataFilter.java
> +@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
ok thanks!

2022-11-07 22:24 UTC, romartin approved these changes
Hey @treblereel 

Thanks for the latest updates as well.

Everything looks good to me at this point, great work!! Approving :+1:

2022-11-07 22:24 UTC, romartin commented
Hey @domhanak ,

Please missing QE review here. Thanks!

2022-11-14 07:25 UTC, domhanak approved these changes

2022-11-14 16:03 UTC, romartin commented
@hasys can you please check with @treblereel that since merging https://github.com/kiegroup/kie-tools/pull/1275 we need to properly serialize the state's `metadata` field again?

2022-11-14 16:11 UTC, romartin commented
Hey @treblereel 

This is finally approved! Thanks for this work!

Anyway, **BEFORE MERGING, please a couple of actions**:

- rebase from main 
- Please check with @hasys the serialization for the state's metadata field

Once this is done, I'll proceed with merge. 

Thanks!

2022-11-14 16:17 UTC, hasys commented
Hi @treblereel, I added one change to the model which is `Metadata.java`. It is added to the super class `State.java` as a property:
```java
    public Metadata metadata;
    public Metadata getMetadata() {
        return metadata;
    }

    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }
```

And `Parser.java` has this change:
```java
            Metadata metadata = Js.uncheckedCast(Js.asPropertyMap(jso).get("metadata"));
            if (null != metadata) {
                state.metadata = metadata;
            }
```

2022-11-15 21:58 UTC, treblereel commented
@romartin ^^

2022-11-16 11:22 UTC, merged