kie-issues#34 Fix context entries rows generated names on paste
apache/incubator-kie-tools pull request #1341
Opened 2022-11-23 10:56 UTC by jomarko

For more details see: 
- https://github.com/kiegroup/kie-issues/issues/34
- https://issues.redhat.com/browse/KOGITO-5920

This PR fixes just the basic reported scenario. The copy and paste into Context Expression will work correctly in a single scenario, and it is when ContextExpression contains single entry, defined as LiteralExpression. See the picture bellow

![Screenshot from 2022-11-23 11-51-00](https://user-images.githubusercontent.com/8044780/203528597-fa9801e5-a4bb-40e8-8445-88925b88bf62.png)

Other situations, when user tries to paste into ContextExpression with multiple context entries don't work even on the main branch.

To try the fix:
- Open some spreadhsheet tool like google spreadsheets
- Copy multiple cells of one column (Press 'Ctrl+C')
- Select the LiteralExpression of the ContextEntry-1
- paste value (Press 'Ctrl+V')

The existing issues, that are not addressed as part of this PR are:
- https://issues.redhat.com/browse/KOGITO-6436
- https://issues.redhat.com/browse/KOGITO-6437
- https://issues.redhat.com/browse/KOGITO-6438

2022-11-23 11:57 UTC, jomarko commented
Reported by @fantonangeli , we have duplicated name in this scenario:
![Peek 2022-11-23 12-28](https://user-images.githubusercontent.com/8044780/203541218-8a7e8d4b-65ab-4fff-b25a-080b00a32c16.gif)

2022-11-24 09:12 UTC, jomarko commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos: EntryInfo[] = [];
I see this line as the most problematic. When debugging, it is clear between two `onRowAdding` invocations, `existingEntryInfos` is never cleared, its content is just getting new and new elements.

While, everytime `onRowsUpdate` is invoked, `existingEntryInfos` is always empty.

![Screenshot from 2022-11-24 09-36-51](https://user-images.githubusercontent.com/8044780/203743704-f3bb3bb9-c3eb-46aa-9ea2-27de49146717.png)
![Screenshot from 2022-11-24 09-36-20](https://user-images.githubusercontent.com/8044780/203743712-444dca41-3357-451e-a153-08c227dd8c32.png)

2022-11-25 08:55 UTC, fantonangeli approved these changes

2022-11-25 09:01 UTC, yesamer commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
@jomarko Can you please check this warning 

`React Hook useMemo has an unnecessary dependency: 'rows'. Either exclude it or remove the dependency array`

2022-11-25 09:11 UTC, fantonangeli commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
Without that dependency, `existingEntryInfos` would not be re-initialized on `rows` changes.
I saw there we have also other components giving the same warning. 
Would you know a way to avoid this warning otherwise we can use the `// eslint-disable-next-line react-hooks/exhaustive-deps` comment?

2022-11-25 10:47 UTC, tiagobento commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
When an unnecessary dependency is needed in a Hook, that's a very strong indicator that the problem is bigger. Ignoring the warning is ok, but does not fix the root cause. We need to dog deeper to find where's the wrong abstraction so that we don't need a Hook with an extra dependency.

2022-11-25 16:16 UTC, fantonangeli commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
True, I used dependencies in the wrong way. 
Re-writing better the useMemo and dependencies the resulting code is much better and we don't need to receive `allRows` in `onRowAdding`.
Now I opened a PR on @jomarko branch and we both test it

2022-11-28 07:20 UTC, jomarko commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
lint warning are fixed now, thank you @fantonangeli 

@yesamer @tiagobento feel free to re-review

2022-11-28 08:35 UTC, yesamer commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +  const existingEntryInfos = useMemo<EntryInfo[]>(() => [], [rows]);
@jomarko @fantonangeli Much butter, thank you both. Reviewing it.

2022-11-28 09:39 UTC, yesamer approved these changes
LGTM

2022-11-29 11:58 UTC, tiagobento requested changes
@jomarko Please take a look at my comment below. Thanks!

2022-11-29 11:58 UTC, tiagobento commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +    existingEntryInfos.push(row.entryInfo);
Mutanting an array that is part of a `useMemo` is not something we should be doing. If this was necessary, it probably means that there's a bigger problem somewhere else. Most of the time we need to rethink out strategy to adapt to React's declarative model.

2022-11-29 16:58 UTC, fantonangeli commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +    existingEntryInfos.push(row.entryInfo);
The problem here is that `onRowAdding()` is called for each row before it is added to the `rows` variable.
The callstack is: `pasteOnTable()`--for each row--> `Table.onRowAddingCallback()`---> `onRowAdding()`.

As a solution I wanted to use a temporary array to store the rows info before they are added to `rows`, reinitializing it when `rows` is changed.
Using a normal constant for the array, without `useMemo`, the linter gives a warning.

Do we have a better solution, avoiding a refactoring that can impact all the components with the Copy&Paste functionality?

2022-11-29 17:19 UTC, tiagobento commented on packages/boxed-expression-component/src/components/ContextExpression/ContextExpression.tsx
> +    existingEntryInfos.push(row.entryInfo);
I'm not familiar with the boxed expression component (yet), so I won't be able to advise. What I can say is that there's a lot of things in the whole component architecture that does not conform with how React wants us to use its features. Scenarios like this one you're describing are a symptom of a much larger structural problem with it. I'm starting to look at the component as a whole trying to understand how we're going to change it to be easier to evolve and maintain, but right now, I'm not able to help much more than just pointing out these kind of things...

2022-12-09 11:22 UTC, jomarko commented
Waiting for @tiagobento's refactoring of the component

2022-12-09 11:22 UTC, closed without merging