kie-issues#37: Exclude 'WEB-INF' folder and html files of gwt-editors from 'dist' folder
apache/incubator-kie-tools pull request #1347
Opened 2022-11-25 07:03 UTC by jomarko

This PR closes:
- https://github.com/kiegroup/kie-issues/issues/37
- https://issues.redhat.com/browse/KOGITO-1430

2022-11-29 10:18 UTC, jomarko commented
All CI checks passed @yesamer @tiagobento

2022-11-29 11:55 UTC, tiagobento approved these changes

2022-11-29 12:00 UTC, yesamer approved these changes

2022-11-29 12:19 UTC, caponetto requested changes

2022-11-29 12:19 UTC, caponetto commented on packages/chrome-extension-serverless-workflow-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
`chrome-extension-pack-kogito-kie-editors` package also needs this change, doesn't it?

2022-11-29 12:19 UTC, caponetto commented on packages/dashbuilder-viewer-deployment-webapp/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
Please revert this change. Dashbuilder uses some `index.html` files to load external components.

2022-11-29 12:19 UTC, caponetto commented on packages/vscode-extension-dashbuilder-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
Looks like the VS Code extension for Dashbuilder is not working properly. Can you please check?

2022-11-30 06:36 UTC, jomarko commented on packages/dashbuilder-viewer-deployment-webapp/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
done as c1f46444475

2022-11-30 06:40 UTC, jomarko commented on packages/chrome-extension-serverless-workflow-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
done as 1620df8355b

2022-11-30 07:03 UTC, jomarko commented on packages/vscode-extension-dashbuilder-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
@caponetto sure. this extension is new for me. Would you mind to help me in understanding how can I built it locally? It is ntot described in https://github.com/kiegroup/kie-tools/blob/main/packages/vscode-extension-dashbuilder-editor/README.md

Or is the only way I need to try it to download CI build artifacts?

2022-11-30 09:43 UTC, caponetto commented on packages/vscode-extension-dashbuilder-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
To build and run this extension locally you can follow the same steps as the other VS Code extensions.
Then, open any `*.dash.yaml` file (you can get one example at https://start.kubesmarts.org).

2022-11-30 09:53 UTC, jomarko commented on packages/vscode-extension-dashbuilder-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
I downloaded build form CI, installed extension and opened example https://raw.githubusercontent.com/kiegroup/kie-tools/main/examples/dashbuilder/kitchensink/Kitchensink.dash.yml

This is what I got

what should I focus on there please?
![Screenshot from 2022-11-30 10-52-08](https://user-images.githubusercontent.com/8044780/204764564-2b7ebd51-a4eb-4446-8b00-3fbfc9905689.png)

2022-11-30 09:56 UTC, caponetto commented on packages/vscode-extension-dashbuilder-editor/webpack.config.js
> +            globOptions: { ignore: ["**/WEB-INF/**/*", "**/*.html"] },
Do the "External Components" tab and its inner tabs load ok?
I installed the extension from CI yesterday and I was seeing a blank screen. Let me try again.

2022-11-30 12:38 UTC, caponetto approved these changes

2022-12-01 07:56 UTC, jomarko commented
@tiagobento may I ask you for a merge?

2022-12-02 10:09 UTC, merged