KOGITO-8071: Flaky test - serverless-workflow-editor-extension-autocompletion.test.ts
apache/incubator-kie-tools pull request #1359
Opened 2022-12-07 12:06 UTC by zdrapela

**Jira:** https://issues.redhat.com/browse/KOGITO-8071

The test is now stable when running locally (30+ runs, no fail) and [on the CI](https://github.com/zdrapela/kie-tools/actions/runs/3637751535) (7+ runs, no fail).

The requirement to run smoke tests before other tests was added.

2022-12-07 13:42 UTC, tomasdavidorg approved these changes

2022-12-07 14:50 UTC, paulovmr requested changes
Hi @zdrapela , just one question regarding the added requires.

2022-12-07 14:50 UTC, paulovmr commented on packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-autocompletion.test.ts
> +require("./serverless-workflow-editor-extension-smoke.test");
Why are these `require`s needed?

2022-12-08 09:51 UTC, zdrapela commented on packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-autocompletion.test.ts
> +require("./serverless-workflow-editor-extension-smoke.test");
It is not relevant to fixing this test, but @domhanak advised adding this to these tests. To my understanding, this should ensure, that smoke test is run before running any other tests. We use the same approach in [`vscode-extension-pack-kogito-kie-editors`](https://github.com/kiegroup/kie-tools/tree/main/packages/vscode-extension-pack-kogito-kie-editors/it-tests).

2022-12-13 09:27 UTC, zdrapela commented on packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-autocompletion.test.ts
> +require("./serverless-workflow-editor-extension-smoke.test");
Hi @paulovmr, is the explanation above enough, or should I remove the `require`s for now and we can discuss their usage later, possibly in separate PR? 🙂

2022-12-15 15:32 UTC, paulovmr approved these changes

2022-12-15 15:32 UTC, merged