kie-issues#13: Make it possible to configure a commit message validation endpoint on KIE Sandbox
apache/incubator-kie-tools pull request #1436
Opened 2023-01-31 21:46 UTC by thiagoelg

# In this PR

- Added commit message validation to the commit message modal (via a request to an external service)
- Added example commit message validation service in the examples directory

# How
https://user-images.githubusercontent.com/10515135/215890679-5a9d68d1-3ef1-4a57-8e13-dac9110570ff.mov

2023-02-01 12:47 UTC, tiagobento requested changes
@thiagoelg Great job!

I think we're missing two important things here:
1. Standardization on the name of this feature. Right now, there's "Commit message validator", "Commit messages validation service", "Commit message validation", and "Commit message validation service". Can you please rename everything to `Commit message validation service`? Including the examples package you provided.

2. Same thing we did for the "Require custom commit messages" feature, this needs to be configurable on a per-deployment basis, so we need to enable this env var on `kie-sandbox-image` as well. We need to provide instructions to do so, and possibly an example that users the new example package too!

Some comments inline too.

2023-02-01 12:47 UTC, tiagobento commented on packages/online-editor/src/workspace/components/WorkspaceCommitModal.tsx
> +        return { result: false, reason: i18n.commitModal.inputHelper };
Maybe `inputHelper` is not a good name for a "non-empty? validation message?

2023-02-01 12:47 UTC, tiagobento commented on packages/online-editor/src/workspace/commitMessageValidation/CommitMessageValidation.ts
> +export class CommitMessageValidationFetch {
Maybe rename to `CommitMessageValidationServiceClient`?

2023-02-01 12:48 UTC, tiagobento commented
Btw thanks for the GIF! It's always nice to see changes in action! :)

2023-02-01 22:55 UTC, tiagobento requested changes
Some more comments inline... 

Also, we're missing a strong documentation for this new service. People should be capable of configuring their own `commit-message-validation-service`s by looking at what KIE Sandbox expects from it (e.g. HTTP method, Request body format, HTTP errors etc etc.

 I think this information should be on `kie-sandbox-image` README. WDYT?

2023-02-01 22:55 UTC, tiagobento commented on examples/commit-message-validation-service/README.md
> +[POST] Validates a commit message againts the enabled validators.
```suggestion
[POST] Validates a commit message against the enabled validators.
```

2023-02-01 22:55 UTC, tiagobento commented on examples/commit-message-validation-service/README.md
> +- `COMMIT_MESSAGE_VALIDATION_SERVICE__port <PORT_NUMBER>`
```suggestion
- `EXAMPLE_COMMIT_MESSAGE_VALIDATION_SERVICE__port <PORT_NUMBER>`
```

2023-02-01 22:55 UTC, tiagobento commented on examples/commit-message-validation-service/README.md
> +- `COMMIT_MESSAGE_VALIDATION_SERVICE__validators <validatorName1>:<validatorParameters1>;<validatorName2>:<validatorParameters2>...`
```suggestion
- `EXAMPLE_COMMIT_MESSAGE_VALIDATION_SERVICE__validators <validatorName1>:<validatorParameters1>;<validatorName2>:<validatorParameters2>...`
```

2023-02-01 22:55 UTC, tiagobento commented on examples/commit-message-validation-service/env/index.js
> +      description: "Enabled validators",
I think the description should provide some hints about the format of this string. It's not trivial to know how to configure it.

2023-02-01 22:55 UTC, tiagobento commented on examples/commit-message-validation-service/env/index.js
> +      description: "Enabled validators",
Is this a known pattern from some library? Or is this something specific to this example webapp?

2023-02-01 22:55 UTC, tiagobento commented on packages/online-editor/src/workspace/commitMessageValidationService/CommitMessageValidationService.ts
> +export class CommitMessageValidationService {
Oh, okay. That's my bad. This one should be `CommitMessageValidationService`, the other one is indeed `CommitMessageValidationResource`.

2023-02-01 22:55 UTC, tiagobento commented on packages/online-editor/src/workspace/commitMessageValidationService/CommitMessageValidationServiceClient.ts
> +}
Hmmmm... IDK, I think this class might be too much? Maybe we could do everything on `CommitMessageValidationService`?

2023-02-01 22:55 UTC, tiagobento commented on packages/online-editor/src/workspace/components/WorkspaceCommitModal.tsx
> +  }
Hmmm... instead of having us split the commit messages by line breaks, maybe we could simply return an array from the Commit Message Validation Service?

2023-02-01 23:32 UTC, tiagobento commented on packages/git-cors-proxy-image/Containerfile
> +CMD [ "/kie-sandbox/git-cors-proxy/bin.js", "start", "-p", "3000" ]
Leftover? :D

2023-02-02 19:18 UTC, thiagoelg commented on packages/git-cors-proxy-image/Containerfile
> +CMD [ "/kie-sandbox/git-cors-proxy/bin.js", "start", "-p", "3000" ]
🙈

2023-02-02 19:18 UTC, thiagoelg commented on packages/online-editor/src/workspace/components/WorkspaceCommitModal.tsx
> +  }
Good idea!

2023-02-02 19:20 UTC, thiagoelg commented on examples/commit-message-validation-service/env/index.js
> +      description: "Enabled validators",
I've seen similar patterns around, but nothing specific. This is just something I came up with.

Improved the description a little bit and added examples to the README.

2023-02-03 12:10 UTC, tiagobento approved these changes

2023-02-06 15:29 UTC, merged