https://github.com/kiegroup/kie-issues/issues/39 Fix SDM on Linux, Windows and Mac OS
apache/incubator-kie-tools pull request #1438
Opened 2023-02-01 18:55 UTC by inodeman

Hi @yesamer @gitgabrio @Josephblt can you review this PR? To test the changes make sure you build kie-wb-common-stunner first as I have had issues with Hot Reload before on these changes. I have tested the changes on Linux, Windows (Thanks Wagner) and Mac OS and it works, tested it with different diagrams and also tested the issue on DMN which does not seem to have any errors. Thanks and let me know

2023-02-01 20:25 UTC, tiagobento requested changes
@inodeman Can you please put the issue URL on the comments as well? It can be important in the future.

2023-02-01 22:57 UTC, tiagobento commented
@inodeman It would be good to know why this happens.. is this a GWT compiler error? Runtime error? Writing the solution on the issue or on this PR's comment can be very important for future reference.

2023-02-02 00:44 UTC, inodeman commented
> @inodeman It would be good to know why this happens.. is this a GWT compiler error? Runtime error? Writing the solution on the issue or on this PR's comment can be very important for future reference.

Hi @tiagobento added the comment of my findings about the issue

2023-02-02 08:45 UTC, gitgabrio requested changes
Hi @inodeman Thanks for the PR! I would prefer a small modification on one of your changes

2023-02-02 08:45 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java
>          return Optional.ofNullable(encoded)
Hi @inodeman Thanks for PR!
Would not be possible to simlpify this method and remove altogether that `Optional.ofNullable` usage ?
AFAIU, this method returns a `new AssociationList()` when

`encoded == null || encoded.isEmpty`
 Only when  `encoded.notEmpty` the "mapping" is actually invoked (side note - the filter still contains the `nonEmpty` predicate, even if checked in the newly added "if")

2023-02-02 08:45 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java
> +                // The change below is to fix SDM issue for Linux/Windows
Hi @inodeman 
I just checked `FlowElement` hierarchi and, actually, this `FlowElementImpl` is one of the direct children. 
Without this modification, how would it be possible for this method to work at all, when receiving a `SeqeuenceFlowImpl` ? It is not even declared in the following `ignore`. I'm just trying to understand and never saw this `Match` class before

2023-02-02 09:57 UTC, yesamer reviewed
Hi @inodeman! I tested your changes, it seems the issue is still present in my local (macOS)

https://user-images.githubusercontent.com/16005046/216292679-298ed26a-d019-47ae-90f4-6795887c1472.mov

Is probably that issue related to another marshaller area? I can give you the BPMN files I'm using, just ping me :)

2023-02-09 16:01 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java
>          return Optional.ofNullable(encoded)
Hi @gitgabrio I modified it

2023-02-09 16:02 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java
> +                // The change below is to fix SDM issue for Linux/Windows
Hi @gitgabrio removed changes from that class and modified ProcessConverterDelegate as per the code you shared

2023-02-09 17:11 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java
> +                // The change below is to fix SDM issue for Linux/Windows
Thanks @inodeman ! I hope everything is fixed with this PR 👍

2023-02-09 17:33 UTC, inodeman commented
Hi @gitgabrio @yesamer @Josephblt made code changes, ready for review

2023-02-09 19:22 UTC, Josephblt approved these changes

2023-02-10 08:29 UTC, yesamer approved these changes
@inodeman It finally works! Just a couple of minor points:

2023-02-10 08:29 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +        final List<Result<BpmnNode>> results = new ArrayList<Result<BpmnNode>>();
@inodeman You can use the `<>` Diamond operator here

2023-02-10 08:29 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +        final Map<String, BpmnNode> resultMap = new HashMap<String, BpmnNode>();
@inodeman You can use the `<>` Diamond operator here

2023-02-10 08:29 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@inodeman I would use a LOGGER here, and not the `GWT.log`.
`    private static Logger LOGGER = Logger.getLogger(ProcessConverterDelegate.class.getName());
`

2023-02-10 12:46 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@yesamer Why "Logger" instead of "GWT.log" ? Out of curiosity....

2023-02-10 12:57 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@gitgabrio `GWT.log()` works in dev mode only --> https://www.gwtproject.org/javadoc/latest/com/google/gwt/core/client/GWT.html . I would use the Logger at least in the catch body.

2023-02-10 13:04 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@yesamer 🤔 TBH I'm not so sure. https://www.gwtproject.org/doc/latest/DevGuideLogging.html

`Most of the default Handlers are very straightforward

    SystemLogHandler - Logs to stdout. These messages can only be seen in Development Mode — look for them in the DevMode window
    DevelopmentModeLogHandler - Logs by calling method GWT.log. These messages can only be seen in Development mode — look for them in the DevMode window
    ConsoleLogHandler - Logs to the javascript console, which is used by Firebug Lite (for IE), Safari and Chrome(?)
    FirebugLogHandler - Logs to Firebug
    PopupLogHandler - Logs to the popup which appears in the upper left hand corner
    SimpleRemoteLogHandler - Discussed below, in the Remote Logging section` 

`Client vs. Server-side Logging

Although GWT emulates java.util.logging, it is important to understand the difference between server-side and client-side logging. Client-side logging logs to handlers on the client side, while server-side logging logs to handlers on the server side.

To make this clear, the client-side GWT code has a Root Logger (and logger hierarchy) that is separate from the server-side code; all of the handlers discussed above are only applicable to client-side code. If code shared by the client and server makes logging calls, then which Root Logger (and logger hierarchy) it logs to will depend on whether it is being executed on the client or server side. You should not add or manipulate Handlers in shared code, since this will not work as expected.

In [ServerLoggingArea.java](https://gwt.googlesource.com/gwt/+/master/samples/logexample/src/com/google/gwt/sample/logexample/client/ServerLoggingArea.java), you can experiment with these concepts. The buttons in that section will trigger logging calls on the server, as well as logging calls in [SharedClass.java](https://gwt.googlesource.com/gwt/+/master/samples/logexample/src/com/google/gwt/sample/logexample/shared/SharedClass.java) from both the client and server side. Note the slight differences in formatting between client-side and server-side logging, as well as the different handlers each is logged to (in the tutorial, server-side logging will simply log to stderr, while client-side logging will log to all of the Handlers discussed above).`


@inodeman Would you have the chance to give it a try ? My doubt is that "Logger" does not print on browser console (i.e. the one see inside the "Web development tools" of the browser): this is pretty important, IMO, because otherwise it is not possible to see the exception when it happen

2023-02-10 13:16 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@gitgabrio 
<img width="1163" alt="Screenshot 2023-02-10 at 14 15 44" src="https://user-images.githubusercontent.com/16005046/218101226-fd5a4c54-4dad-47f5-b470-bbdc5c236aca.png">

2023-02-10 15:34 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@yesamer Ok, but my question is: does `Logger` print on browser console ? If not, how to print in browser console ?

2023-02-10 16:51 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
Hi @yesamer @gitgabrio now that i think of it, one time Roger from stunner team told me that instead of GWT.log we should use DomGlobal.console.log which logs to the console in both dev mode and production, he mentioned that since we are moving away from GWT we should use that, what do you think?

2023-02-10 17:03 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +        final List<Result<BpmnNode>> results = new ArrayList<Result<BpmnNode>>();
Hi @yesamer will do

2023-02-10 17:03 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +        final Map<String, BpmnNode> resultMap = new HashMap<String, BpmnNode>();
Hi @yesamer will do

2023-02-10 17:21 UTC, yesamer commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
@gitgabrio 
LOGGER works, it's currently used in several places in the code base. To give you an example, this is a LOGGER usage used to log exceptions during DMN file unmarshalling phase.
<img width="425" alt="Screenshot 2023-02-10 at 18 12 57" src="https://user-images.githubusercontent.com/16005046/218154195-749b9dd7-bfb5-488e-9883-6477819263b1.png">
As a result of passing an invalid DMN file, the console shows the following:
<img width="1534" alt="Screenshot 2023-02-10 at 18 18 31" src="https://user-images.githubusercontent.com/16005046/218155180-c6a914cb-5de6-4848-9d95-18dbcb89aed5.png">

@inodeman Good point, `DomGlobal.console.log` is a reasonable alternative. My point is just don't use `GWT.log` for the above reason, so it's fine for me to use `DomGlobal.console.log`

2023-02-10 17:23 UTC, inodeman commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
Very well @yesamer , is it ok with you @gitgabrio ?

2023-02-11 07:32 UTC, gitgabrio commented
@inodeman the log has to be printed always in the browser console (i.e. not
on some server file) to be readable when some issue happen: did you verify
that?

Il Ven 10 Feb 2023, 18:23 Jaime Enriquez ***@***.***> ha
scritto:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> <https://github.com/kiegroup/kie-tools/pull/1438#discussion_r1103030232>:
>
> > -
> -        return ResultComposer.composeResults(resultMap, results);
> +        final List<Result<BpmnNode>> results = new ArrayList<Result<BpmnNode>>();
> +        final Map<String, BpmnNode> resultMap = new HashMap<String, BpmnNode>();
> +        for (FlowElement element : flowElements) {
> +            try {
> +                GWT.log("Converting  " + element);
> +                Result<BpmnNode> result = converterFactory.flowElementConverter().convertNode(element);
> +                results.add(result);
> +                GWT.log("Mapping  " + result);
> +                if (result.value() != null) {
> +                    BpmnNode n = result.value();
> +                    resultMap.put(n.value().getUUID(), n);
> +                }
> +            } catch (Throwable t) {
> +                GWT.log("Failed to convert/map " + element, t);
>
> Very well @yesamer <https://github.com/yesamer> , is it ok with you
> @gitgabrio <https://github.com/gitgabrio> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kiegroup/kie-tools/pull/1438#discussion_r1103030232>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAF25CRWD4KTGL3F2GOLJF3WWZ2SRANCNFSM6AAAAAAUOC55CA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-11 17:13 UTC, inodeman commented
Hi @gitgabrio yes, DomGlobal.console.log does what console.log (JavaScript) does, and I verified it as well, let me know

2023-02-11 21:49 UTC, gitgabrio commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java
> +                GWT.log("Failed to convert/map " + element, t);
Great @inodeman Fine for me! Thanks for this!

2023-02-13 11:23 UTC, tiagobento commented
Is this good to go in? @yesamer @inodeman @Josephblt @gitgabrio

2023-02-13 11:24 UTC, yesamer commented
> Is this good to go in? @yesamer @inodeman @Josephblt @gitgabrio

We just need to remove `GWT.log()`s and it's fine.

2023-02-13 15:34 UTC, inodeman commented
Hi @gitgabrio @yesamer @Josephblt  changes are in to include  <> as well as removing GWT.log.

2023-02-13 16:10 UTC, gitgabrio approved these changes

2023-02-13 17:08 UTC, Josephblt approved these changes

2023-02-13 17:51 UTC, merged