Add SWF external component
apache/incubator-kie-tools pull request #1448
Opened 2023-02-07 21:13 UTC by manaswinidas

2023-02-09 03:19 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/dev-webapp/index.tsx
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
Please fix header year

2023-02-09 03:20 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/dev-webapp/webpack.config.js
> + * Copyright 2019 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino requested changes
Hello @manaswinidas 

Thanks for your PR. I am adding a few comments.

Please also notice that there are errors on build.

To reproduce these errors locally build with `build:prod`

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/dev-webapp/webpack.config.js
> +          { from: path.resolve(__dirname, "sample.svg"), to: "." },
I think `sample.svg` could be removed

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/env/index.js
> + * Copyright 2022 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/jest.config.js
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/SwfEditorComponent.tsx
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/webpack.config.js
> + * Copyright 2019 Red Hat, Inc. and/or its affiliates.
fix header - year should be 2023

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/tests/jest.setup.ts
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/static/manifest.json
> +{
This file should be updated

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/static/index.html
> +  ~ Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/index.tsx
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/index-dev.tsx
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-09 03:25 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/SwfStandaloneEditor.tsx
> + * Copyright 2020 Red Hat, Inc. and/or its affiliates.
header

2023-02-16 00:26 UTC, jesuino requested changes
We are almost there! Just a few tweaks and comments

2023-02-16 00:26 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/dev-webapp/webpack.config.js
> + * Copyright 2019 Red Hat, Inc. and/or its affiliates.
Year still needs fix!

2023-02-16 00:26 UTC, jesuino commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxView.java
> +        button.disable();
any reason to change this line of code? It seems unrelated to the component

2023-02-16 00:26 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/SwfStandaloneEditor.tsx
> +      const editor = SwfEditor.open({
I would assign editor to the component state - it will be useful later

2023-02-16 00:26 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/SwfEditorComponent.tsx
> +  const initialiseWithContent = (params: Map<string, any>) => {
we may look for using useCallback later - it would cache the callback and help us to improve performance

https://beta.reactjs.org/reference/react/useCallback

2023-02-16 09:48 UTC, manaswinidas commented on packages/dashbuilder-component-swf-editor/src/SwfEditorComponent.tsx
> +  const initialiseWithContent = (params: Map<string, any>) => {
Cool

2023-02-16 09:49 UTC, manaswinidas commented on packages/dashbuilder-component-swf-editor/src/SwfStandaloneEditor.tsx
> +      const editor = SwfEditor.open({
Do you mean something like: `const [swfEditor, setSwfEditor] = useState<any>({ editor });`

2023-02-16 09:50 UTC, manaswinidas commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxView.java
> +        button.disable();
Oops, I think this came along with the rebase 😞

2023-02-16 21:57 UTC, jesuino requested changes
Just wanted to ask you to please reset the file AbstractActionsToolboxView.java to the main version - I am really concerned that it may impact stunner editors

THanks!

2023-02-16 21:57 UTC, jesuino commented on packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxView.java
> -        button.disable();
Could you please reset this file to main version?

2023-02-16 21:57 UTC, jesuino commented on packages/dashbuilder-component-swf-editor/src/SwfStandaloneEditor.tsx
> +  const initialEditor = (content: string) =>
I would call this callback as `initEditor`

2023-02-21 01:41 UTC, jesuino approved these changes
LGTM to me!

Great work @manaswinidas

2023-02-22 21:07 UTC, paulovmr approved these changes

2023-02-22 21:08 UTC, merged