KOGITO-8696:[SWF Editor] Add support to Camel routes in Service Catalog
apache/incubator-kie-tools pull request #1467
Opened 2023-02-17 05:05 UTC by Sara4994

2023-03-07 09:03 UTC, caponetto commented
@Sara4994 Can you please add a short gif/video to the PR description to show off this new feature?

2023-03-08 12:07 UTC, Sara4994 commented
https://user-images.githubusercontent.com/40579476/223709311-0bc0a36b-1d92-42c1-9f79-8cd58b23d617.mp4

2023-03-08 12:10 UTC, Sara4994 commented
@caponetto yep, here it is :)

https://user-images.githubusercontent.com/40579476/223709834-ec418c40-7f8f-4392-9cf9-0b86fa6b729c.mp4

2023-03-10 12:05 UTC, caponetto reviewed
Thanks for this PR, @Sara4994!
I've left some comments inline. Please check if they make sense. :)

Also, can you please create a JIRA to support this on Serverless Logic Web Tools as well?

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/languageService/VsCodeSwfLanguageService.ts
> +          getServices: async (textDocument: any) => {
```suggestion
          getServices: async (textDocument) => {
```
I believe you don't need this change.

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/languageService/VsCodeSwfLanguageService.ts
> +        getSpecsDirPosixPaths: async (textDocument: any) => {
```suggestion
        getSpecsDirPosixPaths: async (textDocument) => {
```

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/languageService/VsCodeSwfLanguageService.ts
> +        getRoutesDirPosixPaths: async (textDocument: any) => {
```suggestion
        getRoutesDirPosixPaths: async (textDocument) => {
```

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/languageService/VsCodeSwfLanguageService.ts
> +          swfServiceCatalogServiceId: any
```suggestion
          registryName,
          swfServiceCatalogServiceId
```
I believe you don't need to specify the types here. 
Also, you have to have a very good reason to use the `any` type.
In this case, I believe `registryName` and `swfServiceCatalogServiceId` are simply `string`.

2023-03-10 12:05 UTC, caponetto commented on packages/serverless-workflow-service-catalog/src/channel/parsers/impl/camelRoutes/CamelRoutesParser.ts
> +  canParse(content: any): boolean {
It is possible to avoid using `any` here? And use a more defined type instead.

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/serviceCatalog/SwfServiceCatalogSupportActions.ts
> +    vscode.window.showInformationMessage(`Wrote ${routesServiceFileAbsolutePosixPath}.`);
Can we have only one showInformationMessage for both?
Like `Wrote ${serviceFileAbsolutePosixPath} and ${routesServiceFileAbsolutePosixPath}`
Or would this message be too long?

2023-03-10 12:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/serviceCatalog/fs/FsWatchingServiceCatalogRelativeStore.ts
> +const EXTENSIONS_REGEX = new RegExp("^.*\\.(yaml|yml|json|xml)$");
Are we supporting `xml` already?

2023-03-10 12:05 UTC, caponetto commented on packages/serverless-workflow-service-catalog/src/channel/parsers/impl/camelRoutes/camelRoutes.ts
> +  const name = `camel:${routeFrom?.uri}` as string;
```suggestion
  const name = `camel:${routeFrom?.uri}`;
```

2023-03-11 12:15 UTC, caponetto commented on packages/serverless-logic-web-tools/src/editor/api/WebToolsSwfLanguageService.ts
> +        getRoutesDirPosixPaths: async (_textDocument) => ({
@Sara4994 can you please rebase your branch with `main`? 
We need to add `getRoutesDirPosixPaths` [here](https://github.com/kiegroup/kie-tools/blob/main/packages/serverless-workflow-text-editor/dev-webapp/channel/DevWebAppSwfLanguageService.ts) as well.

2023-03-12 13:52 UTC, Sara4994 commented on packages/serverless-logic-web-tools/src/editor/api/WebToolsSwfLanguageService.ts
> +        getRoutesDirPosixPaths: async (_textDocument) => ({
@caponetto done 👍

2023-03-13 10:05 UTC, caponetto commented on packages/vscode-extension-serverless-workflow-editor/src/extension/serviceCatalog/fs/FsWatchingServiceCatalogRelativeStore.ts
> +  private readFileSystemServices(dirAbsolutePosixPath: any): Promise<SwfServiceCatalogService[]> {
```suggestion
  private readFileSystemServices(dirAbsolutePosixPath: string): Promise<SwfServiceCatalogService[]> {
```

2023-03-13 12:45 UTC, caponetto approved these changes

2023-03-13 14:12 UTC, ricardozanini commented
I'll be on PTO for the next few weeks, so I'm refraining from reviewing this PR. Feature-wise looks exactly like what we were talking about. Many thanks!

2023-03-13 19:29 UTC, paulovmr approved these changes

2023-03-14 14:15 UTC, tomasdavidorg requested changes
I found two issues:
- If a camel route file is added to the `routes` directory, it does not appear in the list of available functions after `+ Add function` is clicked. VS Code needs to be restarted and then the function is there
- `+ Add function` list displays the routes as `[specsDirName]>>` but there should be `[routesDir] name instead` 
![Screenshot from 2023-03-14 15-05-20](https://user-images.githubusercontent.com/4498639/225027009-a6004f29-ad56-44af-af6b-9fbcefaccc9c.png)

2023-03-14 14:15 UTC, tomasdavidorg commented on packages/serverless-workflow-service-catalog/src/channel/parsers/impl/camelRoutes/types.ts
> +  id: string;
```suggestion
  description: string;
  id: string;
```
Not an issue but just to have the definition complete, shouldn't we also add the `description` property? 
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json#L1049

2023-03-15 07:28 UTC, Sara4994 commented
> I found two issues:
> 
> * If a camel route file is added to the `routes` directory, it does not appear in the list of available functions after `+ Add function` is clicked. VS Code needs to be restarted and then the function is there
> * `+ Add function` list displays the routes as `[specsDirName]>>` but there should be `[routesDir] name instead`
>   ![Screenshot from 2023-03-14 15-05-20](https://user-images.githubusercontent.com/4498639/225027009-a6004f29-ad56-44af-af6b-9fbcefaccc9c.png)

@tomasdavidorg Thanks for pointing these bugs, really good catch. these are fixed now 👍

2023-03-16 09:18 UTC, tomasdavidorg approved these changes
Thanks @Sara4994. Looks good to me 🙂

2023-03-16 13:18 UTC, caponetto approved these changes

2023-03-16 13:18 UTC, merged