SWF Viewer - display stateDataFilter parameter with icon
apache/incubator-kie-tools pull request #1474
Opened 2023-02-21 14:56 UTC by hasys

2023-02-23 15:29 UTC, LuboTerifaj requested changes
Hello @hasys ,

I have found two issues:
- Empty string value is not trimmed in the diagram. It can cause showing a box with very wide width excessing the diagram.

- The parameters that are not present in source file should not be listed the diagram.
  - I understand that the similar issue is present also for other icons, so it is not necessary to change it in this PR, but it is definitely something to discuss. 

Potential improvement:
- If there are no other icons in state, currently shown icon could be aligned to the top right corner.
  - I reported the issue here: https://issues.redhat.com/browse/KOGITO-8726

Thanks!

2023-02-23 15:45 UTC, hasys commented
Hello @LuboTerifaj, great feedback thank you!

Just not sure the point about:

* Empty string value is not trimmed in the diagram. It can cause showing a box with very wide width excessing the diagram.

Can I ask you to provide JSON and screenshot to illustrate the issue there?

2023-03-01 14:50 UTC, LuboTerifaj approved these changes
Hey @hasys 

It looks good to me now.

I reported the issue with showing undefined values here:
https://issues.redhat.com/browse/KOGITO-8762

Thanks!

2023-03-02 14:08 UTC, romartin approved these changes

2023-03-02 14:08 UTC, merged