KOGITO-8721 Solve CORS error message and dataset error message
apache/incubator-kie-tools pull request #1487
Opened 2023-02-27 09:38 UTC by kumaradityaraj

User friendly message is displayed when a dataset is missing or it's URL is not reachable and if there is any CORS error, A message is displayed which is relevant to it.

![Screenshot from 2023-02-27 15-03-03](https://user-images.githubusercontent.com/82813768/221527644-5335e7dd-8384-4603-a364-2c5be4d50320.png)
![Screenshot from 2023-02-27 15-01-58](https://user-images.githubusercontent.com/82813768/221527651-13ebcb8b-0a0b-45e9-b6b0-bc1a211fce3a.png)

2023-02-28 20:31 UTC, jesuino requested changes
It is looking great, thanks @kumaradityaraj 

Just a small change and we are done

2023-02-28 20:31 UTC, jesuino commented on packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
> +                new RuntimeException("Request not started, make sure that CORS is enabled. message: " + e)
```suggestion
                new RuntimeException("Request not started, make sure that CORS is enabled. Message: " + e)
```

please change to `Message`

2023-03-01 13:18 UTC, jesuino approved these changes
good work, thanks @kumaradityaraj

2023-03-01 14:03 UTC, paulovmr approved these changes

2023-03-01 14:03 UTC, merged