kie-issues#91 Strange behavior when importing a Gist file on KIE Sandbox
apache/incubator-kie-tools pull request #1525
Opened 2023-03-15 13:16 UTC by kbowers-ibm

Closes https://github.com/kiegroup/kie-issues/issues/91

2023-03-27 18:17 UTC, tiagobento requested changes
Very good! Left some minor comments inline.

2023-03-27 18:17 UTC, tiagobento commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +  supported:
Is this used somewhere? I couldn't find usages for it..

2023-03-27 18:17 UTC, tiagobento commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +}
Why not make this a single enum?

2023-03-27 18:23 UTC, kbowers-ibm commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +}
It was causing an error at \serverless-logic-web-tools\src\workspace\components\FileLabel.tsx with the const labelColors, which wanted the sandbox file types to be defined in there.

2023-03-27 18:24 UTC, kbowers-ibm commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +  supported:
No usages anywhere. I thought maybe it was there as a sort of "comment" to have all supported filetypes in one type

2023-03-27 18:26 UTC, kbowers-ibm commented
Do not merge! Investigating a bug where a file with file extension e.g. .dmn, will error if .dmn is anywhere in the name of the file except at the end.

2023-03-28 18:43 UTC, tiagobento requested changes
Alright, looking good! Let's solve the two remaining comments before proceeding.. I need to test it locally too..

@caponetto Can you help us verify this on Serverless Logic Web Tools?

2023-03-28 18:43 UTC, tiagobento commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +  supported:
Alright, so if there are no usages, let's delete it :D

2023-03-28 18:43 UTC, tiagobento commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +}
Can you give more details? I'm not sure I understand the problem..

2023-03-28 19:27 UTC, caponetto reviewed
Thanks guys! I will test locally the serverless logic web tools tomorrow.

2023-03-28 19:27 UTC, caponetto commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +export function isDecision(path: string): boolean {
I know these methods (`isXYX`) were only moved but I think we can replace them with some TS tricks, like:

```ts
type FileRegexKind = keyof typeof REGEX;
const matchers: Record<FileRegexKind, (path: string) => boolean> = {} as any;
for (const key in REGEX) {
  const kind = key as FileRegexKind;
  matchers[kind] = (path: string): boolean => REGEX[kind].test(path);
}

function isOfKind(kind: FileRegexKind, path: string) {
  return matchers[kind](path);
}

// usage examples
isOfKind("swYaml", "foo/bar/model.sw.json") // ----> false 
isOfKind("swJson", "foo/bar/model.sw.json") // ----> true
isOfKind("bpmn", "model.bpmn") // ----> true
isOfKind("bpmn", "model.dmn") // ----> false
isOfKind("bpmn", "model.bpmn.bpmn") // ----> true
```

Anyway, just a suggestion.

2023-03-28 19:27 UTC, caponetto commented on packages/workspaces-git-fs/src/relativePath/WorkspaceFileRelativePathParser.ts
> +      case isServerlessWorkflowJson(fileName):
Why use a switch-case statement here?
I think if-return would suit better.

2023-03-29 08:51 UTC, klbowers commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +}
![Screenshot (4)](https://user-images.githubusercontent.com/92726146/228481313-b24bd1ac-8001-4676-983f-92524d330622.png)
There's a serverless-logic const called 'labelColors' which is a record with 'FileTypes' as a property, so when the sandbox FileTypes and serverless FileTypes are a single enum, labelColors requires dmn,bpmn,etc. to be defined in there. I've changed it to have string as a property instead of FileTypes (which is what online-editor does)

2023-03-29 10:08 UTC, kbowers-ibm commented on packages/workspaces-git-fs/src/constants/ExtensionHelper.ts
> +export function isDecision(path: string): boolean {
Feels a lot cleaner, thanks for that!

2023-03-29 14:19 UTC, caponetto commented on packages/workspaces-git-fs/src/relativePath/WorkspaceFileRelativePathParser.ts
> +    relativePathWithoutExtension: relativePath.substring(0, relativePath.lastIndexOf("." + extension)),
The only issue I found on Serverless Logic Web Tools is that I cannot open files that do not have extensions anymore. 

Probably because of this change.
For example, if I have `relativePath=test`, `relativePathWithoutExtension` returns `""` but it should be `test`.

2023-03-29 15:11 UTC, kbowers-ibm commented on packages/workspaces-git-fs/src/relativePath/WorkspaceFileRelativePathParser.ts
> +    relativePathWithoutExtension: relativePath.substring(0, relativePath.lastIndexOf("." + extension)),
Fixed, sorry about that! Didn't realize that SLWT could open files without extensions

2023-03-29 16:32 UTC, caponetto commented on packages/workspaces-git-fs/src/relativePath/WorkspaceFileRelativePathParser.ts
> +    relativePathWithoutExtension: relativePath.substring(0, relativePath.lastIndexOf("." + extension)),
Thanks!!

2023-03-29 16:34 UTC, caponetto approved these changes
LGTM! Thanks @kbowers-ibm!
I suggest changing the title of this PR to something that better describes the issue.

2023-03-30 13:34 UTC, tiagobento approved these changes

2023-03-30 13:34 UTC, merged