NO-ISSUE: Fixed typo on SWF VSCode Extension
apache/incubator-kie-tools pull request #1547
Opened 2023-03-31 15:08 UTC by fantonangeli

Found a small typo in `kie-tools/packages/vscode-extension-serverless-workflow-editor/package.json`:
`rimraf test-resou &&`
but at the beginning of the command, there is already 
`rimraf ./test-resources &&`

In the end, the typo doesn't have any effect on the project.

2023-03-31 15:50 UTC, caponetto approved these changes

2023-04-03 10:46 UTC, zdrapela commented
Hi, that's a great catch. I believe it is the same for `vscode-extension-pack-kogito-kie-editors` and `vscode-extension-yard-editor`. These packages also contain `rimraf test-resou &&` with no obvious reason in `package.json` (as no folder called `test-resou` appear during running tests. Would consider adding these to this PR too.

2023-04-03 13:17 UTC, fantonangeli commented
> Hi, that's a great catch. I believe it is the same for `vscode-extension-pack-kogito-kie-editors` and `vscode-extension-yard-editor`. These packages also contain `rimraf test-resou &&` with no obvious reason in `package.json`. Would consider adding these to this PR too.

Sure no problem @zdrapela

2023-04-03 13:42 UTC, zdrapela requested changes
Just a small suggestion for `test:it:clean:offline`, otherwise it looks great :+1:

2023-04-03 13:42 UTC, zdrapela commented on packages/vscode-extension-pack-kogito-kie-editors/package.json
> +    "test:it:clean:offline": "rimraf ./dist-it-tests && rimraf ./out && rimraf ./it-tests-tmp && rimraf ./test-resources && rimraf *.vsix",
```suggestion
    "test:it:clean:offline": "rimraf ./dist-it-tests && rimraf ./out && rimraf ./it-tests-tmp && rimraf *.vsix",
```
In the `test:it:clean:offline` command, the `rimraf ./test-resources` is omitted intentionally, because files cached in this folder are needed for running tests offline without additional downloading VSCode and ChromeDriver, so the folder is not to be deleted.

2023-04-03 14:17 UTC, fantonangeli commented on packages/vscode-extension-pack-kogito-kie-editors/package.json
> +    "test:it:clean:offline": "rimraf ./dist-it-tests && rimraf ./out && rimraf ./it-tests-tmp && rimraf ./test-resources && rimraf *.vsix",
This is a functionality that would be very useful for `vscode-extension-serverless-workflow-editor`.
I would add `test:it:clean:offline` and `test:it:offline` in the `package.json` of   `vscode-extension-serverless-workflow-editor` and `vscode-extension-yard-editor`.
WDYT?

2023-04-03 14:19 UTC, zdrapela commented on packages/vscode-extension-pack-kogito-kie-editors/package.json
> +    "test:it:clean:offline": "rimraf ./dist-it-tests && rimraf ./out && rimraf ./it-tests-tmp && rimraf ./test-resources && rimraf *.vsix",
Yes, that would be great!

2023-04-03 15:53 UTC, caponetto approved these changes

2023-04-03 16:52 UTC, zdrapela requested changes
There is one more thing about running the IT tests offline - there should be a flag `--offline` in the `extest setup-and-run` command as the [`ExTester` wiki suggests](https://github.com/redhat-developer/vscode-extension-tester/wiki/Test-Setup#set-up-and-run-tests). I see that having the VSCode and ChromeDriver cached is enough and the tests run offline just fine even without the flag, but I would rather add the `--offline` flag just to be sure :smile: 
The flag was initially there, but was removed in [#1153](https://github.com/kiegroup/kie-tools/commit/90fb49a41defdf24138eced3451f8ae5bca93bac#diff-0f5e1ec86fd1b1e6dd1c1546e993229fde5c0a052304f7e3b8044e81f502f7cdL30). Luckily, the offline mode keeps on working anyway :smile:

2023-04-03 16:52 UTC, zdrapela commented on packages/vscode-extension-pack-kogito-kie-editors/package.json
>      "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-test
```suggestion
    "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-tests/resources it-tests-tmp/resources\" \"tsc --project tsconfig.it-tests.json --skipLibCheck --sourceMap true\" \"extest setup-and-run --offline --yarn -c max -u -e ./test-resources -o it-tests/settings.json out/*.test.js\"",
```

2023-04-03 16:52 UTC, zdrapela commented on packages/vscode-extension-serverless-workflow-editor/package.json
> +    "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-test
```suggestion
    "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-tests/resources it-tests-tmp/resources\" \"tsc --project tsconfig.it-tests.json --skipLibCheck --sourceMap true\" \"extest setup-and-run --offline --yarn -c max -u -e ./test-resources -o it-tests/settings.json out/*.test.js\"",
```

2023-04-03 16:52 UTC, zdrapela commented on packages/vscode-extension-yard-editor/package.json
> +    "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-test
```suggestion
    "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-tests/resources it-tests-tmp/resources\" \"tsc --project tsconfig.it-tests.json --skipLibCheck --sourceMap true\" \"extest setup-and-run --offline --yarn -c max -u -e ./test-resources -o it-tests/settings.json out/*.test.js\"",
```

2023-04-04 06:23 UTC, zdrapela commented on packages/vscode-extension-pack-kogito-kie-editors/package.json
>      "test:it:offline": "run-script-if --ignore-errors \"$(build-env integrationTests.ignoreFailures)\" --bool \"$(build-env integrationTests.run)\" --then \"pnpm test:it:clean:offline\" \"cpr it-test
As I tried the commands, it looks that caching works with and without the `--offline` flag, but running the tests completely offline with the `--offline` flag, with the internet connection disabled, is not possible (I am getting an error that connection to update.code.visualstudio.com is not possible). So it looks like the [Extension tester](https://github.com/redhat-developer/vscode-extension-tester) might not work correctly. Anyway, I would still keep the `--offline` flag.

2023-04-05 06:53 UTC, zdrapela approved these changes

2023-04-05 09:46 UTC, merged