SWF Editor - Issues on state selection & tooltip overlapping toolbox
apache/incubator-kie-tools pull request #1549
Opened 2023-04-02 23:19 UTC by romartin

Hey @LuboTerifaj 

See https://issues.redhat.com/browse/KOGITO-8288 https://issues.redhat.com/browse/KOGITO-8947

Thanks!

2023-04-03 09:25 UTC, hasys commented
Hi @romartin,

thank you for PR! 

Looks like there is a random test fail:

```
  1 failing

  1) Serverless workflow editor - Basic operations tests
       "after each" hook for "Opens, edits and saves the *.sw.json file":
     StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=102.0.5005.196)
      at Object.throwDecodedError (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/http.js:587:13)
      at Executor.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/http.js:515:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
      at async toWireValue (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:145:15)
      at async /home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:195:16
      at async forEachKey (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:189:9)
      at async convertKeys (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:194:3)
      at async Driver.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.8.1_patch_hash=lbqefch5nrzt5atgrk2dnw5phe/node_modules/selenium-webdriver/lib/webdriver.js:743:22)
```

To restart the build you need to push empty commit to the branch. To commit an empty PR you can execute this  command:
```
git commit --allow-empty -m "Empty commit - CI Run"
```

Going to check locally meanwhile.

2023-04-03 11:11 UTC, hasys commented
Hello Roger,

Looks good both Edit and View mode. Just one note: is it possible to keep the click handler on the Icons?

2023-04-03 11:13 UTC, hasys requested changes

2023-04-03 11:13 UTC, hasys commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/CornerIcon.java
> -        );
Maybe we can change from Goup to Path or getShape instead, it will be clearer and click should still work.

2023-04-03 20:42 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/CornerIcon.java
> -        );
done , reverted click handler

2023-04-03 20:42 UTC, romartin commented
Hey @hasys 

Thanks for the review. I rebased from main again, so test failure should gone, also I added again the click handler for the button.

Thanks!

2023-04-04 12:13 UTC, hasys commented
Hello Roger, I found some small issues:

* Onclick is still removed on Bottom depiction
* Mouse over do not highlight the button
* After you improved Tooltip there are some excessive "moveOnTop" on mouse hover.

I created a small PR for your branch to fix those issues: https://github.com/romartin/kie-tools/pull/3

Thank you!

2023-04-04 19:32 UTC, romartin commented
Thanks a lot @hasys ! Merged, builds re-running

2023-04-04 19:52 UTC, romartin commented
Hey @LuboTerifaj @hasys 

I updated the link the WAR bundle in the description above, including latest changes from this PR review. So WAR ready to test again!

Thanks!

2023-04-05 09:06 UTC, hasys approved these changes
Hello @romartin,

great job, works good now.

Thank you!

2023-04-27 08:56 UTC, LuboTerifaj requested changes
Hello @romartin ,

I found the following issue:

- If you click directly on the state's icon and keep hovering over it, the tooltip is shown behind toolbox.

Thanks!

2023-05-04 20:33 UTC, romartin commented
Thanks @LuboTerifaj , good catch! 

Fixed and ready for review again, I updated the link for the WAR file to test in the description of this PR.

Thanks!

2023-05-04 22:21 UTC, romartin commented
rebased

2023-05-05 09:06 UTC, LuboTerifaj approved these changes
Hi @romartin ,

It looks good to me now.

Thanks for the fix!

2023-05-05 09:08 UTC, LuboTerifaj commented
Hello @romartin , please consider to include at least one of the jiras' ids to squashed commit message. Thanks!

2023-05-05 11:16 UTC, merged