kie-issues#245: Create a Docker Compose file to run KIE Sandbox and its related services
apache/incubator-kie-tools pull request #1628
Opened 2023-05-11 16:13 UTC by RishiRajAnand

This PR aims to create a docker compose file to run KIE sandbox and its related containers like kie_extended_services and git-cors-proxy-image with a single command. we can use ${KIE_TOOL_VERSION} environment variable to run specific version of KIE Sandbox.

issue link : https://github.com/kiegroup/kie-issues/issues/245

2023-05-11 16:43 UTC, porcelli requested changes
made a few comments

2023-05-11 16:43 UTC, porcelli commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +      - 7081:8080
same here about the ports parameter and docs

2023-05-11 16:43 UTC, porcelli commented on pnpm-lock.yaml
not sure if this file should be here for this PR content

2023-05-11 16:43 UTC, porcelli commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +      KIE_SANDBOX_GIT_CORS_PROXY_URL: http://localhost:7081
can we get these ports as parameters?

2023-05-11 16:43 UTC, porcelli commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +    image: quay.io/kie-tools/kie-sandbox-image:${KIE_TOOL_VERSION}
would be good to have by default KIE_TOOL_VERSION using the latest stable image published

2023-05-11 20:21 UTC, thiagoelg requested changes
Thanks for the PR!
Left some inline comments about env vars.

Also, we should probably have a `package.json` file with the dependencies (`kie-sandbox-image`, `git-cors-proxy`, `extended-services`) and some scripts to start, stop, and build this docker-compose. Having a `package.json` file means that this package is mapped on our dependencies graph and bootstrapped with the rest of the project.

2023-05-11 20:21 UTC, thiagoelg commented on packages/kie-sandbox-distribution/README.md
> +  export KIE_TOOL_VERSION=<kie_tool_version>
WDYT about renaming this env var to `KIE_SANDBOX_DISTRIBUTION__imageTag` and creating an `env/index.js` just like the other packages?

2023-05-11 20:21 UTC, thiagoelg commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +             "enabled": false,
This can be enabled, as we provide support for it now.

2023-05-11 20:21 UTC, thiagoelg commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +             "id": "GitHub_at_IBM",
Is this required for the community version? Maybe we could just remove the `KIE_SANDBOX_AUTH_PROVIDERS` env var and let the `online-editor` use it's default.

2023-05-11 20:24 UTC, porcelli commented
Good catches @thiagoelg! I completely overlooked the internal GitHub reference 😁

2023-05-12 10:13 UTC, RishiRajAnand commented
Thanks for the review.
@porcelli @thiagoelg I have added the changes as described. Could you please review it again ?

2023-05-12 21:16 UTC, thiagoelg requested changes
Added some more inline comments regarding the env vars.

Also, the package.json scripts didn't work for me, they just finish without errors after setting the env vars, not starting the docker compose command. Let me know if I can help debug with anything.

Btw. I noticed some problems with the `kie-sandbox-image` on `main`, [this PR](https://github.com/kiegroup/kie-tools/pull/1633) should fix it.

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/env/index.js
> +  vars: varsWithName({
Would be good to have a pattern for these environment variables.
Some things to note:
- The prefix should be the same for all env vars;
- The full env var name should be `{prefix}__{varName}`, note the double `_`;
- Have different env vars for different image tags;

Here's an example:
```
KIE_SANDBOX_DISTRIBUITION__kieSandboxImageTag
KIE_SANDBOX_DISTRIBUITION__kieSandboxPort
KIE_SANDBOX_DISTRIBUITION__extendedServicesImageTag
KIE_SANDBOX_DISTRIBUITION__extendedServicesPort
KIE_SANDBOX_DISTRIBUITION__gitCorsProxyImageTag
KIE_SANDBOX_DISTRIBUITION__gitCorsProxyPort
```

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/env/index.js
> +      },
Following the example above, this could be something like this:

```suggestion
      kieSandboxDistribution: {
        kieSandbox: {
          imageTag: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__kieSandboxImageTag),
          port: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__kieSandboxPort),
        },
        extendedServices: {
          imageTag: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__extendedServicesImageTag),
          port: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__extendedServicesPort),
        },
        gitCorsProxy: {
          imageTag: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__gitCorsProxyImageTag),
          port: getOrDefault(this.vars.KIE_SANDBOX_DISTRIBUITION__gitCorsProxyPort),
        },
      },
```

I know it seems more verbose, but it helps bring clarity to our env vars and their purposes.

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +    container_name: kie_extended_services
```suggestion
  extended_services:
    container_name: extended_services
```

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +    container_name: cors
```suggestion
  git_cors_proxy:
    container_name: git_cors_proxy
```

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/docker-compose.yaml
> +      KIE_SANDBOX_REQUIRE_CUSTOM_COMMIT_MESSAGE: true
This can be removed, let the default value be used and users can change them if they want.

2023-05-12 21:16 UTC, thiagoelg commented on packages/kie-sandbox-distribution/README.md
> +  pnpm -F @kie-tools/kie-sandbox-image... build:prod
Setting the `KIE_TOOLS_BUILD__buildContainerImages` env var to `true` is necessary to build images.

```suggestion
  KIE_TOOLS_BUILD__buildContainerImages=true pnpm -F @kie-tools/kie-sandbox-image... build:prod
```

2023-05-15 11:11 UTC, RishiRajAnand commented
Thanks @thiagoelg . I have pushed the changes as you suggested. 

Actually, there seems to be an issue while running command with run-script-if module. When the paste the final command generated by it in console, it works fine 

`KIE_SANDBOX_DISTRIBUITION__kieSandboxImageTag=0.27.0 KIE_SANDBOX_DISTRIBUITION__kieSandboxPort=9090 KIE_SANDBOX_DISTRIBUITION__extendedServicesImageTag=0.27.0 KIE_SANDBOX_DISTRIBUITION__extendedServicesPort=21345 KIE_SANDBOX_DISTRIBUITION__gitCorsProxyImageTag=0.27.0 KIE_SANDBOX_DISTRIBUITION__gitCorsProxyPort=7081 docker compose up`

Do you know what could be the problem here ?

2023-05-16 01:23 UTC, thiagoelg commented
@RishiRajAnand I don't think `run-script-if` support this kind of command, have to investigate it though.

But, figured out something that could help, check these two changes here:
- https://github.com/kiegroup/kie-tools/compare/main...thiagoelg:245-docker-compose?expand=1#diff-b0d31180ddd1b97f88e6ea4f8caa9786af935bfb896563c4106585858c3191bd
- https://github.com/kiegroup/kie-tools/compare/main...thiagoelg:245-docker-compose?expand=1#diff-f558d729d1541c415a0fddcb6f13be77cb334cf11047f3c78ddba804cca93257

The first one adds a `--print-env-file:self` option to our `build-env` script;
The second one uses this new option to output a `.env` file to be used by docker-compose.
What do you think?

___

On another note, I think that we might need some new env vars, considering the following scenarios:
- The images are hosted somewhere else other than `quay.io` and published by a different user other than `kiegroup`.
- The containers are not exposed via `localhost` but via another hostname, think of how this would work if deployed to OpenShift for example.

The good news is that we already have env vars for this kind of stuff, so maybe we can reuse them here. Check out how our GitHub actions use this env vars to publish new releases: https://github.com/kiegroup/kie-tools/blob/main/.github/workflows/staging_build.yml#L43

2023-05-17 13:18 UTC, RishiRajAnand commented
@thiagoelg these changes would make our scripts more clean. On other side, the generated .env file can also be used by users to directly modify and then run `docker compose up` which is prefered way in docker compose.

I think we can merge your changes while I am working on adding env variables as you mentioned there. wdyt ?

2023-05-17 13:45 UTC, thiagoelg commented
@RishiRajAnand sounds good!

2023-05-18 06:27 UTC, RishiRajAnand commented
@thiagoelg Thanks a lot for changes. I have merged it.
I have added more env variables that would make our image location a variable.
However, i think since docker compose always runs on single machine and uses localhost ports for its services. It'd be good to keep `localhost` in service URL. wdyt ?
For openshift/kubernetes use case, i am already working on creating helm charts to run kie sandbox https://github.com/kiegroup/kie-issues/issues/240

2023-05-18 13:17 UTC, thiagoelg approved these changes

2023-05-18 13:51 UTC, porcelli approved these changes

2023-05-19 10:44 UTC, RishiRajAnand commented
updated README.md with new env variables.

2023-05-19 13:27 UTC, thiagoelg commented
@RishiRajAnand seems like CI is failing due to the dependency graph being out of date:

```
Check hanging uncommitted files (you should commit those!)
Run git diff
diff --git a/repo/graph.dot b/repo/graph.dot
index 7dcff60bdc..13bd32c1f3 100644
--- a/repo/graph.dot
+++ b/repo/graph.dot
@@ -[9](https://github.com/kiegroup/kie-tools/actions/runs/5023443214/jobs/9008043296?pr=1628#step:15:10)3,6 +93,7 @@ digraph G {
   "@kie-tools/pmml-editor-marshaller" [ color = "blue", fontcolor = "blue", style = "rounded" ];
   "kie-editors-dev-vscode-extension" [ color = "black", fontcolor = "black", style = "dashed, rounded" ];
   "@kie-tools/pmml-editor" [ color = "blue", fontcolor = "blue", style = "rounded" ];
+  "@kie-tools/vscode-extension-common-test-helpers" [ color = "blue", fontcolor = "blue", style = "rounded" ];
   "@kie-tools/kie-sandbox-distribution" [ color = "black", fontcolor = "black", style = "dashed, rounded" ];
   "@kie-tools/kie-sandbox-extended-services-image" [ color = "black", fontcolor = "black", style = "dashed, rounded" ];
   "@kie-tools/kie-sandbox-image" [ color = "black", fontcolor = "black", style = "dashed, rounded" ];
diff --git a/repo/graph.json b/repo/graph.json
index b7a24ebc45..3920ad7089 [10](https://github.com/kiegroup/kie-tools/actions/runs/5023443214/jobs/9008043296?pr=1628#step:15:11)0644
--- a/repo/graph.json
+++ b/repo/graph.json
@@ -101,6 +101,7 @@
       { "id": "@kie-tools/import-java-classes-component" },
       { "id": "kie-editors-dev-vscode-extension" },
       { "id": "@kie-tools/pmml-editor" },
+      { "id": "@kie-tools/vscode-extension-common-test-helpers" },
       { "id": "@kie-tools/kie-sandbox-distribution" },
       { "id": "@kie-tools/kie-sandbox-extended-services-image" },
       { "id": "@kie-tools/kie-sandbox-image" },
Error: Process completed with exit code 1.
```

Running `pnpm bootstrap` locally and committing the changes should fix the issue.

2023-05-22 13:48 UTC, RishiRajAnand commented
@thiagoelg i have pushed the changes

2023-05-22 16:31 UTC, tiagobento approved these changes

2023-05-22 16:31 UTC, merged