kie-issues#259: Adapt context menu content for multiple cell selections
apache/incubator-kie-tools pull request #1652
Opened 2023-05-19 04:58 UTC by jomarko

This PR closes: https://github.com/kiegroup/kie-issues/issues/259

2023-05-25 18:47 UTC, tiagobento reviewed
I know this is in draft, but I was taking a look so... here are some comments :)

2023-05-25 18:47 UTC, tiagobento commented on packages/boxed-expression-component/src/i18n/locales/en.ts
> +  noOptionsAvailable: "No options available.",
Is this not being used? If this is an "empty state" for the context menu, I think it should be "No operations available."

2023-05-25 18:47 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +      columns: ReactTable.ColumnInstance<any>[] | undefined
No need to redeclare the types here.

2023-05-25 18:47 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +    columns: ReactTable.ColumnInstance<any>[] | undefined
This could probably be extract to a type so we avoid duplicating the types of each parameter, and also prevent the confusion between the first two arguments that are of the same type.

2023-05-25 18:47 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx
> +          { name: i18n.rowOperations.delete, type: BeeTableOperation.RowDuplicate },
This should have the "Duplicate" label, no?

2023-05-30 06:40 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx
> +          { name: i18n.rowOperations.delete, type: BeeTableOperation.RowDuplicate },
well spotted , fixing

2023-05-30 06:40 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +    columns: ReactTable.ColumnInstance<any>[] | undefined
good idea, will introduce a separate type

2023-05-30 06:41 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +      columns: ReactTable.ColumnInstance<any>[] | undefined
ok, I will try to remove them, not sure if it was not added automatically in some precommit hook, I will see.

2023-05-30 10:48 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +    columns: ReactTable.ColumnInstance<any>[] | undefined
@tiagobento for now, I just used `selection: BeeTableSelection` instead of `selectionStart` and `selectionEnd`

So with my latest changes `allowedOperations` still has 4 parameters. What is not ideal. Especially `column` and `columns` are used basically just for `Decision Table` expression.

What is you opinion about passing just `selection` - containing current selection start and selection end, and `reactTable Instance` - containing columns, rows length?

2023-05-30 11:35 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx
> +    config[""] = generateOperationConfig(i18n.outputClause);
change due to https://github.com/kiegroup/kie-issues/issues/291

2023-06-07 22:13 UTC, tiagobento commented
Oops.. conflict :D

2023-06-07 22:20 UTC, tiagobento requested changes
Nice job @jomarko @danielzhe! This PR looks really nice. As usual, left some comments inline :)

2023-06-07 22:20 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +          break;
Can we change those to `console.debug`? Perhaps with more information, even..

2023-06-07 22:20 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +  const someOperationIsAllowed = allOperations.some((operation) => currentAllowedOperations.includes(operation.type));
```suggestion
  const hasAllowedOperations = allOperations.some((operation) => currentAllowedOperations.includes(operation.type));
```

? :D

2023-06-07 22:20 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +  const someOperationIsAllowed = allOperations.some((operation) => currentAllowedOperations.includes(operation.type));
Any reason why we're not memoizing these values? This is very important to avoid unnecessary re-renders.

2023-06-07 22:20 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +  const currentAllowedOperations = allowedOperations(selection, reactTableInstanceRowsLength, column, columns);
```suggestion
  const allowedOperationsForSelection = allowedOperations(selection, reactTableInstanceRowsLength, column, columns);
```

? :D

2023-06-07 22:20 UTC, tiagobento commented on packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx
> +      i18n.terms.paste,
No need to have i18n so granular.. A simple `i18n` here would be enough.

2023-06-07 22:20 UTC, tiagobento commented on packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx
> +      columns: ReactTable.ColumnInstance<any>[] | undefined
Let's extract this to a type? Will look cleaner everywhere. These types are replicated all over the code.

2023-06-07 22:20 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +  };
Wrap this in a `useMemo`.

2023-06-08 06:35 UTC, jomarko commented on packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx
> +      columns: ReactTable.ColumnInstance<any>[] | undefined
@tiagobento thank you for feedback. I incorporated it as:
- https://github.com/kiegroup/kie-tools/pull/1652/commits/ba2329206fc814caca28302e6336e71961c304f4

Furthermore, about introducing a a new type, I tried to simplify it even more, see:
- https://github.com/kiegroup/kie-tools/pull/1652/commits/3f423c6aec1f4837eb877a53c4264fc220c7121e

I thought I will be able to simplify `BeeTableContextMenuAllowedOperationsConditions` even more. I tried to remove `column` and `columns` from `BeeTableContextMenuAllowedOperationsConditions` and replace it in particual expressions with `beeTableColumns`, but I was not able to get it working. I think I miss some understanding of difference between `beeTableColumns` in `DecisionTableExpression` and `columns` in `beeTableContextMenuHandler`.

FYI, this PR currently assumes single cell is selected. Multiple cells selected scenarios are being covered by @danielzhe to cover fully kiegroup/kie-issues#168. However if it is fine to do it in separate PR, we can do it.

2023-06-08 16:02 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +    columns: ReactTable.ColumnInstance<any>[] | undefined
@jomarko No need to simplify it even more. Let's revert it back to the stage where it was working, and we'll be good to go.

2023-06-08 16:17 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +    } as BeeTableContextMenuAllowedOperationsConditions);
You shouldn't need a cast here... Please double-check.

2023-06-09 03:27 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx
> +    columns: ReactTable.ColumnInstance<any>[] | undefined
@tiagobento current state should be working, I can recheck during incorporating kiegroup/kie-issues#324

2023-06-09 04:06 UTC, jomarko commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
> +    } as BeeTableContextMenuAllowedOperationsConditions);
you were correct, removed

2023-06-09 11:10 UTC, jomarko commented on packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
>      }
This fixes kiegroup/kie-issues#324

2023-06-09 16:58 UTC, tiagobento commented
@jomarko Small comment.. as I mentioned, all cells should be Copy-able, including header and rowIndex cells..

2023-06-12 08:24 UTC, jomarko commented
@tiagobento ok, makes sense, then maybe a question, what cells can user paste value into:
- header cells - really not sure
- data cells - yes
- row index cells - no

can you help? or should I add just 'copy' as part of this PR and we can address 'paste' via different issue, if needed?

2023-06-12 15:09 UTC, tiagobento commented
@jomarko Yes.. pasting values to header cells is going to be a little bit more complicated, as there's more than a single value, usually (E.g., Name + Data Type). Let's address "copy" here and "paste" in another ticket :)

2023-06-13 13:57 UTC, tiagobento approved these changes

2023-06-13 14:56 UTC, merged