KOGITO-9245 - Chrome Extension is not properly working with the "New Code Search and Code View" GitHub Feature Preview
apache/incubator-kie-tools pull request #1720
Opened 2023-06-07 14:31 UTC by AjayJagan

2023-06-07 18:54 UTC, paulovmr requested changes
Hi @AjayJagan , I gave it a try to the SWF extension and got the following results:

1) View file: works when you open the file, see as source, and go back to see as diagram. Full screen and back also working. But, if you click on "Blame" and back to "Code", it goes to the text editor and there is no option to see as diagram again.

2) Edit file: Not opening the diagram.

3) View PR: See as diagram button works, but diagram rendering always has an error.

2023-06-08 06:03 UTC, AjayJagan commented
Hey @paulovmr thanks for the review
1. So I fixed the issue while switching between blame and code
2 & 3. These issues are related. The issue is that to enable the `commit changes...` button, I had to simulate a `keypress` event. This adds an extra char(`/x00`) in front of the code and that is why both the edit and the pr are not working properly.
If you edit it separately and check the pr .. it works .. I have attached a video to make it clear :)

https://github.com/kiegroup/kie-tools/assets/36824134/e3573ee7-dfbc-457a-af3b-89775327dcaa

2023-06-09 13:33 UTC, ljmotta commented on packages/chrome-extension/src/app/Dependencies.ts
> +      return document.querySelector(".Box-sc-g0xbh4-0.cpPHtE") as HTMLElement | null;
Hi @AjayJagan I'm not 100% sure, but it looks like those CSS classes were generated by the bundler. I think it's necessary to investigate this before, because if this is the case, the chrome extension would break in the next GitHub release.

2023-06-12 04:31 UTC, AjayJagan commented on packages/chrome-extension/src/app/Dependencies.ts
> +      return document.querySelector(".Box-sc-g0xbh4-0.cpPHtE") as HTMLElement | null;
changed to static css class names.. let me know if they are good :)

2023-06-29 19:31 UTC, paulovmr requested changes
Hi @AjayJagan , the changes in the code LGTM. I'm testing both extensions and found out a few issues:

1) When viewing a PR, does not matter if I select "Original" or "Changes", I only see the changed file (tested with a workflow).

2) When editing a BPMN and DMN file, the text editor was not hidden, and the diagram was below it. The DMN also showed an error in the diagram in that test.

2023-06-30 14:34 UTC, paulovmr requested changes
@AjayJagan About the first issue, it seems to be only on closed PRs, so I think we can look at it in another JIRA. The second one I couldn't reproduce anymore. Only one more comment before approving from my side.

@ljmotta If you want to give it a look to to see if the PR is ok now.

2023-06-30 14:34 UTC, paulovmr commented on packages/chrome-extension-pack-kogito-kie-editors/static/scripts/set-content.js
> +const cmInstance = document.querySelector(".cm-content").cmView;
Could you please add `kieTools_` namespace prefix to all variables added in content scripts? Like this:
```suggestion
const kieTools_cmInstance = document.querySelector(".cm-content").cmView;
```

2023-06-30 14:37 UTC, paulovmr commented
@tomasdavidorg If you could please try this out too, or assign someone else. Thanks!

2023-06-30 14:40 UTC, paulovmr commented
To test locally, you have to add the `kie-tools/packages/[chrome-extension-pack-kogito-kie-editors,chrome-extension-serverless-workflow-editor]/dist` folder as an unpacked extension in Chrome, and also leave `pnpm start` running at `kie-tools/packages/[chrome-extension-pack-kogito-kie-editors,chrome-extension-serverless-workflow-editor]`.

2023-07-03 10:50 UTC, tomasdavidorg commented
@paulovmr I will try to take a look today or tomorrow.

2023-07-04 08:08 UTC, tomasdavidorg commented
Hi @AjayJagan, I tried the plugin and I got some weird results:

1. Open https://github.com/kiegroup/kogito-examples/blob/stable/serverless-workflow-examples/serverless-workflow-annotations-description/src/main/resources/jsonannotations.sw.json 
2. Click edit.
3. jsonannotations.sw.json is edited.
5. Click back to resources and open yamlannotations.sw.yml
6. Click edit.
7. The first JSON file is edited (jsonannotations.sw.json).

2023-07-04 08:32 UTC, tomasdavidorg commented
[Screencast from 2023-07-04 10-31-21.webm](https://github.com/kiegroup/kie-tools/assets/4498639/335d23d1-f86e-4cc2-bd60-cc5ad6df56bd)

2023-07-07 14:21 UTC, thiagoelg commented
Just a heads up, we are disabling integration tests for the chrome-extension-pack for now, since it's breaking on the CI
https://github.com/kiegroup/kie-tools/pull/1813/commits/fd88d5f09875cf1f4bafa461760e995596631d54

Related to https://github.blog/changelog/2023-07-06-anonymous-users-have-access-to-new-code-view-and-navigation/

2023-07-07 14:59 UTC, AjayJagan commented
> fd88d5f

sure np 👍

2023-07-07 16:09 UTC, caponetto commented
@AjayJagan since we merge https://github.com/kiegroup/kie-tools/pull/1841, can you please rebase your branch with main and re-enable the tests?

2023-07-10 04:50 UTC, AjayJagan commented
@thiagoelg @caponetto  fixed the IT tests and enabled it.

2023-07-10 12:38 UTC, tomasdavidorg approved these changes

2023-07-11 21:46 UTC, paulovmr requested changes

2023-07-11 21:46 UTC, paulovmr commented on packages/chrome-extension/src/app/components/single/singleEditorEdit.tsx
> +  React.useEffect(() => {
```suggestion
  useEffect(() => {
```

2023-07-11 21:46 UTC, paulovmr commented on packages/chrome-extension/src/index.ts
> +function switchHiddenCssForNonSwfFiles(id: string, dependencies: Dependencies) {
This is a generic package, so there should be no direct reference to a specific editor or extension. In this case, this method name should be changed and the `editorEnvelopeLocator` should be used to check if the path is supported by the extension or not. The `editorEnvelopeLocator` comes from `globals`, and can have it access added here through parameters.

2023-07-12 15:45 UTC, paulovmr requested changes

2023-07-12 15:45 UTC, paulovmr commented on packages/chrome-extension/src/app/utils.ts
> +      for (let mutation of mutations) {
```suggestion
      for (const mutation of mutations) {
```

2023-07-12 16:16 UTC, paulovmr approved these changes

2023-07-12 19:12 UTC, merged