i18n: German translations
apache/incubator-kie-tools pull request #1735
Opened 2023-06-12 13:30 UTC by mariokorte

I've added most of the translations in German where localization support is already available.

2023-06-14 15:46 UTC, tiagobento commented
Hi @mariokorte! Thanks for the contribution! @martinweiler will assist with the review of this PR.

I noticed that there are some places where the translations are not ready yet. Should we wait to review until you have everything translated? Let me know!

2023-06-15 05:42 UTC, mariokorte commented
Hey @tiagobento and @martinweiler,

thanks for letting me know that there are still some rough edges. I will look into the missing parts and add them to this PR.

I will comment here when this is completed.

2023-06-15 07:43 UTC, mariokorte commented
That completes my work on this for now.
If there are any problems or suggestions I'm happy to support further.

2023-06-20 18:07 UTC, martinweiler commented on packages/boxed-expression-component/src/i18n/locales/de.ts
> +  class: "class",
Is this not translated on purpose?

2023-06-20 18:08 UTC, martinweiler commented on packages/boxed-expression-component/src/i18n/locales/de.ts
> +  document: "document",
No translation

2023-06-20 18:25 UTC, martinweiler commented on packages/online-editor/src/i18n/locales/de.ts
> +      createGist: "Gist successfully created.",
Missing translation

2023-06-20 18:32 UTC, martinweiler commented on packages/online-editor/src/i18n/locales/de.ts
> +    chooseLocalFile: "Wähle eine lokale Datei",
Minor nitpicking - in other places the user is addressed formally, shouldn't it be the same here ("Wählen Sie eine lokale Datei")?

2023-06-20 18:33 UTC, martinweiler commented on packages/online-editor/src/i18n/locales/de.ts
> +              runFollowingCommand: `Run the following command on a Terminal tab to start ${de_common.names.extendedServices} on a different port:`,
Missing translation

2023-06-20 18:35 UTC, martinweiler commented on packages/online-editor/src/i18n/locales/de.ts
> +      title: "Revert",
Missing translation

2023-06-20 18:36 UTC, martinweiler commented on packages/serverless-logic-web-tools/src/i18n/locales/de.ts
> +      errorPushingGist: "Push für das aktuelle Gist fehlgeschlagen. Push erzwungen?",
Missing translation

2023-06-20 18:36 UTC, martinweiler commented on packages/serverless-logic-web-tools/src/i18n/locales/de.ts
> +      createGist: "Gist successfully created.",
Missing translation

2023-06-20 18:37 UTC, martinweiler commented on packages/serverless-logic-web-tools/src/i18n/locales/de.ts
> +              runFollowingCommand: `Run the following command on a Terminal tab to start ${de_common.names.extendedServices} on a different port:`,
Missing translation

2023-06-20 18:38 UTC, martinweiler commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/resources/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants_de.properties
> +MarshallingResponsePopup.MessageTableColumnName=Message
Missing translation

2023-06-20 18:40 UTC, martinweiler commented on packages/serverless-workflow-diagram-editor/kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/client/resources/i18n/KieWorkbenchWidgetsConstants_de.properties
> +KSessionSelectorViewImpl.KnowledgeBase=KIE Basis
Maybe leave it as "Kie Base"

2023-06-20 18:43 UTC, martinweiler commented on packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/client/resources/i18n/KieWorkbenchWidgetsConstants_de.properties
> +KSessionSelectorViewImpl.KnowledgeBase=KIE Basis
keep as "Kie Base"?

2023-06-20 18:43 UTC, martinweiler commented on packages/stunner-editors/uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/resources/org/uberfire/ext/editor/commons/client/resources/i18n/Constants_de.properties
> +HtmlEditorView.SwitchView=SAnsicht wechseln
Typo

2023-06-20 18:44 UTC, martinweiler commented on packages/serverless-workflow-diagram-editor/uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/resources/org/uberfire/ext/editor/commons/client/resources/i18n/Constants_de.properties
> +HtmlEditorView.SwitchView=SAnsicht wechseln
Typo

2023-06-20 18:46 UTC, martinweiler commented on packages/form-dmn/src/i18n/locales/de.ts
> +    yearsAndMonthsError: "should match format P1Y(ears)2M(onths)",
Missing translation

2023-06-20 18:52 UTC, martinweiler requested changes
Great translation @mariokorte - I just found some minor issues and a few missing translations.

2023-06-20 18:58 UTC, mariokorte commented
@martinweiler thanks for your feedback. I will add the missing translations and apply your comments tomorrow.
There are one or two properties where I’m not 100% sure about the context, but if questions remain I will get back to you.

2023-06-21 06:58 UTC, mariokorte commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/resources/org/kie/workbench/common/stunner/client/widgets/resources/i18n/StunnerWidgetsConstants_de.properties
> +MarshallingResponsePopup.MessageTableColumnName=Message
I've translated 'Message' with 'Nachricht', but I would like to keep 'Level' as is intentionally. This is something a German understands fine and I'm not sure if 'Stufe' would be a better translation here.

2023-06-21 07:06 UTC, mariokorte commented
@martinweiler I have incorporated your comments into the code. I would be happy if the requirements for the merge are met. If there are still wishes or further requirements I will be happy to help.

2023-06-21 17:00 UTC, martinweiler approved these changes
LGTM @mariokorte - thanks for your contribution and the excellent translation!

2023-06-21 19:14 UTC, mariokorte commented
CI :: Code formatting run failed due to a syntax error (a superfluous bracket).
I have fixed the error, so hopefully the next run will succeed.

2023-06-22 06:11 UTC, mariokorte commented
- fixed build error
- ran prettier to satisfy code format warnings

2023-06-22 07:01 UTC, mariokorte commented
Some missing counteractions to the code formatting problems hid in another development branch of mine that needed to be included in this PR. Sorry.

Now it 'really' should meet the code formatting requirements.

2023-06-22 09:24 UTC, mariokorte commented
@tiagobento Checks have passed now and @martinweiler's remarks have been included. I guess this is ready for review to be merged.

2023-06-22 09:49 UTC, yesamer approved these changes
Thank you for your contribution, @mariokorte !

2023-06-23 14:24 UTC, merged