kie-issues#344: DMN Editor: Name and Data type popover menu visual misalignments in form labels
apache/incubator-kie-tools pull request #1746
Opened 2023-06-14 08:36 UTC by jomarko

This PR closes kiegroup/kie-issues#344

This PR contains these changes:
- fix of conflict in 'center' alignment for all 'th' header elements with needed 'left' alignment for popovers, that are child of 'th' header elements
- some css cleanup according to the sonarqube report, basically merging of rules with same selectors

2023-06-14 09:18 UTC, jomarko commented on packages/boxed-expression-component/src/contextMenu/PopoverMenu/PopoverMenu.css
> +  text-align: left;
Main fix related to **Name** and **Data Type** popover

2023-06-14 09:19 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.css
> -}
Exactly the same set in BeeTable.css

2023-06-14 09:21 UTC, jomarko commented on packages/boxed-expression-component/src/expressions/ExpressionDefinitionRoot/ExpressionDefinitionLogicTypeSelector/ExpressionDefinitionLogicTypeSelector.css
> +  text-align: left;
Without this, nested selected logic indicator is centered
![Screenshot 2023-06-14 112033](https://github.com/kiegroup/kie-tools/assets/8044780/3c336c8b-4e9c-48eb-9c0a-5be04d744519)

2023-06-14 09:21 UTC, jomarko commented on packages/boxed-expression-component/src/table/BeeTable/BeeTable.css
> -}
`row-index-cell-column` class doesn't exist

2023-06-14 14:14 UTC, yesamer approved these changes

2023-06-14 14:21 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.css
> -}
This is just you removing a duplication or removing this actually fixes/changes something?

2023-06-14 14:30 UTC, tiagobento requested changes
Thanks @jomarko! Please see the comments.

2023-06-14 14:30 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTable.css
> +
Ok, I get what you're trying to do here by unifying all logic related to an element in one single CSS block. Please don't do this, as sometimes different places will add different stuff to the same element. In this case, everything is on the same file, but there's a part handling the borders, and another one handling the alignment. Can you please revert it?

2023-06-14 14:30 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.css
> -}
Oh, okay, you're removing it because it's the same color. Please don't do that. This rule is specific for Decision Tables, and not at all coupled with whatever color BeeTable.css declares. We should be making components independent and reducing coupling. Not the other way around.

2023-06-14 14:30 UTC, tiagobento commented on packages/boxed-expression-component/src/table/BeeTable/BeeTable.css
>  }
Can you please explain this change?

2023-06-15 17:01 UTC, tiagobento approved these changes

2023-06-15 17:01 UTC, merged