KOGITO-9389: Support query params in dashbuilder datasets
apache/incubator-kie-tools pull request #1753
Opened 2023-06-14 20:26 UTC by jesuino

Adding the support to safe query parameters in datasets.

Before this we had to encode and manually build the URL, with this new change parameters are now safely encoded and declared:

```
    - uuid: GPU by Day
      type: prometheus
      url: ${dataset_url}
      cacheEnabled: true
      query:
        query: >-
            sum(
              (increase(kepler_container_gpu_joules_total[1h])
                *${watt_per_second_to_kWh}
              ) *
              (count_over_time(kepler_container_gpu_joules_total[24h])/
                count_over_time(kepler_container_gpu_joules_total[1h])
              )
            )${time_window}
```

2023-06-14 21:49 UTC, ederign requested changes

2023-06-14 21:49 UTC, ederign commented on packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
> +        try {
Can we do this check without a try catch?

2023-06-15 17:33 UTC, jesuino commented on packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
> +        try {
We can do this, but I may forget some case and wrongly build URLs (e.g. forget to cover some protocol other than HTTP). Should I try or keep the try/catch, wdyt?

2023-06-16 14:41 UTC, ederign commented on packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
> +        try {
let's keep it for now!

2023-06-16 14:41 UTC, ederign approved these changes

2023-06-16 15:57 UTC, caponetto approved these changes

2023-06-16 15:57 UTC, merged