KOGITO-9202: SWF Editor - Inline editing text
apache/incubator-kie-tools pull request #1779
Opened 2023-06-20 14:35 UTC by hasys

Hello @LuboTerifaj, @romartin,

there is a fix for inline editing. As we discussed I kept the addition Text widget and just overrided some Title methods to be aligned with the Title logic for edit mode. Also I fixed alignments so now it is centered much better and change it's vertical position if name is multiline as well.

NOTE: you need to enable edit mode manually in the code, recompile whole editor and run `mvn gwt:run` in the test app folder to test main change.

2023-06-22 14:52 UTC, hasys commented
Hello @romartin, @LuboTerifaj,

I removed one test, it is too hard mocked and not testing what it is suppose to test. I will replace it with Selenium test as part of https://issues.redhat.com/browse/KOGITO-9446 Does it make sense to you?

2023-06-27 20:21 UTC, romartin reviewed
Hey @hasys 

Code look good in general, thanks!! 

On the other hand, take a look at my comment below, I think we can do better here.

Let's keep in touch

2023-06-27 20:21 UTC, romartin commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/StateShapeView.java
> +        super.setTitleAlpha(0);
I am not sure about this, it looks we are now masking the core logic for handling titles. I am agree on dropping the core stuff, and make it domain specific, as other shapes, but in that case, I think we should try to drop legacy code then.  

Anyway, as you told me it is not easy, I am trying to help for a little while, I am now analyzing how hard is to drop core stuff for title. Will let you know something ASAP.

2023-06-27 21:27 UTC, romartin requested changes
Hey @hasys 

Code looks good, and works nice! Anyway, as commented above, let's just try to drop the core title functionality as we'll no longer use it .Also I prefer to move this logic to domain specific when building shapes, and reduce the core as well.

This way, I did a local test, see this commit, on top of your stuff here:
https://github.com/romartin/kie-tools/commit/f826d34bf14275b15edaa989ca99de3c5a068cc8

- In the commit I just reduced the title scope only to the shape targeting states . No need to have start/end titles there, also because the inline edit is not working.
- Also I created a new base class `StunnerWiresShapeView` , which drops all the references in the core to title stuff. This way title handling is delegate to super types.
- Pending Action -> Finally added a few TODO's for you, as I think we can still then drop all the classes form the `ext/` package, as they are no longer used. Maybe the core has still some references, but I think it should be not hard to drop all that legacy logic. Can you please try to do it?

So can you please cherry-pick my commit, do the pending action requrested, give a try and update the PR please? WDYT?

Thanks in advnace!

2023-06-28 15:45 UTC, hasys commented
Hey @romartin, great points, thank you!

Almost finished the only remaining thing for now is Edit Div. But I think it will be fine, will continue my work on it. Thank you!

2023-06-30 13:33 UTC, hasys commented
Hello @romartin,

PR is green again. All shape related EXT files removed and also changed logic of Edit DIV. Now it is not calculating the position of the Edit DIV but just taking coordinates and size of the Text from the shape itself so I also removed related tests as well.

Now PR is fully ready and not depends on [KOGITO-9446](https://issues.redhat.com/browse/KOGITO-9446) since the logic itself is removed.

Thank you!

2023-07-07 13:20 UTC, LuboTerifaj requested changes
Hello @hasys ,

Please see my suggestions regarding code.

Other than that, the changes work as expected.

Thanks!

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +            editorBoxHeight = zoomFactor * (hasTitle.getTextboxHeight() - 10);
From the code, it is not clear why it is necessary to reduce the TextboxHeight by 10. Maybe it would be worth moving the number to a constant.

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +            getTextEditorBox().setFontSize((hasTitle.getTitleFontSize() * zoomFactor) * 4 / 3);
From the code, it is not clear why it is necessary to adjust the FontSize by 4/3. Maybe it would be worth moving the expression to a constant.

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java
> +        when(hasTitle.getTitlePosition()) .thenReturn(titlePosition);
```suggestion
        when(hasTitle.getTitlePosition()).thenReturn(titlePosition);
```

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java
> +        verify(textEditorBox).setFontSize(FONT_SIZE / 3 * 4);
`FONT_SIZE / 3 * 4` could be moved to a constant.

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/StateShapeView.java
> +                .setX(LABEL_POSITION_X)
```suggestion
                .setX(LABEL_POSITION_X)
                .setY(LABEL_POSITION_Y)
```

2023-07-07 13:20 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/StateShapeView.java
> +        title.setY(40 - title.getBoundingBox().getHeight() / 2);
The parameter could be moved to a separate method with appropriate name to reflect what this value represent.

2023-07-10 13:13 UTC, romartin approved these changes
Thanks @hasys , looks great!!

2023-07-18 09:37 UTC, hasys commented
Hello, @LuboTerifaj,

all issues addressed, thank you! Just one note, I rebased the PR to the master and now it is not updating the name in the text editor anymore (only on the canvas in the diagram). It was caused by recent clean up and will be fixed in the following jiras by @handreyrc.

For now you can check that model is changed using browser console. In the editorFrame you can using following commands before and after changing the name of the node on the canvas:

```javascript
var session = window.frames.frames.editor.session;
canvas.getNodeIds();
session.getNodeByName('Inject State') === session.getNodeByUUID('_AAD182B5-DAEB-442F-A332-F04F41188CA1');
```

2023-07-26 10:33 UTC, LuboTerifaj reviewed
Hello @hasys , I have a few inline comments. Please have a look. Thanks!

2023-07-26 10:33 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +    private int EDIT_TEXBOX_BOTTOM_PADDING = 10;
```suggestion
    private int EDIT_TEXTBOX_BOTTOM_PADDING = 10;
```

2023-07-26 10:33 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +            editorBoxHeight = zoomFactor * (hasTitle.getTextboxHeight() - EDIT_TEXBOX_BOTTOM_PADDING);
```suggestion
            editorBoxHeight = zoomFactor * (hasTitle.getTextboxHeight() - EDIT_TEXTBOX_BOTTOM_PADDING);
```

2023-07-26 10:33 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +    private double ptToPx(double value) {
Would it be possible to provide more context here?

2023-07-26 10:33 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java
> +    private double ptToPx(double pt) {
Missing context here as well.

2023-07-26 11:52 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControl.java
> +    private double ptToPx(double value) {
Feel free to keep it as it is, although it would be worth documenting the expected format of parameters that use `pt` or `px` in classes and interfaces. Ideally to unify used units. Of course, it is not the requirement for this PR.

2023-07-26 11:52 UTC, LuboTerifaj commented on packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/controls/inlineeditor/AbstractCanvasInlineTextEditorControlTest.java
> +    private double ptToPx(double pt) {
Feel free to keep it as it is, although it would be worth documenting the expected format of parameters that use `pt` or `px` in classes and interfaces. Ideally to unify used units. Of course, it is not the requirement for this PR.

2023-07-26 11:53 UTC, LuboTerifaj approved these changes
It looks good to me now. Thanks!

2023-07-27 11:35 UTC, LuboTerifaj commented
The build failed with incompatible Chrome and ChromeDriver versions. I opened the pull-request with the fix: https://github.com/kiegroup/kie-tools/pull/1875.

2023-07-27 14:02 UTC, romartin commented
Hey @hasys , please let me know when this is ready to merge, thanks!

2023-07-28 14:50 UTC, merged