kie-issues#398: Implement flag to allow self-signed certificates when using CORS Proxy for Git requests
apache/incubator-kie-tools pull request #1905
Opened 2023-08-07 12:29 UTC by thiagoelg

2023-08-07 20:41 UTC, tiagobento requested changes
Wow! This PR is awesome. This was no easy task, and you nailed it. I left some minor comments inline, please consider them. Congratulations for the thoroughness and attention to detail. I bet you're tired of typing  the `insecurelyDisableTlsCertificateValidation` string 😝

2023-08-07 20:41 UTC, tiagobento commented on packages/cors-proxy/src/proxy/server.ts
> +  app.disable("x-powered-by");
👍

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/build/defaultEnvJson.ts
> +    }
This needs to be removed, right? In any case, I think it would be good to have a guide somewhere (on a `.md` file) explaning how to configure and use a local Git instance with self-signed certificate, for testing and validation purposes.

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/accounts/git/ConnectToGitSection.tsx
> +      ...(insecurelyDisableTlsCertificateValidation ? INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION_HEADERS : {}),
Why is `INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION_HEADERS` only used here? Shouldn't it be used for GitHub requests too?

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/authSessions/AuthSessionsContext.tsx
> +              const authProvider = authProviders.find(({ id }) => id === authSession.authProviderId) as GitAuthProvider;
Although we know this to be true, there's no hard guarantee on the type system that this will be the case. In this scenario, I prefer to throw an exception if `authProvider` is not a GitAuthProvider. WDYT?

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/bitbucket/Hooks.tsx
> +    return `${proxyUrl ? `${proxyUrl}/` : "https://"}api.${this.domain}/2.0`;
This template string with ternary is kind of complicated to read. Can you please give it some extra love? :D

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/editor/Toolbar/GitIntegration/GitIntegrationContextProvider.tsx
>      }
This is to include the port, right?

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/editor/Toolbar/GitIntegration/GitIntegrationContextProvider.tsx
> +  }, [authProvider, props.workspace]);
So... in summary, we only use the flag saved on the Workspace descriptor if there's no AuthProvider associated with the Workspace? I.e., "Unauthenticated"?

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/github/Hooks.tsx
> +    baseUrl: args.domain === "proxy.testing:9091" ? "proxy.testing:9092" : getGithubInstanceApiUrl(args.domain),
This feels like something to be removed too, right?

2023-08-07 20:41 UTC, tiagobento commented on packages/online-editor/src/importFromUrl/ImportFromUrlHomePageCard.tsx
> +      }
```suggestion
      if (newAuthSession?.type === "git") {
        const localAuthProvider = authProviders.find((provider) => provider.id === newAuthSession.authProviderId);
        if (localAuthProvider?.group === AuthProviderGroup.GIT) {
          setInsecurelyDisableTlsCertificateValidation(
            localAuthProvider.insecurelyDisableTlsCertificateValidation ?? false
          );
        }
      }
```

^ Isn't it the same? It looks cleaner to me...

2023-08-07 20:41 UTC, tiagobento commented on packages/workspaces-git-fs/src/services/GitService.tsx
> +const INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION = "insecurely-disable-tls-certificate-validation";
Ok, so this is duplicated, and this constant doesn't have a very good name, let's say :D 

Or even more than duplicated, as this name is listed at `cors-proxy` too.

If we think about it, this name is owned by the `cors-proxy` package. Since we don't want `online-editor` and `worksapces-git-fs` to depend on `cors-proxy`, my suggestion is that we create a new package called `cors-proxy-api`, and export a this value from there. A lot for a single package, I know, but also sets a standard for dealing with this kind of "soft" dependency between packages. WDYT?

2023-08-11 20:23 UTC, thiagoelg commented on packages/online-editor/src/accounts/git/ConnectToGitSection.tsx
> +      ...(insecurelyDisableTlsCertificateValidation ? INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION_HEADERS : {}),
It is but in a different place (when creating the Octokit client). I've updated this to be more concise.

2023-08-11 20:24 UTC, thiagoelg commented on packages/online-editor/src/authSessions/AuthSessionsContext.tsx
> +              const authProvider = authProviders.find(({ id }) => id === authSession.authProviderId) as GitAuthProvider;
Fixed by adding a new type guard and improving the current type checks.

2023-08-11 20:24 UTC, thiagoelg commented on packages/online-editor/src/editor/Toolbar/GitIntegration/GitIntegrationContextProvider.tsx
>      }
Yes

2023-08-11 20:25 UTC, thiagoelg commented on packages/online-editor/src/editor/Toolbar/GitIntegration/GitIntegrationContextProvider.tsx
> +  }, [authProvider, props.workspace]);
Yes, but now that I'm thinking about it, should this be an "OR" comparison? AuthProvider flag OR Workspace flag?

2023-08-11 20:27 UTC, thiagoelg commented on packages/workspaces-git-fs/src/services/GitService.tsx
> +const INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION = "insecurely-disable-tls-certificate-validation";
I would go further and create a `cors-proxy-client` package, that would work as a drop-in replacement for `fetch`, what do you think?

2023-08-11 21:25 UTC, tiagobento commented on packages/online-editor/src/editor/Toolbar/GitIntegration/GitIntegrationContextProvider.tsx
> +  }, [authProvider, props.workspace]);
Good question. I think the `or` makes more sense.. But I didn't spend a lot of time thinking about it...

2023-08-11 21:28 UTC, tiagobento commented on packages/workspaces-git-fs/src/services/GitService.tsx
> +const INSECURELY_DISABLE_TLS_CERTIFICATE_VALIDATION = "insecurely-disable-tls-certificate-validation";
I'm usually not a big fan of "client" packages that "dictate" how the communication with something should be done. I understand that the idea is to make it easier for consumers, but I tend to feel like sometimes callers need a little more control over how the communication is done... Idk, I'm very careful when creating abstractions, but if you feel like we would benefit from this "client" package, go for it.

2023-08-18 23:13 UTC, tiagobento approved these changes

2023-08-18 23:13 UTC, merged

2023-08-23 12:48 UTC, zdrapela commented
Hi @thiagoelg, 
Thank you for the fix. Unfortunately, it looks broken again as mentioned in https://github.com/lima-vm/lima/issues/1742. I noticed that PR checks started to fail (e.g. https://github.com/kiegroup/kie-tools/pull/1926). Could you please take a look again at how it can be fixed? Thanks in advance!

2023-08-23 14:34 UTC, zdrapela commented
> Hi @thiagoelg, Thank you for this. Unfortunately, it looks QEMU is broken again as mentioned in [lima-vm/lima#1742](https://github.com/lima-vm/lima/issues/1742). I noticed that PR checks started to fail (e.g. #1926). Could you please take a look again at how it can be fixed? Thanks in advance!

Well, you can ignore my previous comment. I figured out that the third workaround mentioned in https://github.com/lima-vm/lima/issues/1742 and will be opening PR for the fix soon.

2023-08-23 15:01 UTC, thiagoelg commented
Thanks @zdrapela! Feel free to let me know if I can help with anything.

This issue kind of sucks and there's not much we can do about it beyond applying these workarounds and waiting for an official fix. :confused: