KOGITO-2303: Use vscode-extension-tester to test VSCode channel
apache/incubator-kie-tools pull request #191
Opened 2020-06-24 10:05 UTC by domhanak

TODO: General refactor to multiple files, fix some dependencies I added by mistake

Ready for initial feedback and comments, I am working on refactoring this in the meantime so any comments will be incorporated to into it.

2020-06-24 10:25 UTC, domhanak commented
Tests are failing now as new version of VSCode was released and the editors are not loading properly.

2020-06-29 13:52 UTC, tiagobento reviewed
Hi @domhanak! I started taking a look at this PR, although I know you said it's still WIP.

A few remarks from my side:

1. Do we really need `chai` to make assertions? I'd like to keep `jest` as the default test execution framework for us, we can do assertions using `expect`.
2. Please don't declare types where they're not needed. Although it looks like it's more "explicit", it's not idiomatic on TypeScript. (soon will not be in Java too, with `var`)
3. Please configure Prettier on your IDE, it's our code formatter.
4. I noticed some changes on the `tsconfig.json`. Ideally I don't see why we should change anything there, rather we should make sure that the configuration files you're adding to run the tests etc work in the current build configuration. I'm not saying we *can't* change it, but if we do need to, please comment on why.

2020-09-16 18:56 UTC, caponetto reviewed
Hi @domhanak, thanks for the PR!
I've left some comments, please check if they make sense.
Also, there are some conflicts that need to be resolved before merging this PR.

+1 for Tiago's comments.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/demo.dmn
> +
Is it supposed to be empty?

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +import { EditorView, WebView, ExtensionsViewItem, By, WebElement } from 'vscode-extension-tester';
Please add the copyright header to all source files.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			item = await marketplace.findExtension(`@installed ${pjson.displayName}`) as ExtensionsViewItem;
Shouldn't this code run inside `beforeAll`?

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			this.timeout(10000);
Where does `this.timeout` come from? I guess I'm missing something here.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +		before(async function () {
Consider using an arrow function here (and in the other applicable places below) just like you did on line 24.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			await new EditorView().closeAllEditors();
Can we have only one instance of EditorView? It is being created five times on this file.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			assert.isTrue(await explorer.findElement(By.xpath(aComponentWithText('End'))).isDisplayed());
Consider rearranging the code of this test using the AAA pattern. IMO it'd improve the organization.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +		})
The code inside `before` and `after` is almost identical to the previous test `BPMN Editor is loading`.
So consider creating reusable methods to avoid code duplication.

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +	describe("BPMM Editor is loading", () => {
```suggestion
	describe("BPMN Editor is loading", () => {
```

2020-09-16 18:56 UTC, caponetto commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +});
Are we gonna have similar tests for `scesim` on this PR?

2020-09-22 07:18 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			item = await marketplace.findExtension(`@installed ${pjson.displayName}`) as ExtensionsViewItem;
This test that we can find the extension in marketplace and it installs without problems. I can move it, but the idea is to check general naming & presence & apperance on marketplace

2020-09-22 07:19 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +			this.timeout(10000);
This wiil be updated

2020-09-22 07:20 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +});
@caponetto Yes,  I ll add them, there wasn't scesim when I started this.
I ll ping you when ready! :)

2020-10-07 10:38 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-marketplace.test.ts
> +		before(async function () {
I would like to have a control of timeout of each test case, the operations may wary and some tasks need more time than others.

2020-11-10 11:13 UTC, domhanak commented
Couple of small refactors and improvements is missing, but overall it is ready for the next round of review. Please let me know @caponetto @paulovmr 

tsconfig.json updates will be reverted.

2020-11-16 13:32 UTC, tiagobento requested changes
Thanks @domhanak! This is looking great! Please consider my comments inline. After you revert the changes on tsconfig.json, we should be good to go! Nice work!

2020-11-16 13:32 UTC, tiagobento commented on package.json
> +    "@types/enzyme": "3.10.0",
Do we need enzyme?

2020-11-16 13:32 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/VSCodeTestHelper.ts
> +        await DefaultWait.sleep(10000);
This seems to be the only usage we have of `vscode-uitests-tooling`. Looks to me that it's just a Promise being resolved after a setTimeout executes.. can we refactor that to remove the dependency with `vscode-uitests-tooling`?

2020-11-19 09:57 UTC, domhanak commented on package.json
> +    "@types/enzyme": "3.10.0",
i double check, thanks

2020-11-19 09:59 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/VSCodeTestHelper.ts
> +        await DefaultWait.sleep(10000);
Well we will definitely use more functionalities from that package, the package is a collection of extra functionalities on top of vscode-extension-tester.

2020-11-25 10:31 UTC, domhanak commented
@tiagobento Ready now, I kept two settings in tsconfig of vscode's package.
`--resolveJsonModule` to allow imports of json file, very usefull when we want to introduce tests to verify that the extension name is same in marketplace as in package.json
`outDir` to make sure that the outputed JS files are in one place and dont pollute the workspace

This is now ready for merging if you approve, I have couple of new tests cases in progress along with some code improvements and refactors coming after this.
For example, save operation, service tasks, backend notification tests.

2020-11-25 11:42 UTC, caponetto commented
Hi @domhanak, can you please add the copyright header to the source files?

2020-11-25 13:53 UTC, domhanak commented
@caponetto Done, how do I rerun the builds?

2020-11-25 14:03 UTC, caponetto commented
Thanks, @domhanak! I just re-run them.

2020-11-27 13:46 UTC, tiagobento commented
@domhanak Regular CI is failing, can you please check that?

2020-12-01 12:25 UTC, domhanak commented
@tiagobento I checked, seems like an instability. I couldn't reproduce on subsequent runs locally, and next build succeeded.
I rebased on master and squashed the commits. Let me know if we can merge.

2020-12-02 09:59 UTC, domhanak commented
FDB failed on an issue with integration tests, not related to this PR.

2020-12-02 11:09 UTC, caponetto approved these changes
LGTM

2020-12-02 12:49 UTC, tiagobento commented
@tomasdavidorg That's a different error from the ones we've seen before. Do you mind checking it out?

2020-12-02 13:33 UTC, tomasdavidorg commented
> @tomasdavidorg That's a different error from the ones we've seen before. Do you mind checking it out?

I will take a look. Looks like the driver was not created / Chrome was not initialized. It is not related to this PR.

2020-12-04 06:00 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +	const DEMO_BPMN: string = 'demo.bpmn';
```suggestion
    const DEMO_BPMN: string = 'demo.bpmn';
```

2020-12-04 06:00 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +        this.timeout(60000);
Why do you use these fixed timeouts? Isn't there a way to have some dynamic waiting?

2020-12-04 06:00 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +describe("Editors are loading properly", () => {
I think we are mixing two styles of defining functions. 

1. `function () {}`
2. `() => {}`

Not sure which is the better one but we should probably use one way? Wdyt?

2020-12-04 08:22 UTC, jomarko reviewed
Tests looks good to me. Just few questions. Good job @domhanak

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +    }
This method seems to be unused. Is it intentional?

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
Small typo here I think

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
Small typo here I think

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/CommonAsserts.ts
> +    assert.isTrue(await tested.isDisplayed() && await tested.isEnabled());
Is it intentional to omit `return` keyword when we return `Promise<void>`?

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/DmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
small typo

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/ScesimEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
small typo

2020-12-04 08:22 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/incident-response.bpmn2
> +<?xml version="1.0" encoding="UTF-8"?>
is this file used in some test?

2020-12-04 08:50 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/CommonAsserts.ts
> +    assert.isTrue(await tested.isDisplayed() && await tested.isEnabled());
That should be correct. When you have `async` function returning void then the return type is `Promise<void>`.

2020-12-04 08:52 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/CommonAsserts.ts
> +    assert.isTrue(await tested.isDisplayed() && await tested.isEnabled());
ok, thank you

2020-12-07 13:49 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +        this.timeout(60000);
This is not dynamic waiting, it just sets the timeout for this function to 60s. If the `before()` setup does not complete in 60s the test fails.

2020-12-07 13:50 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
What do you mean `a <h3> element`?

2020-12-07 13:55 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +describe("Editors are loading properly", () => {
1. binds `this` to the method itself not to the context. Used  to control timeout per method/test. For example in `before` `after`.
Not sure what is the go-to option. There a pros/cons for both approaches so I would probably let it be this time and do a meeting to discuss this.

2020-12-07 13:59 UTC, domhanak commented
Build failed on mac that couldn't download the dependencies... @caponetto How do I re-run the jobs myself? Is there something like `jenkins retest this` ?

2020-12-07 14:06 UTC, caponetto commented
@domhanak There's a button to re-run the jobs but I think only available for users with write permission in the repository.
I'll re-run for you but one workaround for re-running it whenever you want would be force pushing a new commit hash, like:
`git commit --amend --no-edit && git push -f <remove> <branch>`

2020-12-07 14:11 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +        this.timeout(60000);
:man_facepalming: Sorry. :smile:

2020-12-07 14:13 UTC, tomasdavidorg commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
I think @jomarko had in mind `propert` to `proper`.

2020-12-07 14:34 UTC, domhanak commented
@caponetto that is not very user-friendly, but I wil ltry it. The approach could be made less strict so that at least the creator of PR could re trigger the build. Anyway, `macos-lastest` failed again with same issue, fail during dependencies download.

2020-12-07 14:44 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
> +     * Verifies there is a <h3> element with propert text.
@tomasdavidorg yes. @domhanak sorry I was not clear.

2020-12-07 14:52 UTC, tiagobento commented
@domhanak `macos-latest` failing to download the dependencies sometimes is a known issue. There's no workaround for that at the moment :/ Also, GitHub has not yet made it possible for the owners of the PR to re-run a workflow. When GH Actions was launched, re-running was not possible even for admins, so we also had to use this trick of pushing an empty commit :)

2020-12-08 10:06 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +	const DEMO_BPMN: string = 'demo.bpmn';
Not sure why but I see this as fixed locally :confused:

2020-12-10 12:16 UTC, domhanak commented
green, let's merge if all good. @tiagobento

2020-12-10 12:37 UTC, tiagobento approved these changes

2020-12-10 13:11 UTC, tomasdavidorg approved these changes

2020-12-10 13:55 UTC, jomarko approved these changes

2020-12-11 13:44 UTC, merged