KOGITO-2534 Online editor is not loaded after Open in Online Editor button is clicked
apache/incubator-kie-tools pull request #194
Opened 2020-06-24 19:46 UTC by ljmotta

This PR fixes https://issues.redhat.com/browse/KOGITO-2534

2020-06-24 19:50 UTC, tiagobento approved these changes

2020-06-25 04:59 UTC, tomasdavidorg requested changes

2020-06-25 04:59 UTC, tomasdavidorg commented on packages/chrome-extension-pack-kogito-kie-editors/src/background.ts
> +          filePath: removeDirectories(request.filePath),
Could you please remove `removeFileExtension` from import as there is no other usage in this file.

2020-06-25 11:36 UTC, jomarko approved these changes
Please incorporate @tomasdavidorg change request before merge. Otherwise looks fine.

2020-06-25 15:39 UTC, ljmotta commented on packages/chrome-extension-pack-kogito-kie-editors/src/background.ts
> +          filePath: removeDirectories(request.filePath),
Done.

2020-06-25 16:02 UTC, ederign approved these changes

2020-06-25 16:02 UTC, merged