KOGITO-2601: Move State Control API to `kie-bc-editors`
apache/incubator-kie-tools pull request #200
Opened 2020-06-30 21:47 UTC by tiagobento

See https://issues.redhat.com/browse/KOGITO-2601

Related PRs:

2020-07-01 11:27 UTC, caponetto reviewed
Awesome! Thanks @tiagobento. I've left only a couple of questions.

2020-07-01 11:27 UTC, caponetto commented on packages/microeditor-envelope/src/EditorFactory.ts
> +    languageData1: LanguageData,
Is there a reason to append this `1` on the name? `languageData1`

2020-07-01 11:27 UTC, caponetto commented on packages/microeditor-envelope/src/EditorEnvelopeView.tsx
> +        this.getEditor()!.redo();
Is there a chance of editor being `undefined` here? (and also on the change below)

2020-07-01 11:27 UTC, caponetto commented on packages/core-api/src/appformer/Editor.ts
> +  public abstract redo(): Promise<void>;
:heart_eyes:

2020-07-01 12:27 UTC, tiagobento commented on packages/microeditor-envelope/src/EditorFactory.ts
> +    languageData1: LanguageData,
Not at all 😅. Changed.

2020-07-01 12:29 UTC, tiagobento commented on packages/microeditor-envelope/src/EditorEnvelopeView.tsx
> +        this.getEditor()!.redo();
Well... theoretically yes, but I didn't wanna clutter the code with a check an all that, so I simply left it like that and we'll have an exception be raised in the case we don't have an editor there for some reason. I'm open to suggestions on how to handle that! Best thing I could think of was a nice `console.error` but I didn't think that justifies 3 more lines of code.

2020-07-01 13:32 UTC, caponetto commented on packages/microeditor-envelope/src/EditorEnvelopeView.tsx
> +        this.getEditor()!.redo();
+1

2020-07-01 13:33 UTC, caponetto approved these changes

2020-07-08 11:41 UTC, jomarko requested changes
One question to code.

Next it probably break DMN Guided Tour https://issues.redhat.com/browse/KOGITO-764 because I am getting this screen after opening a DMN file.

There is missing error flash message  '... can not read "cookie"...' - was not able to capture it.

![Screenshot from 2020-07-08 13-16-45](https://user-images.githubusercontent.com/8044780/86914457-b059a280-c120-11ea-8498-578c92b9c131.png)

2020-07-08 11:41 UTC, jomarko commented on packages/kie-bc-editors/src/gwtStateControl/GwtCommandRegistry.ts
> +export interface GwtCommandRegistry<T> {
Shouldn't we rename also corresponding `org.appformer.kogito.bridge.client.stateControl.registry.impl.KogitoCommandRegistry` ?

2020-07-08 14:45 UTC, tiagobento commented on packages/kie-bc-editors/src/gwtStateControl/GwtCommandRegistry.ts
> +export interface GwtCommandRegistry<T> {
I think I prefer reverting it to `KogitoCommandRegistry` if that's okay.

2020-07-08 14:46 UTC, tiagobento commented
@jomarko Thanks for testing. I'll upload a new VSIX, since this one was out of date. This bug with the cookie thing was fixed here #202. I'll let you know when a new VSIX is uploaded.

2020-07-08 15:20 UTC, tiagobento commented
@jomarko VSIX updated. Please download it here: https://drive.google.com/file/d/1A0d6HvxhqPz0ksbwJfsfANG4uwkRSDS3/view?usp=sharing

2020-07-09 07:26 UTC, jomarko approved these changes
thank you @tiagobento attached vsix works ok.

2020-07-09 13:55 UTC, paulovmr approved these changes

2020-07-09 14:06 UTC, merged