KOGITO-1883: Improving pattern management for ResourceContentAPI to support Win enviroments.
apache/incubator-kie-tools pull request #203
Opened 2020-07-03 12:34 UTC by yesamer

/* DRAFT */

2020-07-03 14:27 UTC, tiagobento requested changes
Thanks for the PR @yesamer. Minor questions inline! Also, can you please configure Prettier on your IDE? I noticed that there are formatting issues.

2020-07-03 14:27 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
Can you rename that to `workspaceFolderPath`?
Also, what happens if `vscode.workspace` is undefined?

2020-07-03 14:27 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const includingRelativePattern = new RelativePattern(basePath, pattern);
Why is this called `includingRelativePattern` and not `relativePattern`?

2020-07-03 14:50 UTC, yesamer commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const includingRelativePattern = new RelativePattern(basePath, pattern);
@tiagobento I chose that name because of `findFile()` method parameters: 
`export function findFiles(**include**: GlobPattern, exclude?: GlobPattern ...) `
It supports both inclusion and exclusion GLOB pattern. My scope was to underline that an inclusion GLOB is currently passed.
Anyway, considering is the only parameter passed, I can rename it as suggested.

2020-07-03 14:51 UTC, yesamer commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
@tiagobento 
1. Sure!
2. In my opinion both `workspace` and `workspaceFolder` can't be `undefined`, because the code flow is called from a file which is opened inside a VSCode workspace. Consider that here https://github.com/kiegroup/kogito-tooling/pull/203/files/4839c7af7bafe41686a366dd494f684a8b900de9#diff-d79a48ded68ac338330c5545e6f185d5R68 there is the same assumption.

2020-07-06 13:42 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
2. So, it turns out `vscode.workspace` is a namespace, meaning that it cannot indeed be `undefined`. I asked because there's a `!` there, and that's usually means that you're forcing the TS compiler to ignore that this property _can_ be `undefined`. Can you please remote the `!` there then? :D

2020-07-06 13:47 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
Now looking again at this code, I see that you're forcing the compiler to assume that `workspaceFolders` is not `undefined` and also you're assuming that it _has_ at least one element. The link you sent is just opening this PR, can you send me another one?
I'm afraid that when you open a a file without opening a folder, this code will break because `vscode.workspace.workspaceFolders` will be `undefined`, can you please check that?

2020-07-06 13:50 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
![image](https://user-images.githubusercontent.com/1584568/86600438-7056bc00-bf76-11ea-9c1a-011968eee28c.png)

2020-07-06 13:52 UTC, yesamer commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
@tiagobento Good point, I'll check this case as well. Thank you!

2020-07-08 12:55 UTC, yesamer commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
@tiagobento I double checked. Basically, it's correct to assume `vscode.workspace.workspaceFolders` is not undefined and with at least one element inside `VsCodeResourceContentService` class. The reason is inside `KogitoEditorFactory`, here https://github.com/kiegroup/kogito-tooling/pull/203/files/4839c7af7bafe41686a366dd494f684a8b900de9#diff-b162a87c3b2489e6e759295a8b2daacdL89. 
As you can see, the logic here determines which Service to instantiate: `VsCodeResourceContentService` or ``VsCodeResourceContentService` or `VsCodeNodeResourceContentService`. The first one is instantiated iff the given `path` is inside a workspaceFolder (please refer to `isAssetInWorkspace(path: string)`) method. Therefore, if `VsCodeResourceContentService` is instantiated, `vscode.workspace.workspaceFolders` but be NOT undefinied.

2020-07-08 16:45 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    const workspaceFolder = vscode.workspace!.workspaceFolders![0].uri.fsPath + nodePath.sep;
Thanks @yesamer, that makes sense.

2020-07-08 16:45 UTC, tiagobento approved these changes

2020-07-16 01:30 UTC, tiagobento commented
@jstastny-cz Can you please take a look at this PR when you have time?

2020-07-24 13:36 UTC, tiagobento commented
@jstastny-cz @jomarko Hi guys, is some of you available to look at this PR? Should I tag someone else?

2020-07-30 15:47 UTC, ederign approved these changes

2020-07-30 15:48 UTC, merged