kie-issues#633: Change the Extended Services Go App for the new Extended Services Java in the Extended Services Images
apache/incubator-kie-tools pull request #2031
Opened 2023-10-30 16:31 UTC by Josephblt

Fixes https://github.com/apache/incubator-kie-issues/issues/633.

Unnecessary information in the Extended-Services-Java app Ping Endpoint was removed.
Extended-Services-Image now uses the Extended-Services-Java app.

2023-10-30 16:58 UTC, gitgabrio requested changes
Thanks a lot @Josephblt for this PR!
What I would ask you is to avoid  all that variable/file/directory renaming that only adds a lot of instability, creates issues on consumer environments (i.e. ci), and reflect an implementation detail that should not have any impact on the above naming.

2023-10-30 16:58 UTC, gitgabrio commented on packages/extended-services-java/env/index.js
> +    EXTENDED_SERVICES_JAVA__port: {
is it needed to change the name of that variable ? It could lead to some break and, after all, the meaning/semantic is the same. If it is possible, I would prefer to not change it

2023-10-30 16:58 UTC, gitgabrio commented on packages/extended-services-java/env/index.js
> +    EXTENDED_SERVICES_JAVA__host: {
is it needed to change the name of that variable ? It could lead to some break and, after all, the meaning/semantic is the same. If it is possible, I would prefer to not change it

2023-10-30 16:58 UTC, gitgabrio commented on packages/kie-sandbox-extended-services-image/Containerfile
> +FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-11-runtime:1.16-3
Never realized before, but since this is/should be a "company-agnostic" (open-source) code, is it not strange to rely upon the "redhat" registry ?

2023-10-30 16:58 UTC, gitgabrio commented on packages/kie-sandbox-extended-services-image/package.json
> +    "copy:extended-services:linux:darwin": "cp -R ../extended-services-java/dist/extended-services-java ./dist-dev/kie_sandbox_extended_services",
See previous comments: is it needed to change the name of the `/extended-services` directory ? If not, I think it would be better to leave it unchanged - changing the names of files/directories/variables without a need only makes the code instable

2023-10-30 16:58 UTC, gitgabrio commented on packages/kie-sandbox-extended-services-image/package.json
> +    "docker:build": "kie-tools--image-builder -r \"$(build-env extendedServicesImage.registry)\" -a \"$(build-env extendedServicesImage.account)\" -n \"$(build-env extendedServicesImage.name)\" -t \"
same comment here about `extendedServicesJava`: the fact that it is a `java` implementation is an implementation detail that does not need to be exposed in the name of that variable

2023-10-30 16:58 UTC, gitgabrio commented on pnpm-lock.yaml
> +      "@kie-tools/extended-services-java":
see previous comments

2023-10-30 16:58 UTC, gitgabrio commented on repo/graph.dot
> +  "@kie-tools/kie-sandbox-extended-services-image" -> "@kie-tools/extended-services-java" [ style = "solid", color = "black" ];
see previous comments

2023-10-30 16:58 UTC, gitgabrio commented on repo/graph.json
> +        "target": "@kie-tools/extended-services-java",
see previous comments

2023-10-30 17:25 UTC, Josephblt commented on packages/extended-services-java/env/index.js
> +    EXTENDED_SERVICES_JAVA__port: {
Two things about these variables. They conflict with existing variables from the extended-services go app. Remember they still both exist. So I had to change their names.

That being said, we can consider these new variables. So, I just went ahead and matched the names to their exact function. This way we avoid unnecessary guessing. 

No need to worry about this change as it will not break anything.

2023-10-30 17:25 UTC, Josephblt commented on packages/extended-services-java/env/index.js
> +    EXTENDED_SERVICES_JAVA__host: {
Same as above.

2023-10-30 17:30 UTC, Josephblt commented on packages/kie-sandbox-extended-services-image/Containerfile
> +FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-11-runtime:1.16-3
There was a discussion about this, last week, but yeah, I'm open to suggestions. What we need here is a Linux image that has Java 11 Runtime Environment on it. 

The reason I went with that one is because it has minimal overhead, provides the right JRE, and we already used an image from that same registry.

2023-10-30 18:08 UTC, Josephblt commented on packages/kie-sandbox-extended-services-image/package.json
> +    "docker:build": "kie-tools--image-builder -r \"$(build-env extendedServicesImage.registry)\" -a \"$(build-env extendedServicesImage.account)\" -n \"$(build-env extendedServicesImage.name)\" -t \"
This is related to the above comment.

2023-10-30 18:09 UTC, Josephblt commented on pnpm-lock.yaml
> +      "@kie-tools/extended-services-java":
This here, is necessary because of the existence of both apps.

2023-10-30 18:09 UTC, Josephblt commented on repo/graph.dot
> +  "@kie-tools/kie-sandbox-extended-services-image" -> "@kie-tools/extended-services-java" [ style = "solid", color = "black" ];
Same as above.

2023-10-30 18:10 UTC, Josephblt commented on repo/graph.json
> +        "target": "@kie-tools/extended-services-java",
Same as above.

2023-10-30 18:10 UTC, Josephblt commented on packages/kie-sandbox-extended-services-image/package.json
> +    "copy:extended-services:linux:darwin": "cp -R ../extended-services-java/dist/extended-services-java ./dist-dev/kie_sandbox_extended_services",
Here again, we still have to take into account the fact that the extended-services go app still exists. To keep clarity and prevent any misidentification between the two apps I thought it was important to differentiate. I don't see how this can be a problem.

2023-10-30 19:14 UTC, tiagobento commented on packages/kie-sandbox-extended-services-image/Containerfile
> +FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-11-runtime:1.16-3
If the image we chose has a compatible license and meets out requirements, I don't see any problem this image coming from Red Hat.

2023-10-30 19:18 UTC, tiagobento commented
@gitgabrio We're gradually moving away from the Go-based Extended Services. The first step is to have a Quarkus app that does the same as it does. This was addressed on #2017. Now this PR goes a step further and changes the Extended Services used inside the Extended Services image to the new Java-based one. The Go-based one is still around, as we need it for the community production deployment at sandbox.kie.org. Once we have an environment that we can trust, we will stop offering users the possibility to download Extended Services, and we will maintain an Extended Services online for community users to use. Until we don't have this environment, we will keep both, that's why now there's the `extended-services` package, and the `extended-services-java` package. In the future, when we only have one, we can rename `extended-services-java` to `extended-services` again. For now, both will co-exist.

2023-11-08 14:58 UTC, tiagobento approved these changes

2023-11-08 14:59 UTC, merged