KOGITO-9918: Runtime tools features on Serverless Logic Web Tools - Iteration 2
apache/incubator-kie-tools pull request #2128
Opened 2024-01-22 17:40 UTC by fantonangeli

**Jira:** https://issues.redhat.com/browse/KOGITO-9918

**Description:**
Finalizing migration of Runtime-ools DevUI to kie-tools.

Many thanks @paulovmr for your help on this PR.

**How to test:**
The command `pnpm dev` will run together the local server and the local data-index server.

**Preview:**
[KOGITO-9918.webm](https://github.com/apache/incubator-kie-tools/assets/17780574/292809e2-c1ad-4513-bbda-b706219d2771)

2024-01-23 14:28 UTC, paulovmr approved these changes

2024-01-24 13:57 UTC, paulovmr requested changes
Holding the merge for a change in packages visibility.

2024-01-25 14:33 UTC, paulovmr approved these changes

2024-01-29 16:29 UTC, tiagobento approved these changes

2024-01-29 16:29 UTC, merged