kie-issues#902: Add missing images to KIE tools daily dev publish Jenkins job
apache/incubator-kie-tools pull request #2140
Opened 2024-02-02 13:07 UTC by rodrigonull

ISSUE: https://github.com/apache/incubator-kie-issues/issues/902

This PR adds the missing images to the Daily dev Jenkins Job and it also adds the missing release job triggers for these images.

2024-02-02 17:20 UTC, tiagobento requested changes
Found a typo, which I think affects the scripts...

2024-02-02 17:20 UTC, tiagobento commented on .ci/jenkins/Jenkinsfile.daily-dev-publish
> +                    hemlUtils = load '.ci/jenkins/shared-scripts/helmUtils.groovy'
Typo

2024-02-05 10:54 UTC, rodrigonull commented on .ci/jenkins/Jenkinsfile.daily-dev-publish
> +                    hemlUtils = load '.ci/jenkins/shared-scripts/helmUtils.groovy'
Fixed. Thanks!

2024-02-05 14:14 UTC, thiagoelg approved these changes

2024-02-05 16:47 UTC, tiagobento approved these changes

2024-02-05 16:48 UTC, merged