Static Validation for DMN and BPMN Editors on VS Code extensions
apache/incubator-kie-tools pull request #2165
Opened 2024-02-19 15:10 UTC by Josephblt

This closes [incubator-kie-issues/issues/469](https://github.com/apache/incubator-kie-issues/issues/469).

All functionality implemented. A new VS Code extension project was created. It is possible to validate BPMN and DMN files. You can connect to any Extended-Service or choose to locally run one.

2024-02-20 13:21 UTC, jomarko reviewed
@Josephblt hello, thank you for this new extension `extended-services-vscode-extension`.  From the ticket description it seems to be very important and useful, however I would like to ask few questions about its usage.

- Once it is installed into VS Code, are validation messages automatically shown to the user? 
- Or does use need to do any additional setting? 
- Does user needs to open some specific panel in VS Code?
- Does user need to start validation by some command?
- Is user prompted to install this new extension once old `DMN` or `BPMN` extension is installed and the new is not detected?

2024-02-20 13:48 UTC, Josephblt commented
Hello @jomarko.

- Once it is installed into VS Code, are validation messages automatically shown to the user?
Yes. Once installed, Bpmn and Dmn files behave like any other supported language. So any time the user opens a file or changes something, the files are validated. If any error is detected it is reported to the Problems tab.
- Or does use need to do any additional setting?
It works right out of the box. But it supports a few configurations. You can run the services locally or point to any address you want. You can also set how long between each connection check.
- Does user needs to open some specific panel in VS Code?
Nothing, it is intended to work just as any other script/language validator. If you change a file it reports the errors.
- Does user need to start validation by some command?
You can, but it's not necessary. It detects file activity, both from VS Code itself and outside sources (Git changes for example).
- Is user prompted to install this new extension once old DMN or BPMN extension is installed and the new is not detected?
No, but this is a cool feature that we already discussed. However, this is a change that needs to be implemented in the DMN and BPMN extensions themselves. So not part of this PR.

2024-03-27 16:26 UTC, tiagobento requested changes
Did a first round of review and left some comments inline.

General comments:

- Please do use PascalCase acronyms. (e.g., `KIEFile` becomes `KieFile`)
- JITExecutor is not exposed to us in any form. This extension depends on Extended Services. The fact that Extended Services embeds JIT Executor is an implementation detail we don't need to expose.
- Be mindful of error treatment / exceptional case handling. There's a lot of `if` statements without a matching `else`, potentially hiding errors and making the system fail silently.
- Try and keep names more explicit and consistent. `service` is too generic to be used without a discriminator. `command` may refer to VS Code commands or JITCommands, so you have a name clash there... `Extended-Services` with a dash is not something we use anywhere else... This kind of thing. 
- For "weird" parts of the code where context is required, don't be afraid to leave comments. E.g., `Range(0,0,0,0)`
- The directory structure of `packages/extended-services-vscode-extension/src` looks odd IMHO. The two main files are nested inside the `extension` directory, while some "util" files like "validation-helper.ts" are at the top-level. I'm not a big fan of too much nesting, so feel free to put all files at the root. Start with a flat structure, and let the grouping show itself. `configuration` being inside `watchers` is a symptom of this premature nesting :)


Other than that looks solid. Fair separation of concerns, except from the ValidationHelper class of course. Great use/de-use of resources. Nice attention to detail.

The programming style is very Java-like, but I feel like you'll get TypeScriptized soon enough 😜

Thanks @Josephblt!!! Nice job! Looking forward to round 2 of the review.

2024-03-27 16:26 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeRecommendation.ts
> +}
BPMN-specific commands here...

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/watchers/kie-files/kie-file.ts
> +  public readonly fsPath: string;
Please take this comment into consideration when naming variables that represent paths https://github.com/apache/incubator-kie-issues/issues/783#issuecomment-1871525975

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +  private readonly relativePath: string = "/dist-dev/extended-services-java";
We shouldn't be using the `dist-dev` directory in production code.

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/validation-helper.ts
> +    await new Promise((f) => setTimeout(f, 50));
Can you please comment on the purpose of this blocking await?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/jit-executor/jit-commands.ts
> +export class JITCommands {
```suggestion
export class ExtendedServicesClient {
```

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly connectionHeartbeatInterval: number;
Always a good idea to make the unit clear here, so:

```suggestion
  readonly connectionHeartbeatIntervalInMs: number;
```

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly serviceURL: URL;
```suggestion
  readonly extendedServicesUrl: URL;
```

?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly autoRun: boolean;
```suggestion
  readonly enableAutoRun: boolean;
```

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +    const jarFilePath = path.join(absolutePath, this.relativePath, this.jarFileName);
Path variables... need better names.

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +export class LocalServiceManager {
Why not `LocalExtendedServicesManager`?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +  private readonly relativePath: string = "/dist-dev/extended-services-java";
Also, this variable is named `relativePath` and starts with a `/`..

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/jit-executor/responses.ts
> +        const errorMarker = " - error : ";
Those can all be constants.

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/extension/extension-main.ts
> +  }
What happens if there's no configuration?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/extension/extension-main.ts
> +    }
IMHO there's a lot of nested branches here. I always prefer to use guard clauses with `throw`s for exceptional cases. Helps catch errors and prevent the system from failing silently.

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/extension/extension-main.ts
> +    }
Please do apply that reasoning to other parts of the code as well.

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/jit-executor/jit-commands.ts
> +      return "";
Is this a good idea?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/jit-executor/jit-commands.ts
> +    }
```suggestion
    const bodyPayload: KIEValidateBodyPayload = {
      mainURI: "VS Code KIE files",
      resources: documents.map(document => ({
        content: document.getText(),
        URI: document.fileName,
      })),
    };
```

?

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/jit-executor/payloads.ts
I think `requests` would be a better name for it, no? :D

2024-03-27 16:26 UTC, tiagobento commented on packages/extended-services-vscode-extension/src/validation-helper.ts
I'm not a big fan of "helper", "util", "common" terminology... My experience tells me those easily become catch-all places with a lot of unrelated stuff, creating massive coupling and unmaintainable code. 

In this single-class file, you can already see three mixed responsibilities:
1. Managing the diagnostic collection of VS Code.
2. Actually calling Extended Services to validate stuff.
3. Registering the VS Code commands that will handle the validation.

Please do restructure to reduce coupling.

2024-05-13 22:46 UTC, Josephblt commented on packages/vscode-extension/src/VsCodeRecommendation.ts
> +}
Great catch. Changed "bpmn-vscode-extension.installExtendedServices" to "vscode-xtension.installExtendedServices.

2024-05-13 22:50 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/watchers/kie-files/kie-file.ts
> +  public readonly fsPath: string;
After the refactory, the variable type was changed. It is now typed as a vscode.Uri.

2024-05-13 23:11 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +  private readonly relativePath: string = "/dist-dev/extended-services-java";
This the variable now:
 esNormalizedFsPathRelativeToWorkspace = dist-dev/extended-services-java
 private readonly esNormalizedFsPathRelativeToWorkspace: string = "dist/extended-services-java";

2024-05-13 23:12 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/validation-helper.ts
> +    await new Promise((f) => setTimeout(f, 50));
This was left over from testing, sorry about this.

2024-05-13 23:17 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/extension/extension-main.ts
> +    }
Removed all logic nesting and changed to fail-first approach. I agree this way is more elegant when dealing with errors.

For all the other array-loop nesting cases, I changed those to functional-style.

2024-05-13 23:23 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/jit-executor/jit-commands.ts
> +      return "";
No, it is not. This block now shows the error message window and throws the error after.

2024-05-13 23:30 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/jit-executor/jit-commands.ts
> +    }
After the refactory, due to how the Diagnostics work, it was better to create individual payloads. So no collection mapping is necessary.

2024-05-13 23:32 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/jit-executor/payloads.ts
This is now called /request/ValidationRequests.ts

2024-05-14 09:42 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly connectionHeartbeatInterval: number;
Added unit to the variable name.

2024-05-14 09:43 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly serviceURL: URL;
Agreed.

2024-05-14 09:43 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/watchers/configurations/configuration.ts
> +  readonly autoRun: boolean;
Done.

2024-05-14 09:44 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +export class LocalServiceManager {
I went with LocalExtendedServices.

2024-05-14 09:51 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/local-service-manager.ts
> +    const jarFilePath = path.join(absolutePath, this.relativePath, this.jarFileName);
Yes. Changed to this:
private start(extendedServicesURL: URL, extensionAbsoluteFsPath:string): void {
        const jarAbsoluteFilePath:string = path.join(extensionAbsoluteFsPath, this.esNormalizedFsPathRelativeToWorkspace, this.esJarFileName);

2024-05-14 09:59 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/extension/extension-main.ts
> +  }
Caso não haja configuração neste caso não é necessário fazer nada. O tratamento para uma configuração inválida é feito acima e simplesmente encerra a conexão.

2024-05-21 12:50 UTC, Josephblt commented on packages/extended-services-vscode-extension/src/validation-helper.ts
Agreed. I changed it to Validator and the class has only 2 distinct methods for validation: one for BPMN and DMN. It receives a KieFile and returns the diagnostics for that file.

2024-05-27 15:39 UTC, jomarko commented
### Manual verification checkilst
- [ ] multiple files opened, switching between them
- [ ] turn on/off using indicator bottom right corner
- [ ] execute validation using command
- [ ] change extension settings
- [ ] non supported file opened
- [ ] corrupted dmn/bpmn file opened
- [ ] change opened file manually
- [ ] change opened file using KIE extension
- [ ] undo / redo changes in opened file

2024-05-28 12:05 UTC, jomarko commented
### 01 Validation stops to work
- Imagine user is working with a project with dmn and bpmn files. 
- The problems tab properly display messages
- Then user modify the project to contain a file [1] and also open that file [1]. FYI, this file was created manually by me erasing some lines manually, we do not have issue in KIE Editors.
- The VSCode displays an error [2]. From the liveness indicator, orange color, we can see, the validation/extended services are stopped.

The problem is, even erasing the problematic file and opening other, the extended-services extension is not restarted. Or better to say, The liveness indicator is still like not online. And messages are not refreshed.

[1]
[Untitled copy.bpmn.txt](https://github.com/apache/incubator-kie-tools/files/15469242/Untitled.copy.bpmn.txt)

[2]
![Screenshot 2024-05-28 140245](https://github.com/apache/incubator-kie-tools/assets/8044780/bc3cbc43-1e00-4230-8c9b-4e7092736fab)

2024-05-28 12:32 UTC, jomarko commented
### Restart extended-services
Once I click the button to disconnect Apache kie extended services, I am not able to re-connect them using the same button in the bottom right corner

2024-05-28 12:45 UTC, jomarko commented
### 03 Automatic run of the local instance

It seems the extended services validation are automatically started even if my configuration for automatic start of the local instance is turned off.

The screenshot is taken just after closing and reopening the VSCode

![Screenshot 2024-05-28 144502](https://github.com/apache/incubator-kie-tools/assets/8044780/e13f5e77-0532-4404-b0a2-db5d49373f76)

2024-05-28 13:59 UTC, jomarko commented
### 04 KIE Editor changes effect delay
When user edit the dmn/bpmn file with the KIE editor, not plain xml editor in VSCode, the problems tab is updated with a delay. See the steps below.

- Please open the file [1]. You will see two validation messages [2].
- Now change **New Input Data** data type to **Any** and save the file **A.dmn**
- The problems tab will still display two validation messages
- Now change **New Decision** data type to **Any** and save the file **A.dmn**
- The problems tab will display now one message [3], but it should be already empty [4]

[1]
[A.dmn.txt](https://github.com/apache/incubator-kie-tools/files/15470863/A.dmn.txt)

[2]
![image](https://github.com/apache/incubator-kie-tools/assets/8044780/133f329d-0979-4966-ae9b-bb4ad9691937)

[3]
![Screenshot 2024-05-28 155835](https://github.com/apache/incubator-kie-tools/assets/8044780/8915422a-446a-4365-89a8-1ed0bf3c4b42)


[4]
![image](https://github.com/apache/incubator-kie-tools/assets/8044780/e6fed66f-8fc6-4dfa-8016-60cd8467cd6a)

2024-05-28 14:02 UTC, jomarko reviewed
My review is completed. Please take a look at the points I have raised after trying the extension manually.

2024-05-30 16:09 UTC, Josephblt commented
Hello @jomarko. Thanks for testing things out. As I progress, I'll review the reported failures individually and address them in the comments. Thanks.

2024-05-30 17:50 UTC, Josephblt commented
> 01 Validation stops to work

Yes, I managed to find the problems with this. First, there was a problem happening due to a different response format. Second I changed the behaviour to not close the connection when an error happens during validation.

2024-05-30 19:44 UTC, Josephblt commented
> ### 03 Automatic run of the local instance
Nice catch. This is fixed now.

2024-05-31 12:06 UTC, Josephblt commented
> ### 02 Restart extended-services
After some tinkering, I managed to reproduce this error using WSL. I changed the way the process is started and finished. This is fixed now.

2024-05-31 19:50 UTC, Josephblt commented
> ### 04 KIE Editor changes effect delay

Hello @jomarko. Nice catch. According to an [old bug reported](https://github.com/microsoft/vscode/issues/72831) in the VS Code repository,  it is possible to get stale data from tracked textDocuments. The last commit fixes that.

2024-06-11 22:44 UTC, danielzhe commented
I found an issue regarding the "02 Restart extended-services", reported before: if you click to disable the extended-service and don't wait for it to disable and click again in the icon at the right bottom of the VSCode, the extended-service doesn't come back live again, being necessary to kill the process manually in task manager.

In my opinion, I don't see why the user would like to completely disable it. Maybe just an option to "ignore the errors" instead of disable and enable? I don't know.

2024-06-12 10:24 UTC, Josephblt commented
Hello @danielzhe. I got an idea of what could be causing this. I'll let you know when I fix this. Thanks.

2024-06-13 10:47 UTC, Josephblt commented
Hello @danielzhe. All done. I could only reproduce the issue you reported by fast clicking the status bar icon. This last commit fix that issue.

2024-06-14 11:56 UTC, jomarko reviewed
@Josephblt thank you for updates. I think the points I raised during my previous review are addressed now. I have one more question. I tried to run extended services externally, I mean I set **Automatically run a local instance of the service** as false. It worked fine, I was doing updates for the dmn file and the problems tab was updated correctly, however then when I stopped that external extended service, the VS Code displayed this, an error message and the livenes indicator as live. Not sure, just asking, if this is intended behavior, or the extended services vscode extension should automatically detect the external extended service is offline and change the indicator to offline?
![Screenshot 2024-06-14 135212](https://github.com/apache/incubator-kie-tools/assets/8044780/0676097f-4212-4df8-98a7-c31ebc3b6dca)

2024-06-14 13:24 UTC, Josephblt commented
Hello @jomarko. To update the liveness indicator we use a heartbeat check. By itself, that check only updates the icon and clears the diagnostics if the connection is lost. you can change the interval of that check in the settings. 
In the image you sent, there is a validation error. So I assume you tried to validate before the heartbeat check, so the validation failed and the error appeared.

2024-06-17 08:29 UTC, jomarko approved these changes
Ok, thank you @Josephblt , this PR is fine for me, I will get in touch in private channel with you to chat a little bit about the documentation for this extension.

2024-06-18 14:19 UTC, tiagobento approved these changes

2024-06-18 14:20 UTC, merged