incubator-kie-issues#966: Move the BPMN Quarkus Dev UI package from `kogito-apps` to `kie-tools`
apache/incubator-kie-tools pull request #2223
Opened 2024-04-02 08:21 UTC by pefernan

Closes https://github.com/apache/incubator-kie-issues/issues/966

2024-04-02 16:50 UTC, tiagobento requested changes

2024-04-02 16:50 UTC, tiagobento commented on packages/maven-base/pom.xml
> +    <version.org.kie.kogito>999-20240218-SNAPSHOT</version.org.kie.kogito>
Instead of hard coding the dependencies version here, I think we should be reusing the values from `env`. There's other packages doing this.. See https://github.com/apache/incubator-kie-tools/blob/main/packages/dev-deployment-kogito-quarkus-blank-app/install.js

2024-04-03 14:40 UTC, paulovmr approved these changes

2024-04-03 18:27 UTC, tiagobento commented
@pefernan I see there are changes done to `runtime-tools-process-dev-ui-webapp` and `runtime-tools-process-webapp-components` that seem unrelated... do you mind adding a comment about them to the PR description?

2024-04-03 21:51 UTC, tiagobento commented
@pefernan I just remembered something. For Maven packages to successfully be installed and not require the -D properties we require during the build, we need to run a Maven plugin called `flatten-maven-plugin`. The configuration is standard, and I think you can just configure it at the `maven-base` package, in the `<build><plugins>`. Every Maven package on `kie-tools` need to run it so that the published `pom.xml` doesn't depend on the build properties we pass.

2024-04-04 09:44 UTC, pefernan commented
> @pefernan I just remembered something. For Maven packages to successfully be installed and not require the -D properties we require during the build, we need to run a Maven plugin called `flatten-maven-plugin`. The configuration is standard, and I think you can just configure it at the `maven-base` package, in the `<build><plugins>`. Every Maven package on `kie-tools` need to run it so that the published `pom.xml` doesn't depend on the build properties we pass.

right!

2024-04-05 01:10 UTC, tiagobento approved these changes

2024-04-05 15:56 UTC, thiagoelg approved these changes

2024-04-05 17:22 UTC, merged