kie-issues#237: Implement DMN 1.4 Boxed iterator expression
apache/incubator-kie-tools pull request #2243
Opened 2024-04-16 13:39 UTC by danielzhe

Closes: https://github.com/apache/incubator-kie-issues/issues/237
Closes: https://github.com/apache/incubator-kie-issues/issues/238

Both tickets were made together because the `iterator expression` covers both as it is in the spec. See [**10.2.1.10 Boxed iterator**](https://www.omg.org/spec/DMN/1.4/PDF/)

2024-04-16 16:25 UTC, tiagobento requested changes
@danielzhe Thanks for the PR! I left some comments inline.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +            const ret: BoxedFor = {
Missing comment "// Do not inline this variable for type safety. See https://github.com/microsoft/TypeScript/issues/241"

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +          }
Defaulting to "every" and "some", while I think we should actively check for those types and throw an Error if anything else is found.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +          throw new Error("ConditionalExpression shouldn't have more than 3 rows.");
Wrong error message.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/resizing/WidthMaths.ts
> +  }
Not using the ITERATOR_EXPRESSION constants.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +        }
Defaulting to this, while I think we should explicitly check for rowIndex being 1 and 2, as iterator expressions shouldn't have more than 3 rows.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +        } else return "satisfies";
Same here. Defaulting to "satisfies", while we should check for explicit cases we support and throw an error for all other unexpected cases.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +        return expression.__$$element;
Using `__$$element` here is not ideal, as it is a coincidence that those two things have the same value. Please explicitly return the name of the expression based on what type of iterator it is.

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionCell.tsx
> +      return iteratorClause.child?.expression as any;
Why "as any"?

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionCell.tsx
> +                  expression: getNewExpression(),
Why not pass `prev` here, like you're doing at the `in` part?

2024-04-16 16:25 UTC, tiagobento commented on packages/boxed-expression-component/src/expressions/IteratorExpression/IteratorExpressionComponent.tsx
> +                    };
Please follow the same strategy of extracting the return value to a variable, explicitly typing it and adding the comment saying why this is necessary.

2024-04-16 21:19 UTC, tiagobento approved these changes

2024-04-17 17:53 UTC, ljmotta approved these changes
@danielzhe Amazing new features. The code is looking good.

2024-04-17 18:10 UTC, merged

2024-04-18 13:29 UTC, jaimeizuz commented
Hi @ljmotta  @tiagobento @danielzhe 

I've just tested this new functionality and I'm getting the following exception:

`{
  "name": "Error",
  "message": "IteratorExpression can't have more than 3 rows.",
  "stack": "Error: IteratorExpression can't have more than 3 rows.
    at child (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4951260)
    at aa (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4331465)
    at Gs (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4383558)
    at Dl (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4370837)
    at Sl (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4370765)
    at kl (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4370628)
    at _l (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4367615)
    at https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4317387
    at t.unstable_runWithPriority (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4533910)
    at Yr (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4317164)
    at Kr (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4317332)
    at $r (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4317267)
    at Ie (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4388077)
    at Qt (https://business-modeller-app.eu.ngrok.io/new-dmn-editor-envelope.js:2:4295958)"
}`

https://github.com/apache/incubator-kie-tools/assets/138981666/cdd63bdb-4bb4-4387-93a7-e06c2b977283

**Build Version:**
0.0.0 (daily-dev) @ 236931cf7a3299ac81d1fd84c7228cb1033496ae (2024-04-18 08:31:17)
**Kogito Runtimes Version:**
999-20240414-SNAPSHOT
**Quarkus Version:**
3.2.10.Final
**Dev deployments Base image URL:**
quay.io/kie-tools/dev-deployment-base-image:daily-dev
**Dev deployments Kogito Quarkus Blank App image URL:**
quay.io/kie-tools/dev-deployment-kogito-quarkus-blank-app-image:daily-dev
**Dev deployments DMN Form webapp image URL:**
quay.io/kie-tools/dev-deployment-dmn-form-webapp-image:daily-dev
**Extended Services version:**
0.0.0
**Commit SHA:**
236931cf7a

Google Chrome Version 123.0.6312.123 (Official Build) (64-bit) in Windows 10

2024-04-18 13:34 UTC, danielzhe commented
@jaimeizuz Ty for your report. It got broken in the code review, I'm already fixing it.