NO-ISSUE: Make sure `kie-tools` is using the latest timestamped SNAPSHOT from Kogito (999-20240428-SNAPSHOT)
apache/incubator-kie-tools pull request #2272
Opened 2024-04-29 09:25 UTC by yesamer

2024-04-29 11:41 UTC, yesamer commented
` 'dependencies.dependency.version' for org.apache.kie.sonataflow:sonataflow-quarkus-devui:jar is missing.`

I guess we should use ${revision} as version for that dependency

2024-04-29 14:51 UTC, tiagobento commented
@yesamer This package doesn't exist anymore. We're making the `devmode` image point to it locally on 
- https://github.com/apache/incubator-kie-tools/pull/2266


... This PR will have to wait for that.

2024-05-03 09:00 UTC, porcelli approved these changes
thank you for bring the last piece of the 3.8.4 upgrade puzzle!

2024-05-03 11:48 UTC, yesamer commented
Hi @tiagobento 
Still throws the same error I previously reported.

`'dependencies.dependency.version' for org.apache.kie.sonataflow:sonataflow-quarkus-devui:jar is missing. @ org.kie.kogito:serverless-logic-web-tools-swf-deployment-quarkus-app:${revision}, /home/runner/work/incubator-kie-tools/incubator-kie-tools/packages/serverless-logic-web-tools-swf-deployment-quarkus-app/pom.xml, line 146, column 17`

Is that expected?

2024-05-03 12:19 UTC, rodrigonull requested changes

2024-05-03 12:19 UTC, rodrigonull commented on packages/serverless-logic-web-tools-base-builder-image/env/index.js
> +        default: "999-202400502",
```suggestion
        default: "999-20240502",
```

2024-05-03 12:19 UTC, rodrigonull commented on packages/serverless-logic-web-tools-swf-dev-mode-image/env/index.js
> +        default: "999-20240502",
The kogito-swf-devmode image is now part of KIE tools and we no longer build it as part of the weekly jobs. We build it daily as part of the KIE tools daily dev job with the `latest` tag.

2024-05-03 12:23 UTC, yesamer commented on packages/serverless-logic-web-tools-base-builder-image/env/index.js
> +        default: "999-202400502",
Thank you @rodrigonull !!

2024-05-03 12:27 UTC, yesamer commented on packages/serverless-logic-web-tools-swf-dev-mode-image/env/index.js
> +        default: "999-20240502",
@rodrigonull Updated!

2024-05-03 19:52 UTC, tiagobento commented
@yesamer There was a missing dependency on `serverless-logic-web-tools-swf-deployment-quarkus-app`. Fixed and pushed.

2024-05-03 20:12 UTC, rodrigonull approved these changes

2024-05-06 21:49 UTC, tiagobento commented
Ok! So we should expect seeing this error on this PR's checks:

`
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.8.4:build (default) on project serverless-logic-web-tools-swf-deployment-quarkus-app: Execution default of goal io.quarkus:quarkus-maven-plugin:3.8.4:build failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:3.8.4:build: io/quarkus/deployment/builditem/RunTimeConfigurationSourceValueBuildItem
`

@pefernan is aware and could already reproduce this locally. We should have more info tomorrow! Thanks @yesamer and @pefernan !

2024-05-07 02:20 UTC, tiagobento commented
@yesamer @pefernan Just remembered we need to update https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator too!

2024-05-07 11:08 UTC, pefernan commented
@yesamer let's see if the new artifacts solve the build!

2024-05-07 13:43 UTC, pefernan approved these changes

2024-05-08 18:28 UTC, tiagobento commented
Update: this error is caused by a misconfiguration on the data-index-inmemory module. @pefernan will send a PR to `kogito-apps` fixing it and we'll need a new timestamped SNAPSHOT. cc @yesamer @rodrigonull @porcelli

2024-05-10 11:44 UTC, tiagobento commented
🤞

2024-05-10 15:01 UTC, merged