kie-issue#1149: DMN Editor produces invalid typeRef attributes
apache/incubator-kie-tools pull request #2316
Opened 2024-05-10 23:09 UTC by danielzhe

Closes: https://github.com/apache/incubator-kie-issues/issues/1149

Some places related to the user interface are using "<Undefined>".
The places where the data is marshaled are using `undefined`.

The "<Undefined>" value is still present in `DmnBuiltInDataType` because it is still a "valid value".

2024-05-13 12:11 UTC, ljmotta reviewed
@danielzhe Thanks for this change! I've added some comments inline

2024-05-13 12:11 UTC, ljmotta commented on packages/dmn-editor/src/boxedExpressions/getDefaultBoxedExpression.tsx
> +  const dataType = allTopLevelDataTypesByFeelName.get(typeRef ?? "<Undefined>");
`"<Undefined>"` is value used in a few places. Maybe extract to a variable? WDYT?

2024-05-13 12:11 UTC, ljmotta commented on packages/stunner-editors-dmn-loader/src/index.tsx
> +        window.beeApiWrapper?.getDefaultExpressionDefinition(gwtLogicType(logicType), dataType ?? "<Undefined>")
The `dataType` parameter of `getDefaultExpressionDefinition` accepts an `undefined` value, why fallback to `"<Undefined>"`? Maybe should we fallback inside the method?

2024-05-13 14:53 UTC, danielzhe commented on packages/dmn-editor/src/boxedExpressions/getDefaultBoxedExpression.tsx
> +  const dataType = allTopLevelDataTypesByFeelName.get(typeRef ?? "<Undefined>");
I'm going to use the `DmnBuiltInDataType` for this.

2024-05-13 14:54 UTC, danielzhe commented on packages/stunner-editors-dmn-loader/src/index.tsx
> +        window.beeApiWrapper?.getDefaultExpressionDefinition(gwtLogicType(logicType), dataType ?? "<Undefined>")
Because this is to the GWT layer and since it will be removed in the future I think we should avoid spending time on it.

2024-05-13 14:58 UTC, tiagobento commented on packages/stunner-editors-dmn-loader/src/index.tsx
> +        window.beeApiWrapper?.getDefaultExpressionDefinition(gwtLogicType(logicType), dataType ?? "<Undefined>")
This is not for display only, though, right? I mean, this is getting into the XML.

2024-05-13 21:49 UTC, danielzhe commented on packages/stunner-editors-dmn-loader/src/index.tsx
> +        window.beeApiWrapper?.getDefaultExpressionDefinition(gwtLogicType(logicType), dataType ?? "<Undefined>")
As we talked in pvt, I changed it to the proposed change by @ljmotta :)

2024-05-14 13:10 UTC, danielzhe commented
Changes applied! Ready for your review @ljmotta @tiagobento

2024-05-14 18:49 UTC, ljmotta approved these changes

2024-05-15 00:10 UTC, tiagobento approved these changes

2024-05-15 00:16 UTC, tiagobento requested changes
Actually... Just checked an there are a lot of references to `DmnBuiltInDataType.Undefined` in the `stunner-editors-dmn-loader` component. Those are used in the `beeToGwt` function, and certainly are leaking to the XML. Please check that too...

2024-05-15 19:51 UTC, tiagobento approved these changes

2024-05-15 23:09 UTC, merged