kie-issues#243: Fill the "description" of every env var on `kie-tools` build and save the report somewhere (1/2)
apache/incubator-kie-tools pull request #2421
Opened 2024-06-12 01:21 UTC by tiagobento

Part of https://github.com/apache/incubator-kie-issues/issues/243

Still missing the report. Will come in a future PR.

Also on this PR:
- Removing `podman` references and commands
- Renaming `buildTags` to `buildTag`. Only one tag version of images is supported during the build. Retagging needs to be done separately. 
- Improving `build-env` with `--help` and `--generate-empty-env-index-js`

2024-06-13 16:29 UTC, Josephblt commented on packages/chrome-extension-serverless-workflow-editor/env/index.js
> +      description: "", // TODO: Fill this
Did you leave this TODO intentionally? If so, please disregard it.

2024-06-13 16:39 UTC, Josephblt commented on packages/webpack-base/env/index.js
> +        "Whether or not `webpack` should minimize its bundled files. Can be `true` or `false`. Works for all packages on invokations of `webpack` during a `kie-tools` build.",
I think I found a typo here. Invokation should be Invocation, perhaps?

2024-06-13 16:39 UTC, Josephblt commented on packages/webpack-base/env/index.js
> +        "Whether or not `webpack` should skip type-checking TypeScript files. Can be `true` or `false`. Works for all packages on invokations of `webpack` during a `kie-tools` build.",
Same as above, Invokation typo.

2024-06-13 16:39 UTC, Josephblt commented on packages/webpack-base/env/index.js
> +        "Whether or not `webpack` should include source maps for its bundled files. Can be `true` or `false`. Works for all packages on invokations of `webpack` during a `kie-tools` build.",
Same as above, Invokation typo.

2024-06-13 16:40 UTC, Josephblt commented on packages/webpack-base/env/index.js
> +        "Can be `development` or `production`. Works for all packages on invokations of `webpack` during a `kie-tools` build.",
Same as above, Invokations typo.

2024-06-13 16:43 UTC, Josephblt commented on packages/dev-deployment-upload-service/env/index.js
> +      description: "", // TODO: Fill
Perhaps you forgot this here? If not please disregard.

2024-06-13 16:43 UTC, Josephblt commented on packages/dev-deployment-upload-service/env/index.js
> +      description: "", // TODO: Fill
Same as above.

2024-06-13 16:43 UTC, Josephblt commented on packages/dev-deployment-upload-service/env/index.js
> +      description: "", // TODO: Fill
Same as above.

2024-06-13 16:45 UTC, Josephblt requested changes
Hello @tiagobento. I left some questions regarding some TODO's and a small typo.

2024-06-18 14:37 UTC, tiagobento commented
@Josephblt Thanks! Please check https://github.com/apache/incubator-kie-tools/pull/2421/commits/428da0a4dd8e3f1d17f278b5792619814d0dab17

2024-06-18 15:54 UTC, Josephblt approved these changes

2024-06-18 19:25 UTC, thiagoelg approved these changes

2024-06-18 22:19 UTC, merged