kie-issues#1369: Create E2E tests API and some test cases for the DMN Boxed Expression Editor
apache/incubator-kie-tools pull request #2456
Opened 2024-06-28 22:45 UTC by danielzhe

2024-07-01 20:47 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/filterExpression.spec.ts
> +  test("should correctly create a nested filter", async ({ bee, page, stories }) => {
Your tests "translated" to the new API, @jomarko

2024-07-02 05:13 UTC, jomarko reviewed
Thank you for the PR @danielzhe , I haven't go through the tests yet, rather had a look on the API itself.

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/contextExpressionElement.ts
> +  }
What if the first context entry is renamed or has non default data type already?

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/decisionTableExpressionElement.ts
> +  private async addOutputFromHeaderGroupElementAtIndex(index: number) {
Reading code of this class, am I correct the new API always uses the 'plus' icon for adding rows or columns? Do we use somewhere the context menu -> Insert row / Insert column .... ?

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/functionExpressionElement.ts
> +  }
not sure if this is correct, we can add parameters to the function, but I do not think entries

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/invocationExpressionElement.ts
> +export class InvocationExpressionElement {
how to fill in `function name` 
![image](https://github.com/apache/incubator-kie-tools/assets/8044780/8b9dbdd6-5a5c-432f-a5ef-1fabb12922a4)

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/listExpressionElement.ts
> +import { Locator } from "@playwright/test";
missing header

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/boxedExpressionHeader.spec.ts
> +    await bee.pasteToSelectExpression();
is the rewriting of the tests using new API still in progress? asking because lines above seems also be available in the new bee API

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/filterExpression.spec.ts
> +  test("should correctly create a nested filter", async ({ bee, page, stories }) => {
thank you, generally, is the rewriting using new API still in progress?

for example
```
  test("should rename a filter", async ({ page, stories }) => {
    await stories.openBoxedFilter("base");

    await page.getByRole("columnheader", { name: "Expression Name (<Undefined>)" }).click();
    await page.getByPlaceholder("Expression Name").fill("Filter Expression Name");
    await page.keyboard.press("Enter");

    await expect(page.getByRole("columnheader", { name: "Filter Expression Name (<Undefined>)" })).toBeVisible();
  });
```

^ I would expect this PR change some line in this code to be like `bee.asFilter()`

2024-07-02 05:13 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/filterExpressionElement.ts
> +  }
Looking on one of the tests:
```
    await bee.expression.asFilter().in.selectExpressionMenu.selectList();
    await bee.expression.asFilter().in.expression.asList().addEntry();
    await bee.expression.asFilter().in.expression.asList().entry(0).selectExpressionMenu.selectLiteral();
    await bee.expression.asFilter().in.expression.asList().entry(1).selectExpressionMenu.selectLiteral();
    await bee.expression.asFilter().in.expression.asList().entry(0).expression.asLiteral().fill("Passenger One");
    await bee.expression.asFilter().in.expression.asList().entry(1).expression.asLiteral().fill("Passenger Two");

    await bee.expression.asFilter().match.selectExpressionMenu.selectLiteral();
    await bee.expression.asFilter().match.expression.asLiteral().fill("item.Flight Number = Flight.Flight Number");
```

I think this `fill` (commented using this comment) should be removed. the `fill` should be probably only for cells we are sure they are implemented using monaco, in other words, do not contains nested expressions .

2024-07-02 13:10 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/contextExpressionElement.ts
> +  }
This is an WIP, not a finished work.

2024-07-02 13:17 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/filterExpressionElement.ts
> +  }
We are using `fill` to fill Literal Expressions, which are, by definition, single cells where the user can write feel expressions. Can you explain again what is the issue? Sorry, I don't understand this comment.  @jomarko

2024-07-02 13:19 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/filterExpression.spec.ts
> +  test("should correctly create a nested filter", async ({ bee, page, stories }) => {
Yes. I'm going to finish the API first, then write new tests.
I was just showing you an example.

2024-07-02 13:19 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/decisionTableExpressionElement.ts
> +  private async addOutputFromHeaderGroupElementAtIndex(index: number) {
Yes, we don't have nothing to context menu yet.

2024-07-02 13:20 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/functionExpressionElement.ts
> +  }
We can rename it.

2024-07-02 13:22 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/invocationExpressionElement.ts
> +export class InvocationExpressionElement {
WIP. 
Check the ticket, there are a lot of tests that will be done and the API will evolve as they are getting implemented.
https://github.com/apache/incubator-kie-issues/issues/1369

2024-07-02 13:23 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/boxedExpressionHeader.spec.ts
> +    await bee.pasteToSelectExpression();
Yes. It is not done. See the ticket:
https://github.com/apache/incubator-kie-issues/issues/1369

2024-07-02 13:38 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/listExpressionElement.ts
> +import { Locator } from "@playwright/test";
Thank you! Good catch!

2024-07-03 08:28 UTC, jomarko commented on packages/boxed-expression-component/tests-e2e/api/filterExpressionElement.ts
> +  }
yes, I do not understand why we have `fill` method in the `filterExpressionElement.ts`

2024-07-08 19:52 UTC, tiagobento commented on packages/boxed-expression-component/tests-e2e/api/functionExpressionElement.ts
> +  }
@danielzhe I think what Jozef means is that "adding entries" is not something that makes sense to the Function expression. WDYT about `addImplementationExpression`, or `addImplementation`, or even `selectImplementationExpression`?

2024-07-08 22:45 UTC, ljmotta reviewed
Thanks for addressing this. I think tests will look very good after this PR.
I know it's a WIP, but I've added a review of some things that I think must be addressed at some time, so I'll leave it here as a reminder 😄 

### Expression
I didn't like the `ExpressionElementEntry` name. Entry is a very specific name for the Context expression (Context Entry). And this class is being used by other expressions, like the `Conditional`, `Every`, `Filter`, etc. For some of those boxed expressions (I didn't verify all of them), the spec calls the nested expression `ChildExpression`, so I think this would be a more appropriate name to avoid ambiguity. WDYT?
I don't think the `ExpressionVariable` on the Iterator expressions is good for the same reason. The spec uses `iteratorVariable` to avoid ambiguity, but at the end is a `ChildExpression` as well. Not sure which name would be more appropriate.

### Boxed Context
In the Boxed Context, we have a pair of variable/expression which together make an entry. I couldn't see a clear distinction between them on the current API. Could you provide an example?

### Decision Table
As covered in the best practices and on the [Playwright docs](https://playwright.dev/docs/other-locators), the CSS locators are very discouraged. 
I'm unsure if it was intentional, but I think the `AtRight`/`AtLeft` used on the Output columns is better than the `AtStart` and `AtEnd` used on the Input!

### Boxed Function
As mentioned by @jozef and @tiago the `addEntry` does not make much sense for the Boxed Function.

### Boxed List
Like the Boxed Function, an `addEntry` doesn't make sense for it, I guess it should be `addRow`, WDYT?

### General (WIP section)
We must improve the `data-testid` of the entire test codebase.
It's missing the `addEntry`/`addRow` from `atTop`/`atBottom` on some expressions.
I know it's a personal preference, I see some `public` methods, but none are marked as `private`. Even though TS/JS allows this I personally don't think it's considered good practice as it's not explicitly telling what the variable/method is. As I said, feel free to leave like this though.

Overall the new API looks great. I think you've done a great job putting it together! As you can see, most of the comments are regarding the name choice!

2024-07-08 22:45 UTC, ljmotta commented on packages/boxed-expression-component/src/expressions/LiteralExpression/LiteralExpression.tsx
> +    <div className={`literal-expression`} data-testid={`literal-expression-${id}`}>
Please, norrow the `data-testid` scope. On the new DMN Editor we're using the `kie-tools--dmn-editor--`. I think we could use `kie-tools--bee--`. WDYT? Either way, this applies to all `data-testid` from the Boxed Expression Editor.

2024-07-08 22:45 UTC, ljmotta commented on packages/boxed-expression-component/stories/getDefaultBoxedExpressionForStories.ts
> +        expression: undefined as any,
No problem using the `as any`, but on another locations we use the `!`. I think we must stick with one. Either way, we need to add the comment regarding the spec discrepancy.

2024-07-16 13:45 UTC, danielzhe commented
@ljmotta Thank you for your review! I'm going to address the proposed changes as soon as I find out why some tests are failing only in CI 😢

2024-07-16 15:28 UTC, danielzhe commented
> I'm unsure if it was intentional, but I think the AtRight/AtLeft used on the Output columns is better than the AtStart and AtEnd used on the Input!

The question here is: at "left" or "right" of what? I think "atStart" and "atEnd" are more clear. Maybe in some cultures, the start is at the right, but still, I don't think that "atLeft" or "atRight" is better. But those who will use this API also have the option to use the `addInputAtIndex` or `addOutputAtIndex` and so on. @ljmotta

2024-07-16 15:40 UTC, danielzhe commented
> I know it's a personal preference, I see some public methods, but none are marked as private. Even though TS/JS allows this I personally don't think it's considered good practice as it's not explicitly telling what the variable/method is. As I said, feel free to leave like this though.

If we want to force some standardization that is just a "personal preference", we should force it in ESLint. Also, yes, it has private methods

2024-07-16 15:57 UTC, ljmotta commented
@danielzhe  Well, I can use the same question for `atStart`/`atEnd`. `atStart` and `atEnd` of what? 😄. Both questions are answered by the API, as for now we have `addInputAtStart`, `addInputAtEnd`, `addOutputAtRightOfIndex`, and`addOutputAtLeftOfIndex`. I just mentioned the one I preferred because I saw the Output column had a different set of methods. I wasn't sure if you were experimenting or not.

> If we want to force some standardization that is just a "personal preference", we should force it in ESLint. Also, yes, it has private methods.

Actually, the methods are private by default. You're not using the `private` keyword, only the `public` keyword. But as I said, for this case, leave the code as you wish. It's just something that I noticed.

2024-07-20 13:07 UTC, danielzhe commented
@tiagobento GREEN!🕺

2024-07-23 13:24 UTC, danielzhe commented
Can we get this merged or is there any pending change that I forgot? 😄 
 @tiagobento @ljmotta

2024-07-23 15:05 UTC, ljmotta requested changes
I've made my second round of reviews. Some of them are inline, and I've some general comments.

### Fixtures
Starting with the expressions. One general thing that I've noticed, that I didn't pay attention to at the first time, is the usage of the `locator` to refer to the `expression` itself, which I don't think is the best option, as `locator` is a way to identify any page element, and reading the code can cause ambiguity. For instance, we have a few `this.locator.locator`, which could be `this.expression.locator` or `this.expressionLocator`. But I'll let for @tiagobento to decide.

Almost all expressions have a getter `nameAndDataTypeCell`. The context expression is the only exception, which uses the `expressionHeaderCell` which in my opinion is a better suited name. The function expression is missing this getter, I'm not sure why.

Maybe I've misunderstood, but I thought we'd agreed on chat that it is best to have the `public` identifiers. Some methods still lack them, are we proceeding without them?

### Tests
I could see that some tests were not converted to the new API. Additionally, I could see that some tests create a very specific variable, and some tests don't create the variable at all. Looking at it, I think the idea of creating an expression variable on top of each test can help the legibility, for example, `decisionTable`, `context`, etc. But some time ago we decided for not to have any variable at all, so I'll leave this for @tiagobento to decide.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/src/expressions/LiteralExpression/LiteralExpression.tsx
> +    <div className={`literal-expression`} data-testid={`literal-expression-${id}`}>
This is still missing the narrowed `data-testid` scope.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/stories/getDefaultBoxedExpressionForStories.ts
> +        expression: undefined as any,
Here is still with `as any`, making it different than the other expressions that use the `undefined!`

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/__fixtures__/boxedExpression.ts
> +    return new ExpressionContainer(this.page.getByTestId("expression-container").nth(0), this.monaco);
It's using a `data-testid` without the narrowed scope.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressions/contextExpressionElement.ts
> +    return new ChildExpression(this.locator.locator(`.additional-row`).nth(0), this.monaco);
As mentioned on the previous review we should avoid class locators. Can't we use a `data-testid` for this case?

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressions/decisionTableExpressionElement.ts
This file has several `class` locators. The previous comment applies for this entire file. Why can't we use `data-testid` locators?

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressions/filterExpressionElement.ts
The `data-testid` here uses another pattern. It uses `kie-tools--boxed-expression-component--` instead of `kie-tools--bee--` of another files. Please stick with one.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressions/decisionTableExpressionElement.ts
> +  async addRowAtTop() {
Why we don't have a `addRowAtTopOfIndex`?

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressionContainer.ts
> +    return (await this.locator.nth(0).locator(">.logic-type-not-present").count()) === 1;
`class` locator

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressionContainer.ts
> +}
same.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/expressionContainer.ts
> +}
missing narrowed scope

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/api/nameAndDataTypeCell.ts
> +  }
`class` locators.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/context/contextExpression.spec.ts
>  });
It's not using the new API.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/context/contextMenu.spec.ts
> +      const entry = bee.expression.asContext().entry(0);
We couldn't create only one variable for this case? On the start of the test `const contextExpression = bee.expression.asContext()`.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/context/populate.spec.ts
>    test("should correctly create pre-bureau risk category boxed context", async ({
It's not using the new API.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/decisionTable/decisionTableExpression.spec.ts
> +  test("should render expression correctly", async ({ bee, page }) => {
It's not using the new API.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/decisionTable/contextMenu.spec.ts
Each test creates a few different variables. Why not use `const decisionTable = bee.expression.asDecisionTable()` at the top of the test, and the operations and assertions use this `decisionTable`?

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/populate.spec.ts
> +  test("should correctly create a Rebooked Flights filter", async ({ stories, page, bee }) => {
It's not using the new API.

2024-07-23 15:05 UTC, ljmotta commented on packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/filterExpression.spec.ts
>    test("should rename a filter", async ({ page, stories }) => {
It's not using the new API.

2024-07-23 15:06 UTC, ljmotta requested changes
I've made my second round of reviews. Some of them are inline, and I've some general comments.

### Fixtures
Starting with the expressions. One general thing that I've noticed, that I didn't pay attention to at the first time, is the usage of the `locator` to refer to the `expression` itself, which I don't think is the best option, as `locator` is a way to identify any page element, and reading the code can cause ambiguity. For instance, we have a few `this.locator.locator`, which could be `this.expression.locator` or `this.expressionLocator`. But I'll let for @tiagobento to decide.

Almost all expressions have a getter `nameAndDataTypeCell`. The context expression is the only exception, which uses the `expressionHeaderCell` which in my opinion is a better suited name. The function expression is missing this getter, I'm not sure why.

Maybe I've misunderstood, but I thought we'd agreed on chat that it is best to have the `public` identifiers. Some methods still lack them, are we proceeding without them?

### Tests
I could see that some tests were not converted to the new API. Additionally, I could see that some tests create a very specific variable, and some tests don't create the variable at all. Looking at it, I think the idea of creating an expression variable on top of each test can help the legibility, for example, `decisionTable`, `context`, etc. But some time ago we decided for not to have any variable at all, so I'll leave this for @tiagobento to decide.

2024-07-23 16:32 UTC, tiagobento commented
@ljmotta The idea of not having variables was to prevent tests from becoming complicated. We wanted to have testes that could be read from start to finish without having to jump around too much to understand what the test case is. I see on this PR we have some variables already, but I think I'd go for a single variable at the top and then inlining stuff at the individual lines.. Example:

```typescript
      const decisionTable = bee.expression.asDecisionTable()
      await decisionTable.cellAt({ row: 1, column: 1 }).fill("test");
      await decisionTable.cellAt({ row: 1, column: 0 }).contextMenu.open();
      await decisionTable.cellAt({ row: 1, column: 0 }).contextMenu.option("Insert").click();
      await decisionTable.cellAt({ row: 1, column: 0 }).contextMenu.button("minus").click();
      await decisionTable.cellAt({ row: 1, column: 0 }).contextMenu.radio("Below").click();
      await decisionTable.cellAt({ row: 1, column: 0 }).contextMenu.button("Insert").click();

      await expect(decisionTable.cellAt({ row: 1, column: 1 }).content).toContainText("test");
      await expect(decisionTable.cellAt({ row: 2, column: 0 }).content).toBeAttached();
```

2024-07-23 16:37 UTC, tiagobento commented
I'll take a closer look at the `locator` thing in a bit...

2024-07-23 19:07 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/expressions/decisionTableExpressionElement.ts
> +  async addRowAtTop() {
Because it was not used in any test and I didn't notice I didn't do it.

2024-07-23 20:07 UTC, danielzhe commented on packages/boxed-expression-component/tests-e2e/api/expressions/filterExpressionElement.ts
It was a copy-paste from a previous test, but I'll change it to `kie-tools--bee--`

2024-07-24 12:53 UTC, danielzhe commented
@ljmotta Changes applied.

2024-07-24 21:10 UTC, ljmotta approved these changes
@danielzhe Thanks for your patience. LGTM!

2024-07-24 21:13 UTC, danielzhe commented
> @danielzhe Thanks for your patience. LGTM!

Thank YOU for your patience, @ljmotta 😄

2024-07-25 02:01 UTC, danielzhe commented
@tiagobento Ready!

2024-07-25 02:50 UTC, tiagobento approved these changes

2024-07-25 02:50 UTC, merged