NO-ISSUE: Add option to disable the extended services wizard
apache/incubator-kie-tools pull request #2533
Opened 2024-08-14 14:22 UTC by kbowers-ibm

2024-08-14 17:45 UTC, thiagoelg approved these changes

2024-08-19 09:31 UTC, jomarko requested changes
@kbowers-ibm hi, could you please explain more the strategy we have for disabling the wizard?

I am a little bit confused, after reading the PR title my understanding was that we completely hide the button, that would allow the user to display the wizard. But it seems we still keep displaying the wizard but we only change the wizard the text.

Maybe a video/screenshots to demonstrate an effect of this new property would help me in the understanding.

2024-08-19 14:59 UTC, jomarko approved these changes
@kbowers shared video in a private chat. I agree with the new behavior.  I think the new env variable names are somehow misleading but it may be related to my non-native speaker English level. As I do not want to block the PR, approving.

2024-08-19 15:05 UTC, tiagobento commented
Please add a good description here...

2024-08-19 16:39 UTC, merged