Reuse components and retrieve workflow definitions from data index instead of openapi.json in sonataflow-deployment-webapp
apache/incubator-kie-tools pull request #2537
Opened 2024-08-19 07:55 UTC by kumaradityaraj

@fantonangeli

2024-08-19 15:26 UTC, kumaradityaraj commented
@fantonangeli  please assign me this issue.

2024-08-19 17:15 UTC, fantonangeli requested changes
Thanks a lot @kumaradityaraj 

Besides the changes in this PR, I can see there are a few unused dependencies from the past:
- apollo-cache-inmemory                                   
- apollo-client                                           
- apollo-link-http                                        
- util 
- URL

Can you please check if they are really needed and in case remove them?

2024-08-19 17:15 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/pages/Workflows/Workflows.tsx
We don't need this file anymore as we can use `src/runtimeTools/pages/RuntimeToolsWorkflowDefinitions.tsx` directly

2024-08-19 17:15 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/navigation/RoutesSwitch.tsx
>        </Route>
We can move this block to `src/navigation/RuntimeToolsRoutesSwitch.tsx` rendering `RuntimeToolsWorkflowDefinitions` instead of `Workflows`

2024-08-19 17:15 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/navigation/RoutesSwitch.tsx
> +      </Route>
These switches should be defined in `src/navigation/RuntimeToolsRoutesSwitch.tsx`

2024-08-20 15:25 UTC, fantonangeli requested changes

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/routes/index.ts
> +    }>(({ workflowName }) => RUNTIME_TOOLS_ROUTE + `/workflow-definition/${workflowName}/trigger-cloud-event`),
I think we don't need these 2 routes and we can continue to use `routes.workflows.form` and `routes.workflows.cloudEvent`, limiting this PR to the workflow definitions.

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/runtimeTools/pages/RuntimeToolsWorkflowDefinitions.tsx
> +        pathname: routes.runtimeTools.runtimeToolsWorkflowForm.path({ workflowName: workflowDefinition.workflowName }),
```suggestion
        pathname: routes.workflows.form.path({ workflowId: workflowDefinition.workflowName }),
```

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/runtimeTools/pages/RuntimeToolsWorkflowDefinitions.tsx
> +        }),
```suggestion
        pathname: routes.workflows.cloudEvent.path({
          workflowId: workflowDefinition.workflowName,
        }),
```

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/navigation/RoutesSwitch.tsx
> -        <Workflows />
Because we removed the use of `Workflows` here we can also remove the unused import at line 24

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/pages/Workflows/Workflows.tsx
Please remove this file as it is not used anymore and remove the dependencies of this file which are not used by other files, in our case should be only @patternfly/react-table

2024-08-20 15:25 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/pages/Workflows/Workflows.tsx
in 
we are losing the `EmptyTableState` defined here at line 132. Can we reintroduce this message in `RuntimeToolsWorkflowDefinitions` without using a table as a wrapper for it? WDYT?
![Screenshot from 2024-08-20 16-58-25](https://github.com/user-attachments/assets/4d8e8b1b-818a-4c48-9cf4-dad94238b5eb)

2024-08-21 09:50 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/pages/Workflows/Workflows.tsx
Since `RuntimeToolsWorkflowDefinitions` cannot determine the number of elements returned by the data index, we are dropping this message to avoid adding unnecessary complexity to the code.

2024-08-21 10:54 UTC, fantonangeli requested changes

2024-08-21 10:54 UTC, fantonangeli commented on packages/sonataflow-deployment-webapp/src/runtimeTools/pages/RuntimeToolsWorkflowDefinitions.tsx
> +import React, { useCallback, useState } from "react";
`useState` seems unused, can you please remove it?

2024-08-21 15:33 UTC, fantonangeli approved these changes

2024-08-26 16:53 UTC, tiagobento commented on packages/sonataflow-deployment-webapp/package.json
> -    "util": "^0.12.5"
Thank you for cleaning this up! 👍

2024-09-03 12:25 UTC, fantonangeli commented
@tiagobento can we consider your comment an approval?
@domhanak can you please review this PR?

2024-09-06 08:33 UTC, domhanak approved these changes

2024-09-06 15:58 UTC, tiagobento approved these changes
Good to go when conflicts are solved. @kumaradityaraj Please accept `pnpm-lock.json` from `main` then re-bootstrap the repo:

- `git fetch origin`
- `git merge origin/main` --> Conflict will happen here.
- `git checkout origin/main -- pnpm-lock.json`
- `pnpm bootstrap`
- `git merge --continue`

That's how I'm used to solving it. Thanks!

2024-09-06 20:22 UTC, merged