kie-issues#2544: Create a landing page for the Data Index
apache/incubator-kie-tools pull request #2551
Opened 2024-09-02 10:30 UTC by kumaradityaraj

Closes [apache/incubator-kie-issues#2544](https://github.com/apache/incubator-kie-tools/issues/2544)

**Description:**
Its a landing page for data index. Earlier it only showed the error and there was not any friendly message for the user but now we have it. The page has two different views one for light mode and the other one for dark mode as shown below.

**How to test**

- go to the packages/data-index-webapp directory

- `pnpm start`

**Preview**

https://github.com/user-attachments/assets/2d94d18a-4988-4b2d-9d54-01f89eae6433

2024-09-02 10:31 UTC, kumaradityaraj commented
@fantonangeli Please review this PR.

2024-09-02 16:23 UTC, fantonangeli requested changes
Thank you @kumaradityaraj 
This landing page looks very nice. 
I left some comments to make this package compliant with kie-tools standards.

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/package.json
> +  "private": true,
```suggestion
```

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.0.0",
```
It's better to follow the same version of other kie-tools packages

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/package.json
> +    "build:prod": "pnpm lint && pnpm test && rimraf dist && webpack && pnpm test-e2e",
```suggestion
    "build:dev": "rimraf dist && webpack --env dev",
    "build:prod": "pnpm lint && pnpm test && rimraf dist && webpack",
    "test": "run-script-if --ignore-errors \"$(build-env tests.ignoreFailures)\" --bool \"$(build-env tests.run)\" --then \"jest --silent --verbose --passWithNoTests\"",

```
- `--config webpack.config.ts` points to a configuration which is not in the package
- the other updates are to make the command `pnpm -F data-index-webapp -r build:prod` to run without the error: `Command "test" not found`

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/webpack.config.js
> +    },
This configuration is to interact with apis, which is not the case of data-index-webapp and we can remove it

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/webpack.config.js
> +const path = require("path");
Please after removing the unneeded part of `webpack.config.js`, remove the unused requires from here and from the `package.json`

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/webpack.config.js
> +  });
Here we can configure the devServer following other packages. 
To configure `buildEnv.dataIndexWebapp` you can start from the file:
`packages/sonataflow-deployment-webapp/env/index.js`
and choose a port which is not used by other packages.
See also `packages/sonataflow-deployment-webapp/webpack.config.js:98` as an example usage.

```suggestion
    devServer: {
      static: {
        directory: "./dist",
      },
      port: buildEnv.dataIndexWebapp.dev.port,
    },
  });
```

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/src/index.html
> +    <link rel="stylesheet" href="styles.css" />
```suggestion
    <link rel="stylesheet" href="styles.css" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.svg" />
```

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +@media (prefers-color-scheme: dark) {
Please reduce this media query to change only the colors without overriding fonts and sizes

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
```suggestion
  font-family: "RedHatText", "Overpass", overpass, helvetica, arial, sans-serif;
```
I think It's better to follow other SonataFlow packages fonts and avoid license issues

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/src/index.html
> +          <a href="https://graphql.org/learn/" class="btn">GraphQL docs</a>
Please open this link in a new window

2024-09-02 16:23 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +}
Please remove this unused css block.
You can use Chrome DevTools to discover unused blocks:
https://developer.chrome.com/docs/devtools/coverage

2024-09-03 16:36 UTC, fantonangeli commented on packages/data-index-webapp/env/index.js
> +          port: 9024,
This port is already used in serverless-workflow-dev-ui-webapp, can you please use a port not used by other packages? 
packages/serverless-workflow-dev-ui-webapp/env/index.js:28

2024-09-03 16:36 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +@media (prefers-color-scheme: dark) {
Please remove anything which is not `color` or `background`  from this media query without leaving comments.

2024-09-03 16:36 UTC, fantonangeli commented on packages/data-index-webapp/webpack.config.js
> +    },
This part which was needed in sonataflow-deployment-webapp to compress the code, but we don't need compression in this webapp.
Can you please remove this block and the TerserPlugin dependency?

2024-09-03 16:36 UTC, fantonangeli commented on packages/data-index-webapp/package.json
> +    "build:prod": "pnpm lint && pnpm test && rimraf dist && webpack && pnpm test-e2e",
Please apply this suggestion. It is also needed to add jest to the package:
`pnpm i -D jest`

after this running the following command from the root should work:
`pnpm -r -F data-index-webapp... build:prod`

2024-09-04 06:09 UTC, kumaradityaraj commented on packages/data-index-webapp/src/styles.css
> +@media (prefers-color-scheme: dark) {
After removing all the things; I have kept body margin and padding because if I am removing it a white border comes.

2024-09-04 09:20 UTC, fantonangeli requested changes
Below are my last suggestion.
Thanks a lot @kumaradityaraj

2024-09-04 09:20 UTC, fantonangeli commented on packages/data-index-webapp/env/index.js
> +          port: 9025,
Thank you for choosing a port not used by other packages. It happened that exactly the 9025 is used in PR #2532 , which is still in review. Can you please choose the 9026 to avoid using the same port after our PRs are merged?

2024-09-04 09:20 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +@media (prefers-color-scheme: dark) {
To avoid the white border, you can move the block below to the top of the CSS, outside of the media query. This way it's applied also to both versions (black and white) and there are no differences in dimensions between them.
```css
  body {
    margin: 0px;
    padding: 0px;
  }
  ```

2024-09-04 09:20 UTC, fantonangeli commented on packages/data-index-webapp/src/styles.css
> +  }
Here we can clean up all the properties already applied outside of the media query to keep this short and easier to maintain.
Please double-check that I didn't miss anything.

```suggestion
  .maindiv, .container {
    background-color: #232121;
  }

  h4, p {
    color: #fefefe;
  }
```

2024-09-04 09:20 UTC, fantonangeli commented on packages/data-index-webapp/package.json
> +    "jest": "^29.7.0",
We need to update the `pnpm-lock.yaml`, after changing a package dependencies.
Please run `pnpm bootstrap` on kie-tool's root and commit the updated files

2024-09-04 10:00 UTC, fantonangeli approved these changes

2024-09-05 15:38 UTC, thiagoelg requested changes
Thanks for the PR @kumaradityaraj! Looks good!

There seem to be a lot of unrelated changes in the `pnpm-lock.yaml` file. Could you revert it to the version at `main` and run `pnpm bootstrap` again?

2024-09-11 13:27 UTC, thiagoelg approved these changes
Looks good! Thanks for the changes @kumaradityaraj

2024-09-16 07:29 UTC, domhanak approved these changes

2024-09-17 15:56 UTC, merged