kie-issues#1595: Sandbox: Add "Open in Boxed Expression Editor" button in the DMN Runner form output cards
apache/incubator-kie-tools pull request #2720
Opened 2024-11-01 14:03 UTC by jomarko

Closes: https://github.com/apache/incubator-kie-issues/issues/1595

2024-12-19 10:11 UTC, tiagobento commented on packages/editor/src/api/KogitoEditorEnvelopeApi.ts
> +  kogitoEditor_openBoxedExpressionEditor(nodeId: string): void;
This method is specific to the DMN Editor so shouldn't be here in the generic Editor's interface.

2024-12-19 12:29 UTC, jomarko commented on packages/editor/src/api/KogitoEditorEnvelopeApi.ts
> +  kogitoEditor_openBoxedExpressionEditor(nodeId: string): void;
yes, thank you @tiagobento , @ljmotta gave me a tip to look on:
- `YardChannelComponent`
- `WebToolsEmbeddedEditor`
- `yardTextEditor_moveCursorToPosition`

working on it currently

2025-01-14 15:40 UTC, tiagobento commented on packages/dmn-editor-envelope/src/DmnEditorFactory.tsx
> +  protected self: DmnEditorRoot;
Why?

2025-01-14 15:40 UTC, tiagobento commented on packages/form-dmn/src/FormDmnOutputs.tsx
> +              </Flex>
Warnings from ESLint on this hook call.

2025-01-14 15:40 UTC, tiagobento commented on packages/online-editor/src/dmnRunner/DmnRunnerDrawer.tsx
> +            <DmnRunnerDrawerPanelContent {...props} />
This can be potentially dangerous... try and find some resources about this :)

2025-01-15 16:28 UTC, jomarko commented on packages/dmn-editor-envelope/src/DmnEditorFactory.tsx
> +  protected self: DmnEditorRoot;
I think I do not have answer that you would like to hear. This was the only way I was able to access introduced `openBoxedExpressionEditor` from the `NewDmnEditorInterface`. My understanding is we need to have both:
- `DmnEditorFactory` and `NewDmnEditorFactory` 
- `DmnEditorInterface` and `NewDmnEditorInterface`

to capture the fact, that new editor does support opening boxed expressions while the old one does not (from communication between packages point of view).

2025-01-15 16:29 UTC, jomarko commented on packages/form-dmn/src/FormDmnOutputs.tsx
> +              </Flex>
should be fixed now

2025-01-15 16:29 UTC, jomarko commented on packages/online-editor/src/dmnRunner/DmnRunnerDrawer.tsx
> +            <DmnRunnerDrawerPanelContent {...props} />
should be fixed now

2025-01-20 14:55 UTC, tiagobento requested changes
Thanks @jomarko! I believe this PR was a bit challenging but you navigated everything pretty well. Glad you had other places to reference to.

Please consider my comments inline.

2025-01-20 14:55 UTC, tiagobento commented on packages/online-editor/src/editor/EditorPage.tsx
> +                  isLegacyDmnEditor={settings.editors.useLegacyDmnEditor}
I guess this new property is not necessary as you can `useSettings` directly where you need it.

2025-01-20 14:55 UTC, tiagobento commented on packages/online-editor/src/dmnRunner/DmnRunnerDrawerPanelContent.tsx
> +                      }
Nice. This looks odd but it's the best solution possible right now given we have a single "Page" component for all Editors.

2025-01-20 14:55 UTC, tiagobento commented on packages/online-editor/src/dmnRunner/DmnRunnerContextProvider.tsx
> +  const isLegacyDmnEditor = useMemo(() => props.isLegacyDmnEditor, [props.isLegacyDmnEditor]);
Don't need that...

2025-01-21 12:32 UTC, jomarko commented
@tiagobento thank you, your points are incorporated now.

2025-01-21 13:55 UTC, tiagobento requested changes
Still some unnecessary hooks and properties.. Please take a look at my comments inline. Thanks @jomarko !

2025-01-21 13:55 UTC, tiagobento commented on packages/online-editor/src/dmnRunner/DmnRunnerContextProvider.tsx
> +  const dmnEditor = useMemo(() => props.dmnEditor, [props.dmnEditor]);
This line doesn't do much.. it tries to memoize a value based on itself, so you can use `props.dmnEditor` directly.

2025-01-21 13:55 UTC, tiagobento commented on packages/online-editor/src/dmnRunner/DmnRunnerContext.tsx
> +  isLegacyDmnEditor: boolean;
I still don't understand why we need this `isLegacyDmnEditor` property. You can remove it and use `useMemo(() => settings.editors.useLegacyDmnEditor, [settings.editors.useLegacyDmnEditor]);` everywhere you need it...

2025-01-22 07:36 UTC, jomarko commented on packages/online-editor/src/dmnRunner/DmnRunnerContextProvider.tsx
> +  const dmnEditor = useMemo(() => props.dmnEditor, [props.dmnEditor]);
done

2025-01-22 07:36 UTC, jomarko commented on packages/online-editor/src/dmnRunner/DmnRunnerContext.tsx
> +  isLegacyDmnEditor: boolean;
done

2025-01-22 16:10 UTC, tiagobento approved these changes

2025-01-22 16:57 UTC, thiagoelg approved these changes
LGTM

2025-01-22 20:56 UTC, merged