kie-issues#1526: [kn-plugin-workflow] kn-workflow-plugin should persist workflow in the docker image
apache/incubator-kie-tools pull request #2725
Opened 2024-11-05 19:53 UTC by treblereel

issue: https://github.com/apache/incubator-kie-issues/issues/1526

this issue is related to https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/405

2024-11-05 20:42 UTC, ricardozanini reviewed
So, are we manipulating the Quarkus auto-generated Dockerfile to add the files we need to pass the validation on the operator side?

2024-11-05 21:00 UTC, treblereel commented
> So, are we manipulating the Quarkus auto-generated Dockerfile to add the files we need to pass the validation on the operator side?

yeap, We have to include these files into the docker image

2024-11-05 21:00 UTC, treblereel commented
> So, are we manipulating the Quarkus auto-generated Dockerfile to add the files we need to pass the validation on the operator side?

yeap, We have to include these files into the docker image

2024-11-06 17:43 UTC, ricardozanini approved these changes

2025-01-16 06:53 UTC, domhanak commented on packages/kn-plugin-workflow/pkg/command/quarkus/testdata/docker/Dockerfile.jvm
> +FROM registry.access.redhat.com/ubi8/openjdk-17:1.18
Could this be parametrized? just a nitpick, disregard if not

2025-01-16 06:53 UTC, domhanak commented on packages/kn-plugin-workflow/pkg/command/quarkus/testdata/docker/Dockerfile.native
> +FROM registry.access.redhat.com/ubi8/ubi-minimal:8.9
Could this be parametrized? just a nitpick, disregard if not

2025-01-16 06:56 UTC, domhanak approved these changes

2025-01-16 06:57 UTC, domhanak requested changes
@treblereel please, let's rebase to ensure we are not missing some headers. This is quite old PR

2025-01-16 17:16 UTC, domhanak approved these changes

2025-01-16 18:36 UTC, treblereel commented on packages/kn-plugin-workflow/pkg/command/quarkus/testdata/docker/Dockerfile.native
> +FROM registry.access.redhat.com/ubi8/ubi-minimal:8.9
@domhanak Actually, this is only needed for testing; there's no need to keep the current version, any version will work.

2025-02-04 10:00 UTC, domhanak commented
@treblereel think we need headers with license for new files no? maybe I am wrong.

2025-02-04 10:00 UTC, domhanak commented
oh `.rat-excludes` cool. Merging.

2025-02-04 10:00 UTC, merged