kie-issues##1090: Move the source of kie-sandbox-quarkus-accelerator to kie-tools and use its repo as a deployment repo
apache/incubator-kie-tools pull request #2743
Opened 2024-11-11 22:36 UTC by tiagobento

Closes https://github.com/apache/incubator-kie-issues/issues/1090

---

Good description coming soon.

2024-11-22 12:11 UTC, fantonangeli requested changes
LGTM, I left a xxs suggestion

2024-11-22 12:11 UTC, fantonangeli commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
There are some lines like:
`console.log(`[git-repo-http-dev-server] MESSAGE`);
Can we make a simple function to call `console.log` with the "formatted" message?

2024-11-22 15:51 UTC, tiagobento commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
Not exactly sure what you mean... each call to `console.log` is a different log entry...

2024-11-22 16:00 UTC, fantonangeli commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
I mean to call a function like:
```ts
function logger(message: string){
 console.log(`[git-repo-http-dev-server] ${message}`);
}
```
So we can easily change all the messages if we need. 
Wdyt?

2024-11-22 18:39 UTC, tiagobento commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
Not a big fan of the indirection, as the `logger` function would always force `console.log`. Finding and replacing works well and everything is contained to one single file...

2024-11-22 18:39 UTC, tiagobento commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
If this ever gets more complicated, maybe it's worth refactoring, but not in the current state.

2024-11-25 08:33 UTC, fantonangeli commented on packages/kie-sandbox-accelerator-quarkus/dev-server/server.mjs
> +      console.log(`[git-repo-http-dev-server] Received request for '${req.url}'...`);
perfectly fine for me

2024-11-25 17:13 UTC, fantonangeli approved these changes

2024-11-25 21:47 UTC, ljmotta approved these changes
@tiagobento thanks for this PR. LGTM!

2024-11-25 21:48 UTC, merged