apache_issues#2630: Extend kn-workflow CLI to Generate K8s secrets fo…
apache/incubator-kie-tools pull request #2763
Opened 2024-11-25 09:05 UTC by treblereel

…r workflows

issue: https://github.com/apache/incubator-kie-tools/issues/2630

2024-11-25 15:29 UTC, ricardozanini approved these changes

2025-01-13 16:31 UTC, ricardozanini commented
@wmedvede @domhanak can you please take a look?

2025-01-17 09:30 UTC, wmedvede requested changes

2025-01-17 09:30 UTC, wmedvede commented on packages/sonataflow-operator/workflowproj/workflowproj.go
> +		return "", fmt.Errorf("invalid environment variable name: %s (must only contain A-Z, 0-9, and _)", name)
I think it could be helpful for future error tracing, to print which was the original property name, and which was the resulting normalized env var name.

Also I believe there are property name cases not covered by the algorithm, example:

quarkus."myProperty".value 

should be normalized into:

QUARKUS__MYPROPERTY__VALUE

Double check please, I think it's a potential valid use cases with quarkus properties.

see: https://quarkus.io/guides/config-reference#environment-variables

2025-01-18 22:44 UTC, treblereel commented on packages/sonataflow-operator/workflowproj/workflowproj.go
> +		return "", fmt.Errorf("invalid environment variable name: %s (must only contain A-Z, 0-9, and _)", name)
Thank you for the review. I missed the fact that application.properties can contain Quarkus-specific formats. I’ve fixed(and cases like  `%dev, prod.some.property=value`). By the way, we might consider adding support for application.yaml in the future.

2025-01-20 09:36 UTC, wmedvede approved these changes
LGTM, thank you!

2025-01-20 16:59 UTC, ricardozanini commented
Waiting for @domhanak review

2025-02-04 09:32 UTC, domhanak approved these changes
LGTM

2025-02-04 16:36 UTC, ricardozanini commented
@treblereel can you resolve the conflicts so I can merge?

2025-02-04 16:59 UTC, treblereel commented
@ricardozanini done, let's wait for the tests and merge. Once it is done, I will rebase the next one

2025-02-04 19:37 UTC, merged