kie-issues#1669: jBPM Quarkus DevUI seems to not update the # of items
apache/incubator-kie-tools pull request #2814
Opened 2024-12-16 12:57 UTC by bncriju

The wrong behavior is rectified by making the Process Instances, Tasks and Jobs to get dynamically updated, as and when user defines a process instance.

Closes https://github.com/apache/incubator-kie-issues/issues/1669

Please note that earlier pull request got auto closed while renamed the branch name to match the correct kie-issue and the comments in the previous pull request are already incorporated in this one.

2024-12-18 14:27 UTC, pefernan requested changes
@bncriju great work! I cannot get the counts initialized to `0` the first time I open Dev UI  for first time (they stay as `-`). Would you mind taking a look?

2024-12-18 14:27 UTC, pefernan commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/JBPMDevUIEventPublisher.java
> +            default:
maybe we can get rid of the default

2024-12-18 14:27 UTC, pefernan commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        vertx.setTimer(500, id -> {
This timer looks like to short, in slow laptops (like main) this may not work, but I think we can go with it for now.

2024-12-19 18:57 UTC, bncriju commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/JBPMDevUIEventPublisher.java
> +            default:
Done

2024-12-19 18:58 UTC, bncriju commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        vertx.setTimer(500, id -> {
Done and adjusted to 1000 instead of 500

2024-12-19 19:00 UTC, bncriju commented
Thanks for the comments @pefernan. Still cannot get the counts initialized to 0 the first time I open Dev UI for first time (they stay as -), but this works fine as expected when we open process-compact-architecture.

2025-01-08 14:03 UTC, bncriju commented
Done all the changes, and could you have a review once again

2025-01-08 18:14 UTC, pefernan requested changes
@bncriju great work, I'd just clean up a bit the logs to avoid printing info on every count refresh and that would be all.

2025-01-08 18:14 UTC, pefernan commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        LOGGER.info("Refreshing data for query: {}", query);
@bncriju I'd change this to `debug` to have the logs a bit more clean

2025-01-08 18:28 UTC, pefernan commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        this.path=path;
I think this path is not needed, since it's always an empty string.

2025-01-08 20:00 UTC, danielzhe commented
Good job, @bncriju ! 

I just found some minor issues in the jbpm-dev-ui:
1. The Process Instances, Tasks and Jobs does not automatically update in the first run. I mean, if we have zero process and start a new one, the count just start if I refresh the page (pressing F5). After that, they update automatically without the need of refresh.

2. It looks like the counters doesn't decrement. I started 3 process, waited them to be finished and the counters still at 3. For the process instances it may be correct, since they are completed, but I'm not sure about the tasks. Even applying the filters, I can't see any task:
![image](https://github.com/user-attachments/assets/71b56115-95db-4a47-9528-b71bf3c04f91)

I don't know if this is an issue, but I think it doesn't looks correct. It can be an issue related to filters in tasks either. I'm not sure. What do you think @pefernan ?

2025-01-08 20:09 UTC, danielzhe commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        this.path=path;
In fact, it is not, specially in the `jbpm-dev-ui` where the default path is `http://0.0.0.0/kie`. Without this code, the `DataIndexCounter` fail [here](https://github.com/apache/incubator-kie-tools/pull/2814/files#diff-40c015a84a4818f22053e2fe1620d27260e24625fa029982b1b289f738e4a8e9R89), because it calls `http://0.0.0.0/graphql` instead of `http://0.0.0.0/kie/graphql`.

User can set a URL like `https://localhost:8080/some/long/path` for the setting `kogito.data-index.url`, so we need that path that is not part of the domain, because as you can see [here](https://github.com/apache/incubator-kie-tools/blob/be87d4b6bd7844cf175f74dd25ffc3bca4d19c59/packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/JBPMDevuiJsonRPCService.java#L81), the `WebClientOptions` only contains the **host**, port and if it is ssl or not, not the full path (subdomain).

2025-01-09 07:49 UTC, bncriju commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        this.path=path;
Agreeing with Daniel. This was necessary which is why it is given.

2025-01-09 07:55 UTC, bncriju commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        LOGGER.info("Refreshing data for query: {}", query);
Done

2025-01-09 10:48 UTC, pefernan commented on packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
> +        this.path=path;
got it @danielzhe, I was missing that the the application may have a different context path configured...

2025-01-09 11:00 UTC, pefernan commented
@danielzhe yes, issue 1 is something I already found. Looks like the new subscriptions added to the counter Multi aren't updated with the new values.. I provided @bncriju a PR with a fix (https://github.com/bncriju/incubator-kie-tools/pull/2)

Regarding 2.. yes, that's a filter thing, we are currently showing the count of all elements (process instances, tasks or jobs) indexed in data-index. When we first created we wanted to show a snapshot of what was present on the system, but we can definitelly change it. In the end I think that it's just matter of deciding what we want to display there, I don't have a strong opinion.
IMO It would be cool to have different counters for each label and show different data, but at this point I think Quarkus doesn't allow that, maybe in future versions.

2025-01-09 11:14 UTC, pefernan approved these changes
great job @bncriju! I think we have it :D

2025-01-09 11:37 UTC, bncriju commented
thanks Pere and Daniel for all the inputs and suggestions on this. now, in good position to merge seeing the ci build status.

2025-01-09 11:49 UTC, pefernan approved these changes

2025-01-09 13:18 UTC, danielzhe approved these changes
Great job!

2025-01-09 14:12 UTC, yesamer approved these changes

2025-01-09 14:13 UTC, yesamer commented
Merging, the failing 'CI :: License headers' is unrelated and already fixed.

2025-01-09 14:13 UTC, merged