kie-issues#1718: DMN Editor extension generates SVG with missing font color
apache/incubator-kie-tools pull request #2816
Opened 2024-12-16 14:11 UTC by Kusuma04-dev

Closes https://github.com/apache/incubator-kie-issues/issues/1718

Fixing font-color issue while downloading SVG in DMN Editor.

2024-12-16 14:21 UTC, yesamer commented
@Kusuma04-dev Thank you and congratulations on your first contribution! Do you have any screenshots to share to see your change in action?

2024-12-16 15:02 UTC, kbowers-ibm requested changes
Hi Kusuma, congrats on your first PR! It looks great, and more importantly, it works, so nicely done! As Yeser mentioned, it can be helpful to include a screenshot, e.g. a before and after showing your change working, especially with a visual bug like this. Just a minor comment from me regarding clean-code practices

2024-12-16 15:02 UTC, klbowers commented on packages/dmn-editor/src/svg/DmnDiagramSvg.tsx
> +                style={{ ...fontStyle, fill: fontStyle.color }}
Instead of explicitly adding the fill property here, it's probably a bit cleaner to set it in the fontStyle the way the rest of the properties do

2024-12-16 15:11 UTC, jomarko commented
Will do review once https://github.com/apache/incubator-kie-tools/pull/2816#discussion_r1886967302 is discussed. Right now I am not sure if code will change or not.

2024-12-17 04:34 UTC, Kusuma04-dev commented on packages/dmn-editor/src/svg/DmnDiagramSvg.tsx
> +                style={{ ...fontStyle, fill: fontStyle.color }}
Hi , I have changed it.

2024-12-17 04:37 UTC, Kusuma04-dev commented
> @Kusuma04-dev Thank you and congratulations on your first contribution! Do you have any screenshots to share to see your change in action?
DMN diagram:
<img width="678" alt="Screenshot 2024-12-17 at 9 50 58 AM" src="https://github.com/user-attachments/assets/390bce11-5f6a-4074-a141-45cb31d1796d" />
SVG before fix:
<img width="868" alt="Screenshot 2024-12-17 at 10 06 37 AM" src="https://github.com/user-attachments/assets/e92e733a-dae3-4a3e-870b-983627fb695d" />


SVG after fix:
<img width="843" alt="Screenshot 2024-12-17 at 10 07 14 AM" src="https://github.com/user-attachments/assets/f70ad0e7-5ef1-4b3d-a4e0-7d3625068f16" />

2024-12-17 06:59 UTC, jomarko approved these changes
I can confirm the feature works now well. Thank you for the fix.

2024-12-17 07:21 UTC, kbowers-ibm approved these changes
Thanks Kusuma, looks good to me!

2024-12-17 08:41 UTC, yesamer approved these changes
Thank you @Kusuma04-dev

2024-12-17 08:41 UTC, yesamer approved these changes

2024-12-17 08:42 UTC, merged