KOGITO-2693: Embeddable editors (Milestone 1)
apache/incubator-kie-tools pull request #293
Opened 2020-10-22 19:34 UTC by paulovmr

Part of an ensemble:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1504
* https://github.com/kiegroup/appformer/pull/1065
* https://github.com/kiegroup/kie-wb-common/pull/3464
*

2020-10-22 21:35 UTC, paulovmr commented
@jstastny-cz To test both DMN and BPMN standalone editors, I've published it on GitHub Pages:
* [DMN Editor](https://kiegroup.github.io/kogito-online/standalone/dmn/) ([HTML](https://github.com/kiegroup/kogito-online/blob/gh-pages/standalone/dmn/index.html))
* [BPMN Editor](https://kiegroup.github.io/kogito-online/standalone/bpmn/) ([HTML](https://github.com/kiegroup/kogito-online/blob/gh-pages/standalone/bpmn/index.html))

2020-10-23 13:19 UTC, tiagobento requested changes
Hi @paulovmr! Great work! Left some minor comments inline.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-bc-editors/src/__tests__/GwtEditorWrapperFactory.test.ts
> +      {shouldLoadResourcesDynamically: true},
Formatting.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/README.md
> +--
Can you please update this README? A simple description of what the module provides plus a small code snipped with the most basic usage would be awesome.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/resources/bpmn/index.html
> +</html>
Can you please add a comment on this file saying that it's used for testing/development purposes only? I believe this module has a particular complex organization and this might confuse people on their first contact with it.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/resources/dmn/index.html
> +</html>
Same for this one.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/src/common/EditorResources.ts
> +}
On `kogito-tooling`, we're trying to use acronyms with camelCase too. Can you please rename these and other variables too? These should be called `JsResource` and `CssResource`.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/src/envelope/index.ts
> +  mutationObserver.observe(document.body, { childList: true, subtree: true });
I believe a comment here is necessary for the next reader (probably us in the future) 😝

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/src/envelope/index.ts
> +}
Comments.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/src/envelope/index.ts
> +    editorFactory: new GwtEditorWrapperFactory({ shouldLoadResourcesDynamically: false }),
Please add a comment explaining why this parameter is "false" on this case.

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/resources/dmn/dmnEnvelopeIndex.template
> +        }
Why is that necessary? (We can add a comment too)

2020-10-23 13:19 UTC, tiagobento commented on packages/kie-editors-standalone/resources/bpmn/bpmnEnvelopeIndex.template
> +    </script>
I believe a comment is also good here, since the actual script is wrapped by many things. Same for DMN template.

2020-10-26 09:53 UTC, manstis commented
@paulovmr @ederign Once these are merged could you please drop me a line as to how to use?

Trusty embeds the DMN editor the "old way" (copy the unzipped GWT webapps etc) and will move to this new way.

2020-10-26 13:51 UTC, paulovmr commented
Hi @manstis , I'm writing a blog post that will describe the whole feature.

For now, I think it is better to keep all other distributions using the current way of importing the Editors. For the next milestone, we plan to improve these standalone/embeddable editors for React Apps, creating React components that will make them better and easier to use.

2020-10-27 15:38 UTC, paulovmr commented
The CI build will fail because the modified editors are not built there. Please only consider the FDB.

2020-11-03 13:52 UTC, jstastny-cz commented on packages/kie-editors-standalone/README.md
> +  * `import * as DmnEditor from "@kogito-tooling/kie-editors-standalone/dist/dmn"`
Could we use named export to group the imports by the editor on higher level? let's say
```
import {DmnEditor} from "@kogito-tooling/kie-editors-standalone"
```
? Having `dist` in import statement always seems like misconfiguration to me.

2020-11-03 13:52 UTC, jstastny-cz commented on packages/kie-editors-standalone/package.json
> +  "scripts": {
do we measure test coverage in the kogito-tooling repository?

2020-11-03 14:32 UTC, paulovmr commented on packages/kie-editors-standalone/README.md
> +  * `import * as DmnEditor from "@kogito-tooling/kie-editors-standalone/dist/dmn"`
The named export and having the dist in the import are two different things. Using the `dist/some_dir` is a convention we adopted in kogito-tooling for when a package has submodules inside it (in this case, dmn and bpmn). About the export, we do it for the `open` function, so the import could be rewritten as `import { open } from "@kogito-tooling/kie-editors-standalone/dist/dmn"` if the user wants to.

2020-11-03 14:32 UTC, paulovmr commented on packages/kie-editors-standalone/package.json
> +  "scripts": {
No, we don't measure it yet.

2020-11-03 14:37 UTC, paulovmr commented on packages/kie-bc-editors/src/__tests__/GwtEditorWrapperFactory.test.ts
> +      {shouldLoadResourcesDynamically: true},
Done.

2020-11-03 14:37 UTC, paulovmr commented on packages/kie-editors-standalone/README.md
> +--
Done.

2020-11-03 14:37 UTC, paulovmr commented on packages/kie-editors-standalone/resources/bpmn/index.html
> +</html>
Done.

2020-11-03 14:37 UTC, paulovmr commented on packages/kie-editors-standalone/resources/dmn/index.html
> +</html>
Done.

2020-11-03 14:38 UTC, paulovmr commented on packages/kie-editors-standalone/src/common/EditorResources.ts
> +}
Done.

2020-11-04 19:55 UTC, paulovmr commented on packages/kie-editors-standalone/src/envelope/index.ts
> +  mutationObserver.observe(document.body, { childList: true, subtree: true });
Done.

2020-11-04 19:55 UTC, paulovmr commented on packages/kie-editors-standalone/src/envelope/index.ts
> +}
Done.

2020-11-04 19:55 UTC, paulovmr commented on packages/kie-editors-standalone/src/envelope/index.ts
> +    editorFactory: new GwtEditorWrapperFactory({ shouldLoadResourcesDynamically: false }),
Done.

2020-11-04 19:56 UTC, paulovmr commented on packages/kie-editors-standalone/resources/dmn/dmnEnvelopeIndex.template
> +        }
I've removed this part.

2020-11-04 19:56 UTC, paulovmr commented on packages/kie-editors-standalone/resources/bpmn/bpmnEnvelopeIndex.template
> +    </script>
Done.

2020-11-09 11:17 UTC, jstastny-cz commented on packages/kie-editors-standalone/README.md
> +  * `import * as DmnEditor from "@kogito-tooling/kie-editors-standalone/dist/dmn"`
> Using the dist/some_dir is a convention we adopted in kogito-tooling for when a package has submodules inside it (in this case, dmn and bpmn).

I am not sure I follow - `dist` folder is usually the location where the resulting JS bundle is placed, isn't it? Here we're using it as a sort of package-structure tool? I think we're unnecessarily exposing inner structure of @kogito-tooling/kie-editors-standalone package to the external world.

> The named export and having the dist in the import are two different things.

IMO they're not different things, I meant that the `dist` in import can be replaced by named export/import - a grouping named export from `@kogito-tooling/kie-editors-standalone` package, differentiating between bpmn and dmn by the imported name, not by the import path.

2020-11-12 18:54 UTC, jstastny-cz approved these changes
LGTM.

2020-11-16 12:18 UTC, tiagobento approved these changes

2020-11-20 18:33 UTC, merged