FAI-384: Score Cards: Move validation to post-commit update
apache/incubator-kie-tools pull request #436
Opened 2021-03-05 11:36 UTC by manstis

See https://issues.redhat.com/browse/FAI-384

This is an exciting PR :1st_place_medal: 

It refactors the entire validation sub-system to perform validation after all of the batch commits have completed.

Previously we were validating sub-trees after the sub-tree had been updated. However this was problematic when one sub-tree depended on the state/update made to another since the dependent sub-tree only had access to the stale/prior state and had to re-apply the change to the sub-tree it could access to mimic the complete batch. The JIRA may explain it better (of course it may not).

Sadly, with regard to testing, every RESOLVED child JIRA under https://issues.redhat.com/browse/FAI-333 should be revisited.

2021-03-05 11:49 UTC, manstis commented on packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaContainer/MiningSchemaContainer.tsx
> +    [dataDictionary, miningSchema]
I've also added validation to invalid `MiningField`'s that referenced `DataField`'s when the `DataField` is deleted. This requires the validations for the "Mining Schema" button and "Mining Field Rows" to be updated when the `DataDictionary` changes.

2021-03-05 11:51 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> -      case Actions.UpdateDataDictionaryField:
I've just moved this block, keeping the order the actions are handled by the reducers more consistent.

2021-03-05 11:53 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/OutputFieldReducer.ts
> +          },
I've moved some validations that were handled by the `ScorecardReducer` to reducers more appropriate for the validation being performed. For example `MiningSchema`\`MiningField` validation is now handled by the `MiningSchemaReducer`\`MiningSchemaFieldReducer`. The same can now be said for `Outputs` and `OutputField`.

2021-03-09 15:51 UTC, kelvah requested changes
Hi @manstis, thank you for the huge refactor. I've found two bugs inside `OutputReducer`. Plus left a consideration.

2021-03-09 15:51 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/OutputReducer.ts
> +              .build(),
This is not working because of the missing `output` in the path

```suggestion
            Builder()
              .forModel(modelIndex)
              .forOutput()
              .build(),
```

2021-03-09 15:51 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/OutputReducer.ts
> +              .build(),
Missing `output` here too

2021-03-09 15:51 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/DataDictionaryReducer.ts
> +    readonly modelIndex?: number;
Do we need `modelIndex` to delete a DD field?

2021-03-09 15:51 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +                );
I see you are marking as invalid the mining fields here. I am guessing what the user should do with them afterwords. Delete them? Create or rename a DD field? In that case mining fields need a re-validation on DD change. Also wondering if it is dangerous to replace a DD field pointed by a MiningField if there are attributes referring to the latter.

2021-03-09 16:04 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/DataDictionaryReducer.ts
> +    readonly modelIndex?: number;
Yes, we do. For the new validation you just added for Mining Schema. And that I commented minutes ago. :man_facepalming:

2021-03-09 20:07 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/OutputReducer.ts
> +              .build(),
Corrected. Thank-you.

2021-03-09 20:07 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/OutputReducer.ts
> +              .build(),
Corrected. Thank-you.

2021-03-09 20:13 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +                );
At this point it is only the references I need to re-validate so perhaps I'll make the clean-up smarter and just clear `forDataFieldMissing()`. I can then remove invalidation of the whole `MiningField`. I should probably re-validate the `MiningField` references when a DD is added or updated too. Did I understand correctly? I did not understand your second point "if it is dangerous to replace a DD field...". Perhaps we can discuss?

2021-03-10 10:57 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +                );
> At this point it is only the references I need to re-validate so perhaps I'll make the clean-up smarter and just clear `forDataFieldMissing()`. I can then remove invalidation of the whole `MiningField`. I should probably re-validate the `MiningField` references when a DD is added or updated too. Did I understand correctly?

Yes, that's correct. :+1:

> I did not understand your second point "if it is dangerous to replace a DD field...". Perhaps we can discuss?

Sure. I was referring to characteristics attributes, specifically to predicates. But on a second thought I don't think it's a problem strictly related to DD field deletion. I think it's more about what happens to predicates when doing changes to DD fields in general. So that's another story.

2021-03-10 16:20 UTC, tiagobento approved these changes

2021-03-10 16:30 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +                );
@kelvah I've added a new commit fixing "Issue 1 : At this point it is only the references I need to re-validate ...."

As discussed "Issue 2 : Complex validation scenarios" will be a new JIRA.

2021-03-10 16:47 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +              validateMiningFieldDataFieldReference(
When a `MiningField` is updated we clear the `ValidationRegistry` of all entries for the _whole_ `MiningField`.

We therefore have to re-validate the references. This issue would also exist in `master`.

2021-03-10 16:48 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +      //Note no break here, since we want the validation below to apply.
This, I think, is the lessor of two evils.

I either allow fall-through of the `case` to include validation or duplicate the code for validation.

~~Or move to a function that is re-used~~

Do you have a preference?

2021-03-10 16:49 UTC, manstis commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +const _validateMiningFieldDataFieldReference = (
Renamed, prefixing `_` (since it's an internal function).

2021-03-10 16:50 UTC, manstis commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +export const validateMiningFieldDataFieldReference = (
New function to validate the references of a single `MiningField`.

2021-03-10 17:30 UTC, kelvah commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +      //Note no break here, since we want the validation below to apply.
No problems with the case fall-through for me.
The only issue I see is that data fields can be added also via `Actions.AddBatchDataDictionaryFields`.

2021-03-10 17:43 UTC, kelvah commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +export const validateMiningFieldDataFieldReference = (
I don't get why you introduced the `_validateMiningFieldDataFieldReference` abstraction :thinking:

2021-03-11 08:56 UTC, manstis commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +export const validateMiningFieldDataFieldReference = (
Changed in a new commit to only have the exposed functions `validateMiningFieldDataFieldReference(..)` and `validateMiningFieldsDataFieldReference(..)`.

2021-03-11 08:56 UTC, manstis commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +const _validateMiningFieldDataFieldReference = (
Refactored.

2021-03-11 08:59 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +      //Note no break here, since we want the validation below to apply.
Validation of references also added for `AddBatchDataDictionaryFields`.

2021-03-11 08:59 UTC, manstis commented on packages/pmml-editor/src/editor/validation/MiningSchema.ts
> +export const validateMiningFieldDataFieldReference = (
Refactored.

2021-03-11 11:49 UTC, kelvah approved these changes
thanks @manstis for the changes :+1:

2021-03-11 13:31 UTC, manstis commented on packages/pmml-editor/src/editor/reducers/MiningSchemaFieldReducer.ts
> +                );
See https://issues.redhat.com/browse/FAI-434

2021-03-12 13:29 UTC, sjamboro approved these changes

2021-03-12 13:30 UTC, merged