[WIP] [DO NOT MERGE] Test Undo command
apache/incubator-kie-tools pull request #473
Opened 2021-04-08 13:47 UTC by jomarko

2021-05-12 13:41 UTC, jomarko commented
Contains also changes from https://github.com/kiegroup/kogito-tooling/pull/480, as there Dominik changes the method for opening files.

I will rebase once that PR is in. However my test is done and ready for review.

2021-05-13 11:18 UTC, domhanak approved these changes
Thanks, looks good to me. Let me know if you need help investigating windows issue.

2021-05-13 11:19 UTC, domhanak commented
Seems like `Include reusable-model in DMN Editor` is not working. Something is intercepting the click.

2021-05-13 15:30 UTC, jomarko commented
Rebased

2021-05-21 10:38 UTC, domhanak commented
@jomarko needs rebase again, sorry :) https://issues.redhat.com/browse/KOGITO-5180 I noticed this today maybe it is worth checking we have it covered here.

2021-05-24 06:12 UTC, jomarko commented
rebased @domhanak , lets see CI results

2021-05-24 09:27 UTC, domhanak commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    const envelopApp = await webview.findWebElement(By.id("envelope-app"));
this can be removed. The check happens in `openFileFromSideBar()`.

2021-05-24 09:33 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    const envelopApp = await webview.findWebElement(By.id("envelope-app"));
thank you, well spotted

2021-05-24 10:13 UTC, jomarko commented
@tiagobento @ederign hello, macos is failing with downloading dependencies, what is not related to this PR changes. Could we please proceed with your review and possible merge?

2021-05-25 08:28 UTC, jomarko commented
@tiagobento @ederign just a friendly reminder ^

2021-05-26 15:29 UTC, tiagobento requested changes
Thanks for the PR @jomarko! Comments inline.

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/VSCodeTestHelper.ts
> +    }
What if edit **is** undefined? The tests will be pass normally, as no asserts are done. Same for line 238.

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    this.timeout(40000);
This is something we should try and avoid at all costs. This is a very unreliable method of waiting, and only drags the tests for a big amount of time. I know @domhanak is working on stabilizing this, so I'm inclined to have this PR be merged only after this wait can be safely removed.

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    await (await dmnEditorTester.openDiagramProperties()).changeProperty("Name", "Updated Name 1");
I would extract this parenthesis'ed `await`s to local variables. `await (await` doesn't look good on the eyes. Optional change though.

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/dmn/DecisionNavigatorHelper.ts
> +  }
```suggestion
  constructor(private readonly root: WebElement) {}
```

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/dmn/DecisionNavigatorHelper.ts
> +  };
We usually don't do public arrow functions, we use named functions instead, like 

```
public async myFunction() {
   //contents
}
```

Same for private ones.

2021-05-26 15:29 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/dmn/PropertiesPanelHelper.ts
> +  }
Same as above.

2021-05-27 04:03 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    this.timeout(40000);
this is not a wait, this is the maximal time the test can run

2021-05-27 04:38 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/VSCodeTestHelper.ts
> +    }
good point, will address it

2021-05-27 04:42 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
> +    await (await dmnEditorTester.openDiagramProperties()).changeProperty("Name", "Updated Name 1");
will try to address it, thank you

2021-05-27 04:46 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/dmn/DecisionNavigatorHelper.ts
> +  };
understand, will try to address

2021-05-27 04:55 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/dmn/PropertiesPanelHelper.ts
> +  }
sure, will do

2021-05-31 06:58 UTC, jomarko commented
@tiagobento hello, the test is failing on Mac, however I am without an access to such environment. 

May I ask you for your help? Would you please run the test and watch, if the issue is:
- the Undo menu is really disabled (that would probably reproducible even manually)
- the menu is not shown/enabled quickly enough

2021-06-07 12:58 UTC, tiagobento commented
@jomarko Hi! Do you mind rebasing this PR and re-triggering the CI?

2021-06-07 13:06 UTC, jomarko commented
@tiagobento sure, good point. I did right now.

2021-06-07 13:57 UTC, tiagobento commented
@jomarko Thanks for rebasing the PR. After taking a look at the failure and how `vscode-extension-tester` accesses the "TitleBar" I can conclude that it won't work on macOS. The menu is not part of the Electron webview, but rather it's on the operating system bar. I'm not sure how we could overcome that, to be honest, but maybe using a keyboard shortcut to trigger the `Undo` command might be more cross-platform?

2021-06-07 20:00 UTC, tiagobento commented
@jomarko Also, it might be worth it opening an issue directly on `vscode-extension-tester`.

2021-06-08 06:56 UTC, domhanak commented
Hey guys, I am accessing the `titleBar` in #526 and it works well on mac too.The `vscode-extension-tester` does not mention this not being cross-platform so I do not think this is the issue.

2021-06-08 07:10 UTC, jomarko commented
The `vscode-extension-tester` has also a test, that suggests `TitleBar` should work fine also on mac, as it is started in github action on that repository. https://github.com/redhat-developer/vscode-extension-tester/blob/master/test/test-project/src/test/menu/titleBar-test.ts

2021-06-08 07:48 UTC, domhanak commented
OK so my PR has the same issue on MAC.

2021-06-08 08:40 UTC, jomarko commented
Tests passes also on mac with my latest changes.

2021-06-08 13:36 UTC, tiagobento requested changes
@jomarko Thanks for the updates! This PR is looking good. Left some minor comments inline.

2021-06-08 13:36 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
> +  };
Great workaround for the TitleBar usage! Works on all platforms. This function should probably be named "executeCommandFromPrompt", though. Also, no reason to abbreviate "quickPicks" to "qPicks".

2021-06-08 13:36 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
> +  TitleBar,
Leftover?

2021-06-08 13:36 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
> +    await testHelper.openCommandFromPrompt("Undo");
@jomarko Can you please explain a little bit more why we need two "Undo" commands? When using the extensions I don't see this pattern... is there a way we can replicate a user's interaction without firing two Undo commands?

2021-06-08 20:21 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
> +  };
sure, good points, will address them

2021-06-08 20:24 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
> +  TitleBar,
yes, will remove

2021-06-08 20:27 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
> +    await testHelper.openCommandFromPrompt("Undo");
as said in comment above this two Undo operations. The reason is we firstly clear the input box and then sendKeys with new value.

```
  public async changeProperty(propertyName: string, propertyValue: string): Promise<PropertiesPanelHelper> {
    const property = await this.root.findElement(labeledInputElementInPropertiesPanel(propertyName));
    await property.clear();
    await property.sendKeys(propertyValue);

    return this;
  }
```

This is needed because of selenium behind the scene. As you said, when human user interact with editor. the node rename is one operation and one undo is enough.

2021-06-08 20:45 UTC, tiagobento commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
> +    await testHelper.openCommandFromPrompt("Undo");
Oooh, okay. Makes sense! Thanks for clarifying that :)

2021-06-08 20:52 UTC, jomarko commented on packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
> +    await testHelper.openCommandFromPrompt("Undo");
np, thank you for review

2021-06-09 00:14 UTC, tiagobento approved these changes

2021-06-09 00:14 UTC, merged