[REPRODUCER][E2E] KOGITO-3527: WorkItemDefinitions parser coverage
apache/incubator-kie-tools pull request #475
Opened 2021-04-09 11:45 UTC by domhanak

Introduce usage of ResourceContent
Include more complex WID
Refactor framework to work with new type

2021-04-12 05:43 UTC, domhanak commented
As mentioned on chat, this behavior is expected for now and user should call `open()` before `setContent()`

2021-04-12 12:56 UTC, domhanak commented
@jstastny-cz PR updated with initial tests. Let me know if you have some tips. I am trying to make it more readable and expand over the unknown email task.

2021-04-12 14:21 UTC, jstastny-cz commented on packages/kie-editors-standalone/it-tests/src/components/EditorComponent.tsx
> +    editor!.setContent("", "");
we need to handle modelName here, otherwise the old file will be replaced when saving. Sth like `setModelName(modelName+filesHolder.size())` (careful with the suffix though).

2021-04-12 14:21 UTC, jstastny-cz commented on packages/kie-editors-standalone/it-tests/src/components/EditorComponent.tsx
> +          new process
General component, should not mention processes. I think `new file` or just `new` might be enough.

2021-04-12 14:21 UTC, jstastny-cz commented on packages/kie-editors-standalone/it-tests/src/components/EditorComponent.tsx
> +          new process
and is it used somewhere? (just checking that all is included in commit)

2021-04-12 14:42 UTC, domhanak commented on packages/kie-editors-standalone/it-tests/src/components/EditorComponent.tsx
> +          new process
Agree with the name, this is a leftover of trying to call open using this button. I will remove it :)

2021-04-13 08:57 UTC, domhanak commented
Updated the main description of PR. Ready for re review and merge once #478 is in. Ping me I rebase after.

2021-04-13 13:09 UTC, jstastny-cz requested changes
Just one left-over and one hint.

2021-04-13 13:09 UTC, jstastny-cz commented on packages/kie-editors-standalone/it-tests/cypress/integration/bpmn-workitem.spec.ts
> +        cy.wrap(dataAssignments.eq(2))
I think that similar pairs like cy.wrap(dataAssignemnts.eq(2)).find() could be transformed as:
```
cy.wrap(dataAssignements.eq(2)).within($it=> {
  cy.find().should();
  cy.find().should();
})
```
cause within should set the context and included get/find calls should reuse that context.
It saves you like one line per each - most importantly, when changing you change it only once.

2021-04-13 13:09 UTC, jstastny-cz commented on packages/kie-editors-standalone/it-tests/src/util/ResourcesHolder.ts
> +      { name, value: { path: name, type: ContentType.TEXT, content: fileContent } },
duplicate this.addFile() invocation. remove the second.

2021-04-16 05:10 UTC, domhanak commented
@paulovmr this is also ready for merging from my POV. The test failure are happening across repository and are unrelated

2021-04-16 06:23 UTC, jstastny-cz approved these changes
LGTM

2021-04-16 13:02 UTC, paulovmr approved these changes

2021-04-16 13:02 UTC, merged