KOGITO-741: Bring Octokit support to Online Editor
apache/incubator-kie-tools pull request #51
Opened 2020-01-09 20:42 UTC by jesuino

Uses octokit to fetch github files in online editor.

2020-01-13 15:40 UTC, tiagobento commented
Looks like there's an issue with CORS when trying to access GitHub's API. Will merge when it's fixed.

2020-01-17 10:29 UTC, domhanak commented on packages/online-editor/src/common/GithubService.ts
> +export class GithubService {
A test for this class would be useful

2020-01-30 16:37 UTC, jesuino commented
added a few tests @domhanak

2020-02-06 15:13 UTC, tiagobento requested changes
Looks good to me, great work @jesuino! Please make sure that your code is properly formatted and the imports are cleaned up. Also, please re-check the copyrights in new files. Thx!

2020-02-06 15:13 UTC, tiagobento commented on packages/online-editor/jest.config.js
> + * Copyright 202 Red Hat, Inc. and/or its affiliates.
Wrong copyright

2020-02-06 18:37 UTC, jesuino commented on packages/online-editor/jest.config.js
> + * Copyright 202 Red Hat, Inc. and/or its affiliates.
fixed, thanks @tiagobento

2020-02-11 14:23 UTC, tiagobento commented
Removed the `do not merge` label since we solved the CORS issue with another HTTP header.

2020-02-11 14:23 UTC, tiagobento approved these changes

2020-02-11 14:23 UTC, merged