Change the username input to namespace
apache/incubator-kie-tools pull request #601
Opened 2021-08-19 19:23 UTC by rafaeltuelho

This PR introduces a change to adapt the DMN deployment capability to support any Openshift Cluster instead of only supporting Red Hat Dev Sandbox.

2021-08-19 20:03 UTC, porcelli requested changes
thx @rafaeltuelho for the contribution! this is great. 

before a real round of review, could you please clean the noise in the PR, like: 
- the versioning assignment
- re-ordering of config files

2021-08-19 21:30 UTC, rafaeltuelho commented
> thx @rafaeltuelho for the contribution! this is great.
> 
> before a real round of review, could you please clean the noise in the PR, like:
> 
> * the versioning assignment
> * re-ordering of config files

Sure I'll take care of this. thanks

2021-08-20 14:08 UTC, porcelli commented
thx very much @rafaeltuelho for the update!

2021-08-20 14:10 UTC, rafaeltuelho commented
> thx very much @rafaeltuelho for the update!

Sure thing! Thanks @tiagobento and @caponetto for their patience teaching me some git magic tricks :-)

2021-08-20 14:44 UTC, caponetto reviewed
Hi @rafaeltuelho, thanks for the initiative, I really appreciate it!
I've left some minor comments, please check if they make sense.

2021-08-20 14:44 UTC, caponetto commented on packages/online-editor/src/common/i18n/locales/en.ts
> +          deployNowExplanation: `${"Deploy now".bold()}: Your model will be deployed on your instance. This action will take a few minutes to be completed and you will need to create a new deployment
Thanks for fixing it!

2021-08-20 14:44 UTC, caponetto commented on packages/online-editor/src/editor/DmnDevSandbox/DmnDevSandboxService.tsx
> +  private readonly RESOURCE_NAME_PREFIX = "dmn-service";
IMO we can keep the `dmn-dev-sandbox` prefix as this is the name of the feature, i.e. not directly related to Openshift Sandbox. cc @tiagobento

2021-08-20 14:44 UTC, caponetto commented on packages/i18n-common-dictionary/src/CommonI18n.ts
> +  namespace: string;
This list of properties is in alphabetical order. Can you place `namespace` before `new`?

2021-08-20 14:44 UTC, caponetto commented on packages/i18n-common-dictionary/src/locales/en.ts
> +    namespace: "Namespace (project)",
This list of properties is in alphabetical order. Can you place `namespace` before `new`?

2021-08-20 14:44 UTC, caponetto commented on packages/online-editor/src/common/i18n/locales/en.ts
> +            "This information is necessary for deploying youde Decision Model into the right project namespace.",
```suggestion
            "This information is necessary for deploying your Decision Model into the right project namespace.",
```
There is a type here.

2021-08-20 14:44 UTC, caponetto commented on packages/online-editor/src/editor/DmnDevSandbox/DmnDevSandboxService.tsx
>    private readonly NAMESPACE_SUFFIX = "-dev";
Could you please remove the `NAMESPACE_SUFFIX` constant and the  `composeNamespace` method?
With your changes, they no longer need to be there.

2021-08-20 14:48 UTC, rafaeltuelho commented on packages/online-editor/src/editor/DmnDevSandbox/DmnDevSandboxService.tsx
> +  private readonly RESOURCE_NAME_PREFIX = "dmn-service";
Sure, that makes sense.

2021-08-20 15:33 UTC, rafaeltuelho commented on packages/i18n-common-dictionary/src/CommonI18n.ts
> +  namespace: string;
Got it. Just out of curiosity, does this influence the runtime or is it just a code convention?

2021-08-20 15:37 UTC, rafaeltuelho commented on packages/online-editor/src/common/i18n/locales/en.ts
> +            "This information is necessary for deploying youde Decision Model into the right project namespace.",
thanks

2021-08-20 16:01 UTC, caponetto commented on packages/i18n-common-dictionary/src/CommonI18n.ts
> +  namespace: string;
It is just a convention.

2021-08-24 11:52 UTC, caponetto commented
Hi @tomasdavidorg, can you please take a look at this PR when possible?

We only use the `username` to append with `-dev` and deploy to `username-dev` namespace.
In this PR, @rafaeltuelho changed the required config from `username` to `namespace` to make it more flexible.

Anyway, the testing goal is just to make sure that the Openshift Sandbox, which is the one that we currently entirely support, is still ok after these changes. I have tested and everything is good to go. 

Thanks!

2021-08-24 11:53 UTC, caponetto approved these changes
Thanks, @rafaeltuelho! :)

2021-08-25 06:58 UTC, tomasdavidorg commented
Hi @caponetto , I was not able to setup the connection with the OpenShift sandbox. Do I need some specific configuration / build parameters?
I built the branch and started the server by:
```
export ONLINE_EDITOR__kieToolingExtendedServicesCompatibleVersion=0.12.1
yarn bootstrap && yarn build:dev
cd packages/online-editor
yarn start
```

After I put the login informations to the modal dialog, I got `Connection refused. Please check the information provided.`.

2021-08-25 12:31 UTC, tomasdavidorg approved these changes
Thanks @caponetto . The issue was that I open the application from http://localhost:9001/ and not from http://0.0.0.0:9001/. Approving.

2021-08-25 12:37 UTC, caponetto commented
@porcelli can we go ahead and merge this PR?

2021-08-25 12:38 UTC, porcelli approved these changes

2021-08-25 12:44 UTC, ederign approved these changes

2021-08-25 12:44 UTC, merged