KOGITO-861: Add an input to paste a file URL in the Online Editor home page
apache/incubator-kie-tools pull request #65
Opened 2020-02-12 15:19 UTC by jesuino

KOGITO-861: Add an input to paste a file URL in the Online Editor home page

Validates and redirect users to edit a valid file URL from online editor home page.

Happy path:

![success_path](https://user-images.githubusercontent.com/359820/74348502-94302000-4d91-11ea-8290-1c46989a28ca.gif)

If user tries to use invalid URL we make three validations:

* Check if it is a valid URL;
* If it has an extension, which is important for us to redirect to the correct editor;
* Finally check if we support that extension.

You can see this in action in gif below

![invalid_URLs](https://user-images.githubusercontent.com/359820/74348598-ba55c000-4d91-11ea-8fe2-50c905299991.gif)

Notice I am changing the app location and skipping the react router so the file can be correctly fetched by index.tsx

2020-02-12 15:38 UTC, kywalker-rh commented
Looks great!

2020-02-12 15:39 UTC, srambach commented
LGTM! 👍

2020-02-12 15:39 UTC, srambach approved these changes

2020-02-12 16:22 UTC, paulovmr commented on packages/online-editor/src/App.tsx
> +            <HomePage router={onlineEditorRouter} onFileOpened={onFileOpened} />
@jesuino you can access the router in the HomePage.tsx by using `context.router`.

2020-02-12 16:53 UTC, jesuino commented on packages/online-editor/src/App.tsx
> +            <HomePage router={onlineEditorRouter} onFileOpened={onFileOpened} />
fixed in https://github.com/kiegroup/kogito-tooling/pull/65/commits/2d2f38a527dde0b7fbb8d2d86f016141cd2fa759

2020-02-14 14:44 UTC, tiagobento requested changes
Changes requested inline 😊

2020-02-14 14:44 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +    window.location.href = `?file=${inputFileUrl}#/editor/${fileType}`;
Hum..... this looks like something that we should be making with the help of our `Router`.

2020-02-14 14:44 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +  const [invalidFileText, setInvalidFileText] = useState("");
These two states behave very similarly. I think you could create an enum describing the state of the input (e.g. BLANK, VALID, INVALID_URL, INVALID_EXTENSION) and derive the message from there. This way you have only one state variable and your component is less complex. Also, it's easier to test, since we're deriving the message from the input state. Of course you can also derive the 'isValidFileUrl' from this enum.

2020-02-14 14:44 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +  };
Remember to use the Hooks! Here's a good case for 'useCallback' with `[]` as its dependencies. This prevents React from creating a new function every time and saves unnecessary renders :)

2020-02-15 05:53 UTC, jesuino commented
@tiagobento I had to make a big commit to re-organize the code and put editors and home page behind the router, I also had to organize error messages and created an error page. Would you please review?

I still need to work on small details, but it is working now.

Thanks!

2020-02-17 15:10 UTC, jesuino commented
Hello @tiagobento , as we talked I created KOGITO-1202 to focus on routes changes and decided to keep window.location change for now, please see https://github.com/kiegroup/kogito-tooling/pull/65/commits/3549d78769337eb447dc52ea732de31645e1f5ec and let me know your thoughts

2020-02-17 19:49 UTC, srambach commented on packages/online-editor/src/home/HomePage.tsx
> +                isValid={inputFileUrlState === InputFileUrlState.VALID}
Although I see the invalid helper text show up, I don't see the form element displaying as invalid (red underline, red !) This is keyed off of the aria-invalid attribute, which is still showing as false (i.e. the field is marked as valid)

2020-02-17 19:51 UTC, srambach commented
@jesuino This looks really nice. Just one other question - it looks like the enter key doesn't open the given URL. Would that be possible to implement?

2020-02-19 16:09 UTC, jesuino commented
@srambach Thank you so much for your input
The reason why enter was not working and the invalid field message was not red is because the form group was not wrapped by a form element. It should all work now (see below). 

@tiagobento would you please review my last commit? Thanks!

This is how it looks like now:

![form_validation_improvement](https://user-images.githubusercontent.com/359820/74848048-90157c80-5314-11ea-9f51-57c4cbb74ef9.gif)

2020-02-19 16:37 UTC, srambach commented
Can a blank input not be marked as invalid? So it only turns red/shows the icon when the field loses focus? That way we aren't showing them an error if they aren't even trying to import from a url, and not when they are still trying to type it in.
(maybe it's that way, it's hard to see from the video)

2020-02-19 18:28 UTC, tiagobento requested changes
Just one change request and a question inline. Looking good @jesuino!

2020-02-19 18:28 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +    }
I believe the exception happens on the `new URL` call, right? So the try catch block should be only there. We don't want to catch other exceptions.

2020-02-19 18:28 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +      return openFile();
Shouldn't it be just `openFile()`?

2020-02-19 19:00 UTC, jesuino commented
@srambach I had the exactly same question, I was expecting your opnion on this, thanks :-) 

@tiagobento  I made the changes

![page_last_test](https://user-images.githubusercontent.com/359820/74866069-fad4b100-5330-11ea-82a1-ca702280bec3.gif)

2020-02-19 21:16 UTC, srambach commented
@jesuino Great! If I clear the field and leave, it stays invalid. Any chance of clearing the invalid state in that case? Otherwise, it looks great!
Enter key working <3

2020-02-21 20:07 UTC, jesuino commented
Hello Sarah,

Thanks for the suggestion. I did implement this behavior in latest version.

Please let me know if you have any question. Thanks!

2020-02-21 20:11 UTC, tiagobento approved these changes
I'm approving that but I'd like to let @srambach give the final approve. @ederign Please do merge it once @srambach approves it. Thanks @jesuino!

2020-02-21 20:46 UTC, srambach commented on packages/online-editor/src/home/HomePage.tsx
> +                  helperTextInvalid={messageForState}
It looks like without a `helperText` prop, when the field is valid, there is an a11y violation because there is no div matching the `aria-describedby` id. I _think_ the "http://" text could be put as the `helperText` and the 3 error states would provide `helperTextInvalid`.

2020-02-21 20:57 UTC, srambach commented on packages/online-editor/src/home/HomePage.tsx
> +                  helperTextInvalid={messageForState}
Looks like just adding a prop `helperText="http://"` will fix the a11y violation. 👍

2020-02-22 02:12 UTC, jesuino commented on packages/online-editor/src/home/HomePage.tsx
> +                  helperTextInvalid={messageForState}
Thank you so much again, Sarah, I added the missing property

2020-02-24 14:24 UTC, srambach approved these changes
Looks great!! 👍

2020-02-26 15:52 UTC, merged