Incorporate `kogito-editors-java`
apache/incubator-kie-tools pull request #729
Opened 2021-12-28 22:07 UTC by tiagobento

This PR incorporates the `kogito-editors-java` repository into the kogito-tooling monorepo.

The entire repository was placed inside the `stunner-editors` directory.

The directory structure is kept identical, except for the `kogito-editors-js` package, which was hoisted into the top level of the monorepo. This avoids nested lerna builds and encourages reusability and enhances the separation of concerns of our packages. The names are kept, with the exception of `dmn-loader`, which is now called `stunner-editors-dmn-loader`.

I also removed the `yarn  build:dev` and `yarn build:prod` commands, as we should begin to choose what we want to build. Two new commands were created -- `yarn build:dev:until [pkg-name]` and `yarn build:prod:until [pkg-name]`.

Of course building everything is still supported with `lerna run build:dev` and `lerna run build:prod`.

Some changes were made to the way the `DMN Loader` package is configured. The `wire` env var was renamed to `DMN_LOADER__outputPath` and is now managed by `build-env`, just like all the other env vars we have.

Maven commands still work normally inside `packages/stunner-editors`.

The envisioned workflow for Editor developers is

1. yarn bootstrap
1. yarn build:dev:until @kogito-tooling/stunner-editors
1. mvn clean gwt:run -f [bpmn/dmn/scesim webapp path]
1. For instructions on how to enable "live-reloading" of React components, refer to DMN Loader's README.

Something that also changed is how we load CSS for React components inside the DMN Editor. The CSS was separate from the JS bundle in production builds. Although this the ideal thing to do, it gives us some challenges due to the discrepancy between dev and prod builds. For this reason, I changed the DMN Loader to use out default Webpack configuration, so everything works the same now. This is an important optimization issue and we're aware that this could be considered a "step back", however, having everything on the same repository is far more important at this time.

I already contacted Jozef and Dominik about the QE builds/checks we have, so this PR can still be updated once I have more information.

2021-12-28 22:07 UTC, tiagobento commented
⚠️ **_NOTE:_** DO NOT SQUASH ⚠️

2022-01-03 12:53 UTC, domhanak commented
@tiagobento I examined the `kie-editors-standalone` it-tests failures and something is not right. The videos suggest that `No commands were run in this test` or that the `cy.loadEditors` is not a function. My suspicion is that there is an issue with config and most probably something overrides the config of `kie-editors-standalone` it tests.

2022-01-03 14:52 UTC, tiagobento commented
@domhanak Yes.. I'm investigating it.

2022-01-06 12:15 UTC, jomarko requested changes
Tests in `./packages/boxed-expression-component/it-tests/integration/` were not started as part of `https://github.com/kiegroup/kogito-tooling/runs/4722385526?check_suite_focus=true` 

We need to run these tests as part of CI builds.

2022-01-06 14:51 UTC, tiagobento commented
@jomarko They are not running on `kogito-editors-java` as well. I tried enabling them, but they were not stable enough yet.

2022-01-06 14:55 UTC, jomarko commented
@tiagobento I can not agree, there were part of regular CI build on `kogito-editors-java` https://github.com/kiegroup/kogito-editors-java/pull/173/files

2022-01-06 15:01 UTC, tiagobento commented
@jomarko Ok, you're right. Let's enable them.

2022-01-10 12:23 UTC, yesamer commented
Thank you for this huge work. After the merge, I think it's crucial to inform the team about the new commands you introduced and their usage, in order to avoid full compilation in local builds.

2022-01-10 12:24 UTC, yesamer approved these changes
Thank you for this huge work. After the merge, I think it's crucial to inform the team about the new commands you introduced and their usage, in order to avoid full compilation in local builds.

2022-01-10 12:24 UTC, yesamer commented on README.md
> +- SceSim
I suggest to use `Test Scenario` instead of `SceSim`

2022-01-11 10:07 UTC, jomarko commented
Thank you @tiagobento for bringing back most of `./boxed-expression-component/it-tests/integration/`. I reported one more jira for `stunner-editors` integration tests https://issues.redhat.com/browse/KOGITO-6518

2022-01-11 10:08 UTC, jomarko approved these changes

2022-01-11 15:00 UTC, romartin approved these changes

2022-01-11 15:31 UTC, ederign approved these changes

2022-01-11 15:32 UTC, merged