KOGITO-6003: Serialize inputs of DMN Runner
apache/incubator-kie-tools pull request #854
Opened 2022-02-15 16:01 UTC by ljmotta

## JIRA
https://issues.redhat.com/browse/KOGITO-6003

## On this PR
- Persist the DMN Runner inputs on the browser
- Make it possible to download/upload inputs

## Persist the DMN Runner inputs on the browser
Now the DMN Runner inputs are persisted on the browser storage. Also, it's synced between the browser tabs. This way, the user doesn't need to be concerned to lose their inputs.

### Example 1 - Inputs persisted on the browser

https://user-images.githubusercontent.com/24302289/154098045-b5477a4a-0eff-474b-b70d-651b25bc2488.mp4

### Example 2 - Sync between tabs

https://user-images.githubusercontent.com/24302289/154098094-bf929530-6201-41e3-ae58-0f107690e29e.mp4

## Make it possible to download/upload inputs
Now two new buttons were added on the "Run" dropdown, with the possibility to download and upload inputs. This new feature makes it possible for users to share inputs with their peers.

https://user-images.githubusercontent.com/24302289/154098755-ce2840d8-1c0c-4ed5-bbfe-11fe9eb548af.mp4

2022-02-18 13:32 UTC, tiagobento requested changes
@ljmotta This PR is awesome. Very well done, Luiz!

I left some comments inline. Mainly related to names and a little bit of design choices. Ultimately, I think we need to think about DMN Runner Inputs without immediately associating it with Workspaces. Although it depends on Workspaces logic and storage etc, DMN Runner Inputs is its own feature, so we **shouldn't** either:

1. Couple Workspaces with DMN Runner Inputs.
2. Mention Workspaces in the DMN Runner Inputs APIs.

Hope that makes sense :D

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/workspace/contexts/WorkspacesDmnInputsContext.tsx
> +interface WorkspacesDmnInputsType {
```suggestion
interface DmnInputsDispatchContextType {
```

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +                        dmnRunnerService.delete(props.workspaceId);
I think we should rather be listening to when a Workspace is deleted and delete its DMN Runner Inputs counterpart, instead of explicitly calling this `delete` everywhere a workspace is deleted.

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +                        dmnRunnerService.delete(props.workspaceId);
Same as above.

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/home/HomePage.tsx
> +              dmnRunnerService.delete(props.workspace.workspaceId);
Same as below.

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/KieSandboxExtendedServices/KieSandboxExtendedServicesButtons.tsx
> +              load inputs
I know you probably followed the same logic of `as Table` to have these be lowercase, but now I think we should change it to `As Form`, `As Table`, `Load inputs`, and `Download Inputs` and `Delete Inputs`.

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/EditorPage.tsx
> +              workspaceId={props.workspaceId}
Can't you get these two pieces of information from the `workspaceFile` prop?

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerTabular.tsx
> +      [dmnRunnerState.inputRows]
Missing a dependency here? `updateDmnRunnerResults`

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerContext.tsx
> +  inputRowsUpdated: boolean;
I think `didUpdateInputRows` would be a better name, WDYT?

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerContext.tsx
> +  outputRowsUpdated: boolean;
I think `didUpdateOutputRows` would be a better name, WDYT?

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerContext.tsx
> +export type InputRow = { [x: string]: string };
I think this can be replaced with a Record<string, string>, doesn't it?

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerDrawerPanelContent.tsx
> +  const [selectedRow, selectRow] = useState<string>("");
🎉

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/editor/DmnRunner/DmnRunnerDrawerPanelContent.tsx
> +      dmnRunnerDispatch.setInputRows((previousData: Array<InputRow>) => {
🎉

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/workspace/services/WorkspaceDmnRunnerInputsService.tsx
> +export class WorkspaceDmnRunnerInputsService {
```suggestion
export class DmnRunnerInputsService {
```

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/workspace/hooks/WorkspaceDmnRunnerInput.tsx
> +export function useWorkspaceDmnRunnerInputs(
```suggestion
export function useDmnRunnerInputs(
```

2022-02-18 13:32 UTC, tiagobento commented on packages/online-editor/src/workspace/contexts/WorkspacesDmnInputsContext.tsx
> +export function useWorkspacesDmnRunnerInputs(): WorkspacesDmnInputsType {
```suggestion
export function useDmnRunnerInputsDispatch(): DmnRunnerInputsDispatchContextType {
```

2022-02-22 07:30 UTC, tomasdavidorg approved these changes

2022-02-25 13:17 UTC, tiagobento approved these changes

2022-02-25 13:17 UTC, merged