Serverless workflow validation
apache/incubator-kie-tools pull request #928
Opened 2022-04-08 06:50 UTC by Sara4994

2022-04-08 08:52 UTC, domhanak commented
is there any JIRA for this?

2022-04-08 08:58 UTC, domhanak commented
please make sure you tag ask for QE review for everything SWF tooling related. Thanks

2022-04-08 12:26 UTC, Sara4994 commented
> please make sure you tag ask for QE review for everything SWF tooling related. Thanks

@domhanak Sure, will make sure I do that next time. Thanks :+1:

2022-04-08 19:41 UTC, paulovmr requested changes

2022-04-08 19:41 UTC, paulovmr commented on packages/notifications/src/vscode/ProblemsTabNotificationHandler.ts
> +      range: new vscode.Range(startLineNumber, startColumn, startLineNumber, endColumn),
Should it be `endLineNumber` at the third parameter?

2022-04-13 11:34 UTC, barboras7 commented
Hi @Sara4994,
I tried to test the validation but I did not succeed. Here's what I did on the swf-validation branch:

- `yarn build:prod:until @kie-tools-core/notifications`
- `yarn build:prod:until vscode-extension-serverless-workflow-editor`

I took the `vscode_extension_serverless_workflow_editor_0.0.0.vsix` and installed it on VSCode. I tried testing with both yaml and json. I took a working *.sw.json and *.sw.yaml. I edited the files in the VSCode so that they were no longer valid. Is this how the feature should be tested? Because I did not see anything in the Problems tab.

2022-04-27 20:44 UTC, paulovmr requested changes
@Sara4994 The code looks good to me, only thing is that sometimes the problems are duplicated in the problems tab:
![image](https://user-images.githubusercontent.com/832830/165627731-f6d66be6-d88b-473f-af88-5568f50e40bb.png)

2022-04-28 20:28 UTC, paulovmr approved these changes

2022-04-28 20:29 UTC, paulovmr commented
The previous issue should be fixed now.

@barboras7 Could you try testing it again please? Thanks.

2022-04-29 13:04 UTC, tiagobento commented
@Sara4994 There are some conflicts here.. can you please address them?

2022-04-29 15:05 UTC, barboras7 approved these changes
The PR looks good, thanks @Sara4994 :+1:

2022-04-29 16:02 UTC, Sara4994 commented
> @Sara4994 There are some conflicts here.. can you please address them?

@tiagobento Conflicts are fixed :+1

2022-04-29 17:35 UTC, tiagobento commented
@Sara4994 Please check the formatting of the files.

2022-04-29 20:26 UTC, paulovmr commented
I've added the form-dmn dependency to unitables-dmn.

2022-04-29 21:38 UTC, merged