Kogito 6918 interaction with name and data type popover with keyboard
apache/incubator-kie-tools pull request #929
Opened 2022-04-08 10:28 UTC by fantonangeli

Fixes: https://issues.redhat.com/browse/KOGITO-6918

![Peek 2022-04-07 16-51](https://user-images.githubusercontent.com/17780574/162416141-4a2a947b-17d9-4885-9cf0-37a29b159b8b.gif)

2022-04-11 07:46 UTC, jomarko approved these changes
Thank you for big amount of tests @fantonangeli

2022-04-11 08:22 UTC, vpellegrino approved these changes
Looks good to me, thanks @fantonangeli

2022-04-11 12:56 UTC, ljmotta requested changes
Hi @fantonangeli , thanks for this PR! I've made some comments inline.

2022-04-11 12:56 UTC, ljmotta commented on packages/boxed-expression-component/src/components/PopoverMenu/PopoverMenu.tsx
> +  const triggerManually = isVisible !== null;
`isVisible` have a default value and it's a boolean, this will not always be true?

2022-04-11 12:56 UTC, ljmotta commented on packages/boxed-expression-component/src/components/PopoverMenu/PopoverMenu.tsx
> +  const [isPopoverVisible, setIsPopoverVisible] = useState(false);
If `triggerManually` is `true` then we're going to have two states controlling the same thing (the `isVisible` on the parent component and the `isPopoverVisible` on PopoverMenu). This will cause a render delay. This happens because `isVisible` needs to be updated to trigger the `useEffect` and update the `isPopoverVisible`. To fix this issue, you can make a forwarding ref and expose `isPopoverVisible` and `setIsPopoverVisible` through the ref, using the `useImperativeHandle` hook.

2022-04-12 08:26 UTC, fantonangeli commented on packages/boxed-expression-component/src/components/PopoverMenu/PopoverMenu.tsx
> +  const [isPopoverVisible, setIsPopoverVisible] = useState(false);
Thank you for your interesting comments @ljmotta , I will try to follow your suggestion and update this PR next week.

2022-04-20 12:19 UTC, fantonangeli commented on packages/boxed-expression-component/src/components/PopoverMenu/PopoverMenu.tsx
> +  const [isPopoverVisible, setIsPopoverVisible] = useState(false);
Hi @ljmotta, I updated the code to use `useImperativeHandle` and checked with a counter in the `PopoverMenu` component to see how many times is re-rendered, but I don't see a difference for the first rendering. 
I only see the difference when the user closes the popover and it is saving only one rendering.

2022-04-22 17:27 UTC, ljmotta approved these changes
LGTM!

2022-04-26 11:02 UTC, yesamer approved these changes

2022-04-26 12:00 UTC, merged