KOGITO-1426: Re-enable Resource Content API
apache/incubator-kie-tools pull request #93
Opened 2020-03-25 16:53 UTC by pefernan

Restoring ResourceContentAPI... @tiagobento could you please take a look?

This is part of an ensemble, please merge with:

2020-03-25 20:31 UTC, tiagobento approved these changes
Thx Pere! Glad you managed to get it back :)

2020-03-26 10:22 UTC, domhanak commented
Built the stack, I was able to use custom email icons for my Workitems.

![image](https://user-images.githubusercontent.com/5937251/77636044-c9fd2280-6f53-11ea-9b29-25b2936227b3.png)

These two methods could use some unit tests. Please add them before merging, otherwise looks good.

2020-04-02 13:34 UTC, pefernan commented
@tiagobento @jesuino would you mind do a second review?

2020-04-06 19:35 UTC, tiagobento commented
@pefernan Can you please rebase your branch with master? We updated the CI.

2020-04-07 10:49 UTC, pefernan commented
@tiagobento done thanks!

2020-04-07 13:38 UTC, tiagobento requested changes
Thanks for updating the PR, @pefernan! I left some minor comments inline.

2020-04-07 13:38 UTC, tiagobento commented on packages/core-api/src/content/SearchType.ts
> +}
This enum is in a file with named `SearchType.ts`. Can you rename it to `ListType.ts`?

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeInnerResourceContentService.ts
> +export class VsCodeInnerResourceContentServiceFactory {
This name conflicts with some other abstractions around Inner/Outer that we have. In our codebase, inner refers to "within the envelope", and it doesn't seem like that's the case here. Can you please rename it?

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    this.searchFactory = new VsCodeInnerResourceContentServiceFactory(editorStore);
I think it's better if we instantiate this outside the constructor. This line makes `VsCodeResourceContentService` depend on `KogitoEditorStore`, but actually, it depends on `VsCodeInnerResourceContentServiceFactory`

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeResourceContentService.ts
> +    this.searchFactory = new VsCodeInnerResourceContentServiceFactory(editorStore);
Also, `searchFactory` is probably not a good name?

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeInnerResourceContentService.ts
> +  }
Since this is a factory, we should expect a "create" method or something like that. Lookup gives the idea of returning something that already existis, which is not the case, can you rename it too?

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeInnerResourceContentService.ts
> +}
How's this interface different from `ResourceContentService`?

2020-04-07 13:38 UTC, tiagobento commented on packages/vscode-extension/src/VsCodeInnerResourceContentService.ts
> +    expr += pattern;
I would make this a ternary expression to remove the mutable variable.

```typescript
const expr = opts?.type === ListType.ASSET_FOLDER
  ? getParentFolder(this.editor.relativePath) + pattern
  : pattern;
```

2020-04-07 14:46 UTC, ederign commented
@domhanak as you review the related PR's, could you please take a look on this one as well.

2020-04-08 11:36 UTC, pefernan commented
@tiagobento added some changes

2020-04-08 13:36 UTC, domhanak requested changes
I am unable to complete this use case:
1. Create a process
2. Add `email` service tasks (start -> email -> end)
3. Save & close
4. Reopen
5. Process has only `start` event

Nothing is shown in console, problems, or debug tab.

Workaround: 
1. Open properties panel
2. Open Data Assignments
3. Close them.
4. Save & close
5. Reopen and process is there

@romartin if I recall correctly this is what you mentioned on stunner meeting? Imho if a user wants to do a quick sketch, he shouldn't need to open properties at all.
I am ok to approve if we have it reported in jira, let me know if there is one already.

2020-04-08 14:33 UTC, romartin commented
Hey @domhanak 

yep there is a bug with service tasks, but the PR for the fix is still opened:

https://github.com/kiegroup/kie-wb-common/pull/3235

I'm just waiting for this to be merged in order to rebase and start the testing for the PR above.

Thanks!

2020-04-08 16:26 UTC, dgutierr approved these changes
@pefernan I just approved. Given the urgency and the fact that the issue @domhanak reported is already fixed in the dependen PR roger linked. Please do merge.

2020-04-08 17:31 UTC, tiagobento approved these changes

2020-04-08 20:57 UTC, merged