[KOGITO-1436] Remove double setContent call
apache/incubator-kie-tools pull request #95
Opened 2020-03-25 21:02 UTC by ederign

.

2020-03-25 21:26 UTC, manstis commented
@ederign IDK if you have another PR coming but you probably need to update [appformer](https://github.com/kiegroup/appformer/blob/master/uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java#L128) too?

2020-03-25 21:28 UTC, ederign commented
@manstis absolutely, I'm creating right now  one  over https://github.com/kiegroup/kie-wb-common/pull/3236/files

2020-03-25 22:33 UTC, tiagobento commented on packages/microeditor-envelope/src/EditorEnvelopeController.tsx
> +            .finally(() => this.editorEnvelopeView!.setLoadingFinished());
🙏😱☝️👌😉

2020-03-25 22:35 UTC, tiagobento requested changes
Looks great. Just an extra import there. Please remove it. Thanks @ederign!

2020-03-25 22:35 UTC, tiagobento commented on packages/microeditor-envelope/src/__tests__/EditorEnvelopeController.test.tsx
> +import { promises } from "fs";
Please remove this line.

2020-03-26 03:09 UTC, romartin approved these changes

2020-03-26 10:57 UTC, manstis approved these changes

2020-03-26 14:38 UTC, jomarko commented
### Manually tried scenarios
In VS code open
- [ ] Valid bpmn, do changes, reopen
- [ ] Invalid bpmn, fix, reopen
- [ ] Valid dmn, do changes, reopen
- [ ] Invalid dmn, fix, reopen

2020-03-26 14:44 UTC, jomarko commented
When user tries to open invalid BPMN process, ace/xml editor is not shown. Even if I confirm no such element popup from screenshot, ace/xml editor is not shown. Fr dmn it works fine.
![Screenshot from 2020-03-26 15-41-24](https://user-images.githubusercontent.com/8044780/77659611-94b6fb80-6f78-11ea-8494-4908dad930ab.png)

2020-03-26 17:24 UTC, ederign commented on packages/microeditor-envelope/src/__tests__/EditorEnvelopeController.test.tsx
> +import { promises } from "fs";
fixed.

2020-03-26 17:34 UTC, ederign commented
@jomarko I've updated all the PR's as you requested.

I'm not sure if the invalid BPMN issue is related to changes on this PR. @romartin any idea?

2020-03-26 17:41 UTC, tiagobento approved these changes

2020-03-26 17:52 UTC, romartin commented
@ederign @jomarko good catch about the invalid bpmn file guys. TBH no idea, but I don't think it should be related to this. 

I would suggest merging this, which is preventing several things to move forward, and report the "invalid bpmn issue" so I'll take a look later on. WDYT?

Thanks!!

2020-03-26 18:41 UTC, lazarotti commented
@ederign @jomarko @romartin as this has blocked many other PRs I strongly suggest go ahead with the merge and create a new Jira focused only on invalid xml as it is in fact part of a different use case

2020-03-26 19:32 UTC, merged

2020-03-26 19:58 UTC, manstis commented
@romartin there's an old JIRA for BPMN kicking around somewhere about falling back to ACE for invalid files. It is unrelated to this PR.

2020-03-26 21:49 UTC, jomarko commented
@manstis if you have a link, would be good paste it here for a record.

2020-03-27 08:50 UTC, manstis commented
@jomarko here's a link that just popped up in my inbox https://issues.redhat.com/browse/KOGITO-513.. I am sure there are others similar.

2020-03-27 08:52 UTC, jomarko commented
@manstis thank you, I came across this one too.